-- ==============================================================
-- Generated by Vitis HLS v2023.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity fsk_lpf is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    in_r_TDATA : IN STD_LOGIC_VECTOR (15 downto 0);
    in_r_TVALID : IN STD_LOGIC;
    in_r_TREADY : OUT STD_LOGIC;
    in_r_TKEEP : IN STD_LOGIC_VECTOR (1 downto 0);
    in_r_TSTRB : IN STD_LOGIC_VECTOR (1 downto 0);
    in_r_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    out_r_TDATA : OUT STD_LOGIC_VECTOR (15 downto 0);
    out_r_TVALID : OUT STD_LOGIC;
    out_r_TREADY : IN STD_LOGIC;
    out_r_TKEEP : OUT STD_LOGIC_VECTOR (1 downto 0);
    out_r_TSTRB : OUT STD_LOGIC_VECTOR (1 downto 0);
    out_r_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0) );
end;


architecture behav of fsk_lpf is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "fsk_lpf_fsk_lpf,hls_ip_2023_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=pipeline,HLS_SYN_CLOCK=6.565875,HLS_SYN_LAT=8,HLS_SYN_TPT=1,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=1079,HLS_SYN_LUT=387,HLS_VERSION=2023_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_21 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100001";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv18_38000 : STD_LOGIC_VECTOR (17 downto 0) := "111000000000000000";
    constant ap_const_lv16_7FFF : STD_LOGIC_VECTOR (15 downto 0) := "0111111111111111";
    constant ap_const_lv16_8000 : STD_LOGIC_VECTOR (15 downto 0) := "1000000000000000";
    constant ap_const_lv32_602F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000110000000101111";
    constant ap_const_lv33_4FF4 : STD_LOGIC_VECTOR (32 downto 0) := "000000000000000000100111111110100";
    constant ap_const_lv31_26FA : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000010011011111010";
    constant ap_const_lv28_77A : STD_LOGIC_VECTOR (27 downto 0) := "0000000000000000011101111010";
    constant ap_const_lv29_1FFFFB9E : STD_LOGIC_VECTOR (28 downto 0) := "11111111111111111101110011110";
    constant ap_const_lv29_1FFFFA98 : STD_LOGIC_VECTOR (28 downto 0) := "11111111111111111101010011000";
    constant ap_const_lv28_FFFFD56 : STD_LOGIC_VECTOR (27 downto 0) := "1111111111111111110101010110";
    constant ap_const_lv33_686C : STD_LOGIC_VECTOR (32 downto 0) := "000000000000000000110100001101100";
    constant ap_const_lv32_3B8A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000011101110001010";
    constant ap_const_lv31_14C6 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000001010011000110";
    constant ap_const_lv24_FFFFDA : STD_LOGIC_VECTOR (23 downto 0) := "111111111111111111011010";
    constant ap_const_lv29_1FFFFA2E : STD_LOGIC_VECTOR (28 downto 0) := "11111111111111111101000101110";
    constant ap_const_lv29_1FFFFBE1 : STD_LOGIC_VECTOR (28 downto 0) := "11111111111111111101111100001";
    constant ap_const_lv27_7FFFE9D : STD_LOGIC_VECTOR (26 downto 0) := "111111111111111111010011101";

    signal ap_rst_n_inv : STD_LOGIC;
    signal fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_7 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_6 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_5 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_4 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_3 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_2 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_17 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_16 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_15 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_14 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_13 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_12 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_11 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_10 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_9 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_8 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal fsk_lpf_stream_axis_0_stream_axis_ap_int_16_0ul_0ul_0ul_0_delay : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal fsk_lpf_stream_axis_0_stream_axis_ap_int_16_0ul_0ul_0ul_0_delay_1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal fsk_lpf_stream_axis_0_stream_axis_ap_int_16_0ul_0ul_0ul_0_delay_2 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal fsk_lpf_stream_axis_0_stream_axis_ap_int_16_0ul_0ul_0ul_0_delay_3 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal fsk_lpf_stream_axis_0_stream_axis_ap_int_16_0ul_0ul_0ul_0_delay_4 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal fsk_lpf_stream_axis_0_stream_axis_ap_int_16_0ul_0ul_0ul_0_delay_5 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal fsk_lpf_stream_axis_0_stream_axis_ap_int_16_0ul_0ul_0ul_0_delay_6 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal fsk_lpf_stream_axis_0_stream_axis_ap_int_16_0ul_0ul_0ul_0_delay_7 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal fsk_lpf_stream_axis_0_stream_axis_ap_int_16_0ul_0ul_0ul_0_delay_8 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal fsk_lpf_stream_axis_0_stream_axis_ap_int_16_0ul_0ul_0ul_0_delay_9 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal in_r_TDATA_blk_n : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal out_r_TDATA_blk_n : STD_LOGIC;
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter8 : STD_LOGIC := '0';
    signal din_data_reg_893 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter5 : BOOLEAN;
    signal ap_block_state7_pp0_stage0_iter6 : BOOLEAN;
    signal ap_block_state8_pp0_stage0_iter7 : BOOLEAN;
    signal regslice_both_out_r_V_data_V_U_apdone_blk : STD_LOGIC;
    signal ap_block_state9_pp0_stage0_iter8 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal din_last_reg_898 : STD_LOGIC_VECTOR (0 downto 0);
    signal din_last_reg_898_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal din_last_reg_898_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal din_last_reg_898_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal din_last_reg_898_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal din_last_reg_898_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal din_last_reg_898_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_30_reg_903 : STD_LOGIC_VECTOR (15 downto 0);
    signal fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_32_reg_909 : STD_LOGIC_VECTOR (15 downto 0);
    signal fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_34_reg_914 : STD_LOGIC_VECTOR (15 downto 0);
    signal fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_36_reg_919 : STD_LOGIC_VECTOR (15 downto 0);
    signal fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_38_reg_924 : STD_LOGIC_VECTOR (15 downto 0);
    signal fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_40_reg_929 : STD_LOGIC_VECTOR (15 downto 0);
    signal fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_43_reg_934 : STD_LOGIC_VECTOR (15 downto 0);
    signal fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_44_reg_939 : STD_LOGIC_VECTOR (15 downto 0);
    signal fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_47_reg_944 : STD_LOGIC_VECTOR (15 downto 0);
    signal fsk_lpf_stream_axis_0_stream_axis_ap_int_16_0ul_0ul_0ul_0_delay_1_load_reg_949 : STD_LOGIC_VECTOR (15 downto 0);
    signal fsk_lpf_stream_axis_0_stream_axis_ap_int_16_0ul_0ul_0ul_0_delay_3_load_reg_954 : STD_LOGIC_VECTOR (15 downto 0);
    signal fsk_lpf_stream_axis_0_stream_axis_ap_int_16_0ul_0ul_0ul_0_delay_5_load_reg_959 : STD_LOGIC_VECTOR (15 downto 0);
    signal fsk_lpf_stream_axis_0_stream_axis_ap_int_16_0ul_0ul_0ul_0_delay_7_load_reg_964 : STD_LOGIC_VECTOR (15 downto 0);
    signal fsk_lpf_stream_axis_0_stream_axis_ap_int_16_0ul_0ul_0ul_0_delay_9_load_reg_969 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp29_fu_600_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp29_reg_974 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_fu_771_p3 : STD_LOGIC_VECTOR (32 downto 0);
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal grp_fu_779_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal grp_fu_787_p3 : STD_LOGIC_VECTOR (27 downto 0);
    signal grp_fu_795_p3 : STD_LOGIC_VECTOR (28 downto 0);
    signal grp_fu_803_p3 : STD_LOGIC_VECTOR (28 downto 0);
    signal grp_fu_811_p3 : STD_LOGIC_VECTOR (27 downto 0);
    signal grp_fu_819_p4 : STD_LOGIC_VECTOR (32 downto 0);
    signal add_ln131_1_reg_1020 : STD_LOGIC_VECTOR (32 downto 0);
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal add_ln131_1_reg_1020_pp0_iter5_reg : STD_LOGIC_VECTOR (32 downto 0);
    signal add_ln131_4_fu_644_p2 : STD_LOGIC_VECTOR (32 downto 0);
    attribute use_dsp48 : string;
    attribute use_dsp48 of add_ln131_4_fu_644_p2 : signal is "no";
    signal add_ln131_4_reg_1025 : STD_LOGIC_VECTOR (32 downto 0);
    signal add_ln131_4_reg_1025_pp0_iter5_reg : STD_LOGIC_VECTOR (32 downto 0);
    signal grp_fu_851_p4 : STD_LOGIC_VECTOR (27 downto 0);
    signal add_ln131_6_reg_1030 : STD_LOGIC_VECTOR (27 downto 0);
    signal grp_fu_861_p4 : STD_LOGIC_VECTOR (28 downto 0);
    signal add_ln131_7_reg_1035 : STD_LOGIC_VECTOR (28 downto 0);
    signal add_ln131_11_fu_652_p2 : STD_LOGIC_VECTOR (28 downto 0);
    attribute use_dsp48 of add_ln131_11_fu_652_p2 : signal is "no";
    signal add_ln131_11_reg_1040 : STD_LOGIC_VECTOR (28 downto 0);
    signal add_ln131_12_fu_672_p2 : STD_LOGIC_VECTOR (29 downto 0);
    signal add_ln131_12_reg_1045 : STD_LOGIC_VECTOR (29 downto 0);
    signal acc_fu_693_p2 : STD_LOGIC_VECTOR (33 downto 0);
    signal acc_reg_1050 : STD_LOGIC_VECTOR (33 downto 0);
    signal icmp_ln139_fu_719_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln139_reg_1055 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln142_fu_725_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln142_reg_1061 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_48_fu_596_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_48_fu_596_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal sext_ln131_fu_551_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal p_shl_fu_606_p3 : STD_LOGIC_VECTOR (23 downto 0);
    signal p_shl1_fu_617_p3 : STD_LOGIC_VECTOR (18 downto 0);
    signal p_shl1_cast_fu_624_p1 : STD_LOGIC_VECTOR (24 downto 0);
    signal p_shl_cast_fu_613_p1 : STD_LOGIC_VECTOR (24 downto 0);
    signal tmp30_fu_628_p2 : STD_LOGIC_VECTOR (24 downto 0);
    signal grp_fu_760_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_840_p4 : STD_LOGIC_VECTOR (30 downto 0);
    signal sext_ln131_32_fu_641_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal grp_fu_829_p4 : STD_LOGIC_VECTOR (32 downto 0);
    signal grp_fu_882_p4 : STD_LOGIC_VECTOR (27 downto 0);
    signal sext_ln131_36_fu_649_p1 : STD_LOGIC_VECTOR (28 downto 0);
    signal grp_fu_871_p4 : STD_LOGIC_VECTOR (28 downto 0);
    signal sext_ln131_35_fu_660_p1 : STD_LOGIC_VECTOR (29 downto 0);
    signal sext_ln131_34_fu_657_p1 : STD_LOGIC_VECTOR (29 downto 0);
    signal sext_ln131_37_fu_669_p1 : STD_LOGIC_VECTOR (29 downto 0);
    signal add_ln131_8_fu_663_p2 : STD_LOGIC_VECTOR (29 downto 0);
    signal sext_ln131_33_fu_681_p1 : STD_LOGIC_VECTOR (33 downto 0);
    signal sext_ln131_31_fu_678_p1 : STD_LOGIC_VECTOR (33 downto 0);
    signal sext_ln131_38_fu_690_p1 : STD_LOGIC_VECTOR (33 downto 0);
    signal add_ln131_5_fu_684_p2 : STD_LOGIC_VECTOR (33 downto 0);
    signal tmp_1_fu_709_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln_fu_699_p4 : STD_LOGIC_VECTOR (17 downto 0);
    signal or_ln139_fu_747_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln139_fu_740_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal dout_data_fu_731_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_760_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal grp_fu_771_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal grp_fu_779_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal grp_fu_787_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_fu_795_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal grp_fu_803_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal grp_fu_811_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_fu_819_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal grp_fu_829_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal grp_fu_840_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal grp_fu_851_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_fu_861_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal grp_fu_871_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal grp_fu_882_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_fu_760_ce : STD_LOGIC;
    signal grp_fu_771_ce : STD_LOGIC;
    signal grp_fu_779_ce : STD_LOGIC;
    signal grp_fu_787_ce : STD_LOGIC;
    signal grp_fu_795_ce : STD_LOGIC;
    signal grp_fu_803_ce : STD_LOGIC;
    signal grp_fu_811_ce : STD_LOGIC;
    signal grp_fu_819_ce : STD_LOGIC;
    signal grp_fu_829_ce : STD_LOGIC;
    signal grp_fu_840_ce : STD_LOGIC;
    signal grp_fu_851_ce : STD_LOGIC;
    signal grp_fu_861_ce : STD_LOGIC;
    signal grp_fu_871_ce : STD_LOGIC;
    signal grp_fu_882_ce : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reset_idle_pp0 : STD_LOGIC;
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal regslice_both_in_r_V_data_V_U_apdone_blk : STD_LOGIC;
    signal in_r_TDATA_int_regslice : STD_LOGIC_VECTOR (15 downto 0);
    signal in_r_TVALID_int_regslice : STD_LOGIC;
    signal in_r_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_in_r_V_data_V_U_ack_in : STD_LOGIC;
    signal regslice_both_in_r_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal in_r_TKEEP_int_regslice : STD_LOGIC_VECTOR (1 downto 0);
    signal regslice_both_in_r_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_in_r_V_keep_V_U_ack_in : STD_LOGIC;
    signal regslice_both_in_r_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal in_r_TSTRB_int_regslice : STD_LOGIC_VECTOR (1 downto 0);
    signal regslice_both_in_r_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_in_r_V_strb_V_U_ack_in : STD_LOGIC;
    signal regslice_both_in_r_V_last_V_U_apdone_blk : STD_LOGIC;
    signal in_r_TLAST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_in_r_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_in_r_V_last_V_U_ack_in : STD_LOGIC;
    signal out_r_TDATA_int_regslice : STD_LOGIC_VECTOR (15 downto 0);
    signal out_r_TVALID_int_regslice : STD_LOGIC;
    signal out_r_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_out_r_V_data_V_U_vld_out : STD_LOGIC;
    signal regslice_both_out_r_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_out_r_V_keep_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_out_r_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_out_r_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_out_r_V_strb_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_out_r_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_out_r_V_last_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_out_r_V_last_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_out_r_V_last_V_U_vld_out : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component fsk_lpf_ama_addmuladd_16s_16s_15ns_25s_32_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        din3_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        din2 : IN STD_LOGIC_VECTOR (14 downto 0);
        din3 : IN STD_LOGIC_VECTOR (24 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component fsk_lpf_am_addmul_16s_16s_15ns_33_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        din2 : IN STD_LOGIC_VECTOR (14 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (32 downto 0) );
    end component;


    component fsk_lpf_am_addmul_16s_16s_14ns_31_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        din2 : IN STD_LOGIC_VECTOR (13 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (30 downto 0) );
    end component;


    component fsk_lpf_am_addmul_16s_16s_11ns_28_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        din2 : IN STD_LOGIC_VECTOR (10 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (27 downto 0) );
    end component;


    component fsk_lpf_am_addmul_16s_16s_12s_29_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        din2 : IN STD_LOGIC_VECTOR (11 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (28 downto 0) );
    end component;


    component fsk_lpf_am_addmul_16s_16s_11s_28_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        din2 : IN STD_LOGIC_VECTOR (10 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (27 downto 0) );
    end component;


    component fsk_lpf_ama_addmuladd_16s_16s_15ns_32s_33_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        din3_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        din2 : IN STD_LOGIC_VECTOR (14 downto 0);
        din3 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (32 downto 0) );
    end component;


    component fsk_lpf_ama_addmuladd_16s_16s_14ns_33s_33_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        din3_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        din2 : IN STD_LOGIC_VECTOR (13 downto 0);
        din3 : IN STD_LOGIC_VECTOR (32 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (32 downto 0) );
    end component;


    component fsk_lpf_ama_addmuladd_16s_16s_13ns_31s_31_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        din3_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        din2 : IN STD_LOGIC_VECTOR (12 downto 0);
        din3 : IN STD_LOGIC_VECTOR (30 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (30 downto 0) );
    end component;


    component fsk_lpf_ama_addmuladd_16s_16s_7s_28s_28_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        din3_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        din2 : IN STD_LOGIC_VECTOR (6 downto 0);
        din3 : IN STD_LOGIC_VECTOR (27 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (27 downto 0) );
    end component;


    component fsk_lpf_ama_addmuladd_16s_16s_12s_29s_29_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        din3_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        din2 : IN STD_LOGIC_VECTOR (11 downto 0);
        din3 : IN STD_LOGIC_VECTOR (28 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (28 downto 0) );
    end component;


    component fsk_lpf_ama_addmuladd_16s_16s_10s_28s_28_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        din3_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        din2 : IN STD_LOGIC_VECTOR (9 downto 0);
        din3 : IN STD_LOGIC_VECTOR (27 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (27 downto 0) );
    end component;


    component fsk_lpf_regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    ama_addmuladd_16s_16s_15ns_25s_32_4_1_U1 : component fsk_lpf_ama_addmuladd_16s_16s_15ns_25s_32_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        din2_WIDTH => 15,
        din3_WIDTH => 25,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_10,
        din1 => fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_13,
        din2 => grp_fu_760_p2,
        din3 => tmp30_fu_628_p2,
        ce => grp_fu_760_ce,
        dout => grp_fu_760_p4);

    am_addmul_16s_16s_15ns_33_4_1_U2 : component fsk_lpf_am_addmul_16s_16s_15ns_33_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        din2_WIDTH => 15,
        dout_WIDTH => 33)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_9,
        din1 => fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_14,
        din2 => grp_fu_771_p2,
        ce => grp_fu_771_ce,
        dout => grp_fu_771_p3);

    am_addmul_16s_16s_14ns_31_4_1_U3 : component fsk_lpf_am_addmul_16s_16s_14ns_31_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        din2_WIDTH => 14,
        dout_WIDTH => 31)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => fsk_lpf_stream_axis_0_stream_axis_ap_int_16_0ul_0ul_0ul_0_delay,
        din1 => fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_16,
        din2 => grp_fu_779_p2,
        ce => grp_fu_779_ce,
        dout => grp_fu_779_p3);

    am_addmul_16s_16s_11ns_28_4_1_U4 : component fsk_lpf_am_addmul_16s_16s_11ns_28_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        din2_WIDTH => 11,
        dout_WIDTH => 28)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => fsk_lpf_stream_axis_0_stream_axis_ap_int_16_0ul_0ul_0ul_0_delay_2,
        din1 => fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay,
        din2 => grp_fu_787_p2,
        ce => grp_fu_787_ce,
        dout => grp_fu_787_p3);

    am_addmul_16s_16s_12s_29_4_1_U5 : component fsk_lpf_am_addmul_16s_16s_12s_29_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        din2_WIDTH => 12,
        dout_WIDTH => 29)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => fsk_lpf_stream_axis_0_stream_axis_ap_int_16_0ul_0ul_0ul_0_delay_4,
        din1 => fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_1,
        din2 => grp_fu_795_p2,
        ce => grp_fu_795_ce,
        dout => grp_fu_795_p3);

    am_addmul_16s_16s_12s_29_4_1_U6 : component fsk_lpf_am_addmul_16s_16s_12s_29_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        din2_WIDTH => 12,
        dout_WIDTH => 29)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => fsk_lpf_stream_axis_0_stream_axis_ap_int_16_0ul_0ul_0ul_0_delay_6,
        din1 => fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_3,
        din2 => grp_fu_803_p2,
        ce => grp_fu_803_ce,
        dout => grp_fu_803_p3);

    am_addmul_16s_16s_11s_28_4_1_U7 : component fsk_lpf_am_addmul_16s_16s_11s_28_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        din2_WIDTH => 11,
        dout_WIDTH => 28)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => fsk_lpf_stream_axis_0_stream_axis_ap_int_16_0ul_0ul_0ul_0_delay_8,
        din1 => fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_5,
        din2 => grp_fu_811_p2,
        ce => grp_fu_811_ce,
        dout => grp_fu_811_p3);

    ama_addmuladd_16s_16s_15ns_32s_33_4_1_U8 : component fsk_lpf_ama_addmuladd_16s_16s_15ns_32s_33_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        din2_WIDTH => 15,
        din3_WIDTH => 32,
        dout_WIDTH => 33)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_44_reg_939,
        din1 => fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_43_reg_934,
        din2 => grp_fu_819_p2,
        din3 => grp_fu_760_p4,
        ce => grp_fu_819_ce,
        dout => grp_fu_819_p4);

    ama_addmuladd_16s_16s_14ns_33s_33_4_1_U9 : component fsk_lpf_ama_addmuladd_16s_16s_14ns_33s_33_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        din2_WIDTH => 14,
        din3_WIDTH => 33,
        dout_WIDTH => 33)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_47_reg_944,
        din1 => fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_40_reg_929,
        din2 => grp_fu_829_p2,
        din3 => grp_fu_771_p3,
        ce => grp_fu_829_ce,
        dout => grp_fu_829_p4);

    ama_addmuladd_16s_16s_13ns_31s_31_4_1_U10 : component fsk_lpf_ama_addmuladd_16s_16s_13ns_31s_31_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        din2_WIDTH => 13,
        din3_WIDTH => 31,
        dout_WIDTH => 31)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => fsk_lpf_stream_axis_0_stream_axis_ap_int_16_0ul_0ul_0ul_0_delay_1_load_reg_949,
        din1 => fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_38_reg_924,
        din2 => grp_fu_840_p2,
        din3 => grp_fu_779_p3,
        ce => grp_fu_840_ce,
        dout => grp_fu_840_p4);

    ama_addmuladd_16s_16s_7s_28s_28_4_1_U11 : component fsk_lpf_ama_addmuladd_16s_16s_7s_28s_28_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        din2_WIDTH => 7,
        din3_WIDTH => 28,
        dout_WIDTH => 28)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => fsk_lpf_stream_axis_0_stream_axis_ap_int_16_0ul_0ul_0ul_0_delay_3_load_reg_954,
        din1 => fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_36_reg_919,
        din2 => grp_fu_851_p2,
        din3 => grp_fu_787_p3,
        ce => grp_fu_851_ce,
        dout => grp_fu_851_p4);

    ama_addmuladd_16s_16s_12s_29s_29_4_1_U12 : component fsk_lpf_ama_addmuladd_16s_16s_12s_29s_29_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        din2_WIDTH => 12,
        din3_WIDTH => 29,
        dout_WIDTH => 29)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => fsk_lpf_stream_axis_0_stream_axis_ap_int_16_0ul_0ul_0ul_0_delay_5_load_reg_959,
        din1 => fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_34_reg_914,
        din2 => grp_fu_861_p2,
        din3 => grp_fu_795_p3,
        ce => grp_fu_861_ce,
        dout => grp_fu_861_p4);

    ama_addmuladd_16s_16s_12s_29s_29_4_1_U13 : component fsk_lpf_ama_addmuladd_16s_16s_12s_29s_29_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        din2_WIDTH => 12,
        din3_WIDTH => 29,
        dout_WIDTH => 29)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => fsk_lpf_stream_axis_0_stream_axis_ap_int_16_0ul_0ul_0ul_0_delay_7_load_reg_964,
        din1 => fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_32_reg_909,
        din2 => grp_fu_871_p2,
        din3 => grp_fu_803_p3,
        ce => grp_fu_871_ce,
        dout => grp_fu_871_p4);

    ama_addmuladd_16s_16s_10s_28s_28_4_1_U14 : component fsk_lpf_ama_addmuladd_16s_16s_10s_28s_28_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        din2_WIDTH => 10,
        din3_WIDTH => 28,
        dout_WIDTH => 28)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => fsk_lpf_stream_axis_0_stream_axis_ap_int_16_0ul_0ul_0ul_0_delay_9_load_reg_969,
        din1 => fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_30_reg_903,
        din2 => grp_fu_882_p2,
        din3 => grp_fu_811_p3,
        ce => grp_fu_882_ce,
        dout => grp_fu_882_p4);

    regslice_both_in_r_V_data_V_U : component fsk_lpf_regslice_both
    generic map (
        DataWidth => 16)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_r_TDATA,
        vld_in => in_r_TVALID,
        ack_in => regslice_both_in_r_V_data_V_U_ack_in,
        data_out => in_r_TDATA_int_regslice,
        vld_out => in_r_TVALID_int_regslice,
        ack_out => in_r_TREADY_int_regslice,
        apdone_blk => regslice_both_in_r_V_data_V_U_apdone_blk);

    regslice_both_in_r_V_keep_V_U : component fsk_lpf_regslice_both
    generic map (
        DataWidth => 2)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_r_TKEEP,
        vld_in => in_r_TVALID,
        ack_in => regslice_both_in_r_V_keep_V_U_ack_in,
        data_out => in_r_TKEEP_int_regslice,
        vld_out => regslice_both_in_r_V_keep_V_U_vld_out,
        ack_out => in_r_TREADY_int_regslice,
        apdone_blk => regslice_both_in_r_V_keep_V_U_apdone_blk);

    regslice_both_in_r_V_strb_V_U : component fsk_lpf_regslice_both
    generic map (
        DataWidth => 2)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_r_TSTRB,
        vld_in => in_r_TVALID,
        ack_in => regslice_both_in_r_V_strb_V_U_ack_in,
        data_out => in_r_TSTRB_int_regslice,
        vld_out => regslice_both_in_r_V_strb_V_U_vld_out,
        ack_out => in_r_TREADY_int_regslice,
        apdone_blk => regslice_both_in_r_V_strb_V_U_apdone_blk);

    regslice_both_in_r_V_last_V_U : component fsk_lpf_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_r_TLAST,
        vld_in => in_r_TVALID,
        ack_in => regslice_both_in_r_V_last_V_U_ack_in,
        data_out => in_r_TLAST_int_regslice,
        vld_out => regslice_both_in_r_V_last_V_U_vld_out,
        ack_out => in_r_TREADY_int_regslice,
        apdone_blk => regslice_both_in_r_V_last_V_U_apdone_blk);

    regslice_both_out_r_V_data_V_U : component fsk_lpf_regslice_both
    generic map (
        DataWidth => 16)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => out_r_TDATA_int_regslice,
        vld_in => out_r_TVALID_int_regslice,
        ack_in => out_r_TREADY_int_regslice,
        data_out => out_r_TDATA,
        vld_out => regslice_both_out_r_V_data_V_U_vld_out,
        ack_out => out_r_TREADY,
        apdone_blk => regslice_both_out_r_V_data_V_U_apdone_blk);

    regslice_both_out_r_V_keep_V_U : component fsk_lpf_regslice_both
    generic map (
        DataWidth => 2)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => ap_const_lv2_3,
        vld_in => out_r_TVALID_int_regslice,
        ack_in => regslice_both_out_r_V_keep_V_U_ack_in_dummy,
        data_out => out_r_TKEEP,
        vld_out => regslice_both_out_r_V_keep_V_U_vld_out,
        ack_out => out_r_TREADY,
        apdone_blk => regslice_both_out_r_V_keep_V_U_apdone_blk);

    regslice_both_out_r_V_strb_V_U : component fsk_lpf_regslice_both
    generic map (
        DataWidth => 2)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => ap_const_lv2_3,
        vld_in => out_r_TVALID_int_regslice,
        ack_in => regslice_both_out_r_V_strb_V_U_ack_in_dummy,
        data_out => out_r_TSTRB,
        vld_out => regslice_both_out_r_V_strb_V_U_vld_out,
        ack_out => out_r_TREADY,
        apdone_blk => regslice_both_out_r_V_strb_V_U_apdone_blk);

    regslice_both_out_r_V_last_V_U : component fsk_lpf_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => din_last_reg_898_pp0_iter6_reg,
        vld_in => out_r_TVALID_int_regslice,
        ack_in => regslice_both_out_r_V_last_V_U_ack_in_dummy,
        data_out => out_r_TLAST,
        vld_out => regslice_both_out_r_V_last_V_U_vld_out,
        ack_out => out_r_TREADY,
        apdone_blk => regslice_both_out_r_V_last_V_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter8_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter8 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                acc_reg_1050 <= acc_fu_693_p2;
                add_ln131_11_reg_1040 <= add_ln131_11_fu_652_p2;
                add_ln131_12_reg_1045 <= add_ln131_12_fu_672_p2;
                add_ln131_1_reg_1020_pp0_iter5_reg <= add_ln131_1_reg_1020;
                add_ln131_4_reg_1025 <= add_ln131_4_fu_644_p2;
                add_ln131_4_reg_1025_pp0_iter5_reg <= add_ln131_4_reg_1025;
                din_last_reg_898_pp0_iter2_reg <= din_last_reg_898_pp0_iter1_reg;
                din_last_reg_898_pp0_iter3_reg <= din_last_reg_898_pp0_iter2_reg;
                din_last_reg_898_pp0_iter4_reg <= din_last_reg_898_pp0_iter3_reg;
                din_last_reg_898_pp0_iter5_reg <= din_last_reg_898_pp0_iter4_reg;
                din_last_reg_898_pp0_iter6_reg <= din_last_reg_898_pp0_iter5_reg;
                icmp_ln139_reg_1055 <= icmp_ln139_fu_719_p2;
                icmp_ln142_reg_1061 <= icmp_ln142_fu_725_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then
                add_ln131_1_reg_1020 <= grp_fu_819_p4;
                add_ln131_6_reg_1030 <= grp_fu_851_p4;
                add_ln131_7_reg_1035 <= grp_fu_861_p4;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                din_data_reg_893 <= in_r_TDATA_int_regslice;
                din_last_reg_898 <= in_r_TLAST_int_regslice;
                din_last_reg_898_pp0_iter1_reg <= din_last_reg_898;
                fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_30_reg_903 <= fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_6;
                fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_32_reg_909 <= fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_4;
                fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_34_reg_914 <= fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_2;
                fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_36_reg_919 <= fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_0;
                fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_38_reg_924 <= fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_17;
                fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_40_reg_929 <= fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_15;
                fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_43_reg_934 <= fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_12;
                fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_44_reg_939 <= fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_11;
                fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_47_reg_944 <= fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_8;
                fsk_lpf_stream_axis_0_stream_axis_ap_int_16_0ul_0ul_0ul_0_delay_1_load_reg_949 <= fsk_lpf_stream_axis_0_stream_axis_ap_int_16_0ul_0ul_0ul_0_delay_1;
                fsk_lpf_stream_axis_0_stream_axis_ap_int_16_0ul_0ul_0ul_0_delay_3_load_reg_954 <= fsk_lpf_stream_axis_0_stream_axis_ap_int_16_0ul_0ul_0ul_0_delay_3;
                fsk_lpf_stream_axis_0_stream_axis_ap_int_16_0ul_0ul_0ul_0_delay_5_load_reg_959 <= fsk_lpf_stream_axis_0_stream_axis_ap_int_16_0ul_0ul_0ul_0_delay_5;
                fsk_lpf_stream_axis_0_stream_axis_ap_int_16_0ul_0ul_0ul_0_delay_7_load_reg_964 <= fsk_lpf_stream_axis_0_stream_axis_ap_int_16_0ul_0ul_0ul_0_delay_7;
                fsk_lpf_stream_axis_0_stream_axis_ap_int_16_0ul_0ul_0ul_0_delay_9_load_reg_969 <= fsk_lpf_stream_axis_0_stream_axis_ap_int_16_0ul_0ul_0ul_0_delay_9;
                tmp29_reg_974 <= tmp29_fu_600_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay <= fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_17;
                fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_0 <= fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay;
                fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_1 <= fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_0;
                fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_10 <= fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_9;
                fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_11 <= fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_10;
                fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_12 <= fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_11;
                fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_13 <= fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_12;
                fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_14 <= fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_13;
                fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_15 <= fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_14;
                fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_16 <= fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_15;
                fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_17 <= fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_16;
                fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_2 <= fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_1;
                fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_3 <= fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_2;
                fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_4 <= fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_3;
                fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_5 <= fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_4;
                fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_6 <= fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_5;
                fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_8 <= fsk_lpf_stream_axis_0_stream_axis_ap_int_16_0ul_0ul_0ul_0_delay;
                fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_9 <= fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_8;
                fsk_lpf_stream_axis_0_stream_axis_ap_int_16_0ul_0ul_0ul_0_delay <= fsk_lpf_stream_axis_0_stream_axis_ap_int_16_0ul_0ul_0ul_0_delay_1;
                fsk_lpf_stream_axis_0_stream_axis_ap_int_16_0ul_0ul_0ul_0_delay_1 <= fsk_lpf_stream_axis_0_stream_axis_ap_int_16_0ul_0ul_0ul_0_delay_2;
                fsk_lpf_stream_axis_0_stream_axis_ap_int_16_0ul_0ul_0ul_0_delay_2 <= fsk_lpf_stream_axis_0_stream_axis_ap_int_16_0ul_0ul_0ul_0_delay_3;
                fsk_lpf_stream_axis_0_stream_axis_ap_int_16_0ul_0ul_0ul_0_delay_3 <= fsk_lpf_stream_axis_0_stream_axis_ap_int_16_0ul_0ul_0ul_0_delay_4;
                fsk_lpf_stream_axis_0_stream_axis_ap_int_16_0ul_0ul_0ul_0_delay_4 <= fsk_lpf_stream_axis_0_stream_axis_ap_int_16_0ul_0ul_0ul_0_delay_5;
                fsk_lpf_stream_axis_0_stream_axis_ap_int_16_0ul_0ul_0ul_0_delay_5 <= fsk_lpf_stream_axis_0_stream_axis_ap_int_16_0ul_0ul_0ul_0_delay_6;
                fsk_lpf_stream_axis_0_stream_axis_ap_int_16_0ul_0ul_0ul_0_delay_6 <= fsk_lpf_stream_axis_0_stream_axis_ap_int_16_0ul_0ul_0ul_0_delay_7;
                fsk_lpf_stream_axis_0_stream_axis_ap_int_16_0ul_0ul_0ul_0_delay_7 <= fsk_lpf_stream_axis_0_stream_axis_ap_int_16_0ul_0ul_0ul_0_delay_8;
                fsk_lpf_stream_axis_0_stream_axis_ap_int_16_0ul_0ul_0ul_0_delay_8 <= fsk_lpf_stream_axis_0_stream_axis_ap_int_16_0ul_0ul_0ul_0_delay_9;
                fsk_lpf_stream_axis_0_stream_axis_ap_int_16_0ul_0ul_0ul_0_delay_9 <= in_r_TDATA_int_regslice;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then
                fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_7 <= fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_30_reg_903;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage0_subdone, ap_reset_idle_pp0)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    acc_fu_693_p2 <= std_logic_vector(signed(sext_ln131_38_fu_690_p1) + signed(add_ln131_5_fu_684_p2));
    add_ln131_11_fu_652_p2 <= std_logic_vector(signed(sext_ln131_36_fu_649_p1) + signed(grp_fu_871_p4));
    add_ln131_12_fu_672_p2 <= std_logic_vector(signed(sext_ln131_37_fu_669_p1) + signed(add_ln131_8_fu_663_p2));
    add_ln131_4_fu_644_p2 <= std_logic_vector(signed(sext_ln131_32_fu_641_p1) + signed(grp_fu_829_p4));
    add_ln131_5_fu_684_p2 <= std_logic_vector(signed(sext_ln131_33_fu_681_p1) + signed(sext_ln131_31_fu_678_p1));
    add_ln131_8_fu_663_p2 <= std_logic_vector(signed(sext_ln131_35_fu_660_p1) + signed(sext_ln131_34_fu_657_p1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8, regslice_both_out_r_V_data_V_U_apdone_blk, in_r_TVALID_int_regslice, out_r_TREADY_int_regslice)
    begin
                ap_block_pp0_stage0_01001 <= (((ap_enable_reg_pp0_iter8 = ap_const_logic_1) and ((regslice_both_out_r_V_data_V_U_apdone_blk = ap_const_logic_1) or (out_r_TREADY_int_regslice = ap_const_logic_0))) or ((ap_enable_reg_pp0_iter7 = ap_const_logic_1) and (out_r_TREADY_int_regslice = ap_const_logic_0)) or ((in_r_TVALID_int_regslice = ap_const_logic_0) and (ap_const_logic_1 = ap_const_logic_1)));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8, regslice_both_out_r_V_data_V_U_apdone_blk, in_r_TVALID_int_regslice, out_r_TREADY_int_regslice)
    begin
                ap_block_pp0_stage0_11001 <= (((ap_enable_reg_pp0_iter8 = ap_const_logic_1) and ((regslice_both_out_r_V_data_V_U_apdone_blk = ap_const_logic_1) or (out_r_TREADY_int_regslice = ap_const_logic_0))) or ((ap_enable_reg_pp0_iter7 = ap_const_logic_1) and (out_r_TREADY_int_regslice = ap_const_logic_0)) or ((in_r_TVALID_int_regslice = ap_const_logic_0) and (ap_const_logic_1 = ap_const_logic_1)));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8, regslice_both_out_r_V_data_V_U_apdone_blk, in_r_TVALID_int_regslice, out_r_TREADY_int_regslice)
    begin
                ap_block_pp0_stage0_subdone <= (((ap_enable_reg_pp0_iter8 = ap_const_logic_1) and ((regslice_both_out_r_V_data_V_U_apdone_blk = ap_const_logic_1) or (out_r_TREADY_int_regslice = ap_const_logic_0))) or ((ap_enable_reg_pp0_iter7 = ap_const_logic_1) and (out_r_TREADY_int_regslice = ap_const_logic_0)) or ((in_r_TVALID_int_regslice = ap_const_logic_0) and (ap_const_logic_1 = ap_const_logic_1)));
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(in_r_TVALID_int_regslice)
    begin
                ap_block_state1_pp0_stage0_iter0 <= (in_r_TVALID_int_regslice = ap_const_logic_0);
    end process;

        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter4 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage0_iter5 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state7_pp0_stage0_iter6 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state8_pp0_stage0_iter7_assign_proc : process(out_r_TREADY_int_regslice)
    begin
                ap_block_state8_pp0_stage0_iter7 <= (out_r_TREADY_int_regslice = ap_const_logic_0);
    end process;


    ap_block_state9_pp0_stage0_iter8_assign_proc : process(regslice_both_out_r_V_data_V_U_apdone_blk, out_r_TREADY_int_regslice)
    begin
                ap_block_state9_pp0_stage0_iter8 <= ((regslice_both_out_r_V_data_V_U_apdone_blk = ap_const_logic_1) or (out_r_TREADY_int_regslice = ap_const_logic_0));
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6)
    begin
        if (((ap_enable_reg_pp0_iter8 = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_const_logic_1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_reset_idle_pp0 <= ap_const_logic_0;

    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    dout_data_fu_731_p4 <= acc_reg_1050(31 downto 16);
    fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_48_fu_596_p0 <= fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_7;
        fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_48_fu_596_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_48_fu_596_p0),17));


    grp_fu_760_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_760_ce <= ap_const_logic_1;
        else 
            grp_fu_760_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_760_p2 <= ap_const_lv32_602F(15 - 1 downto 0);

    grp_fu_771_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_771_ce <= ap_const_logic_1;
        else 
            grp_fu_771_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_771_p2 <= ap_const_lv33_4FF4(15 - 1 downto 0);

    grp_fu_779_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_779_ce <= ap_const_logic_1;
        else 
            grp_fu_779_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_779_p2 <= ap_const_lv31_26FA(14 - 1 downto 0);

    grp_fu_787_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_787_ce <= ap_const_logic_1;
        else 
            grp_fu_787_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_787_p2 <= ap_const_lv28_77A(11 - 1 downto 0);

    grp_fu_795_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_795_ce <= ap_const_logic_1;
        else 
            grp_fu_795_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_795_p2 <= ap_const_lv29_1FFFFB9E(12 - 1 downto 0);

    grp_fu_803_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_803_ce <= ap_const_logic_1;
        else 
            grp_fu_803_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_803_p2 <= ap_const_lv29_1FFFFA98(12 - 1 downto 0);

    grp_fu_811_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_811_ce <= ap_const_logic_1;
        else 
            grp_fu_811_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_811_p2 <= ap_const_lv28_FFFFD56(11 - 1 downto 0);

    grp_fu_819_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_819_ce <= ap_const_logic_1;
        else 
            grp_fu_819_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_819_p2 <= ap_const_lv33_686C(15 - 1 downto 0);

    grp_fu_829_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_829_ce <= ap_const_logic_1;
        else 
            grp_fu_829_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_829_p2 <= ap_const_lv32_3B8A(14 - 1 downto 0);

    grp_fu_840_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_840_ce <= ap_const_logic_1;
        else 
            grp_fu_840_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_840_p2 <= ap_const_lv31_14C6(13 - 1 downto 0);

    grp_fu_851_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_851_ce <= ap_const_logic_1;
        else 
            grp_fu_851_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_851_p2 <= ap_const_lv24_FFFFDA(7 - 1 downto 0);

    grp_fu_861_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_861_ce <= ap_const_logic_1;
        else 
            grp_fu_861_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_861_p2 <= ap_const_lv29_1FFFFA2E(12 - 1 downto 0);

    grp_fu_871_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_871_ce <= ap_const_logic_1;
        else 
            grp_fu_871_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_871_p2 <= ap_const_lv29_1FFFFBE1(12 - 1 downto 0);

    grp_fu_882_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_882_ce <= ap_const_logic_1;
        else 
            grp_fu_882_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_882_p2 <= ap_const_lv27_7FFFE9D(10 - 1 downto 0);
    icmp_ln139_fu_719_p2 <= "1" when (signed(tmp_1_fu_709_p4) > signed(ap_const_lv3_0)) else "0";
    icmp_ln142_fu_725_p2 <= "1" when (signed(trunc_ln_fu_699_p4) < signed(ap_const_lv18_38000)) else "0";

    in_r_TDATA_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, in_r_TVALID_int_regslice)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            in_r_TDATA_blk_n <= in_r_TVALID_int_regslice;
        else 
            in_r_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    in_r_TREADY <= regslice_both_in_r_V_data_V_U_ack_in;

    in_r_TREADY_int_regslice_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            in_r_TREADY_int_regslice <= ap_const_logic_1;
        else 
            in_r_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    or_ln139_fu_747_p2 <= (icmp_ln142_reg_1061 or icmp_ln139_reg_1055);

    out_r_TDATA_blk_n_assign_proc : process(ap_block_pp0_stage0, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8, out_r_TREADY_int_regslice)
    begin
        if ((((ap_enable_reg_pp0_iter8 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0)) or ((ap_enable_reg_pp0_iter7 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0)))) then 
            out_r_TDATA_blk_n <= out_r_TREADY_int_regslice;
        else 
            out_r_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    out_r_TDATA_int_regslice <= 
        select_ln139_fu_740_p3 when (or_ln139_fu_747_p2(0) = '1') else 
        dout_data_fu_731_p4;
    out_r_TVALID <= regslice_both_out_r_V_data_V_U_vld_out;

    out_r_TVALID_int_regslice_assign_proc : process(ap_enable_reg_pp0_iter7, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter7 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            out_r_TVALID_int_regslice <= ap_const_logic_1;
        else 
            out_r_TVALID_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

        p_shl1_cast_fu_624_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_shl1_fu_617_p3),25));

    p_shl1_fu_617_p3 <= (tmp29_reg_974 & ap_const_lv2_0);
        p_shl_cast_fu_613_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_shl_fu_606_p3),25));

    p_shl_fu_606_p3 <= (tmp29_reg_974 & ap_const_lv7_0);
    select_ln139_fu_740_p3 <= 
        ap_const_lv16_7FFF when (icmp_ln139_reg_1055(0) = '1') else 
        ap_const_lv16_8000;
        sext_ln131_31_fu_678_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln131_1_reg_1020_pp0_iter5_reg),34));

        sext_ln131_32_fu_641_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(grp_fu_840_p4),33));

        sext_ln131_33_fu_681_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln131_4_reg_1025_pp0_iter5_reg),34));

        sext_ln131_34_fu_657_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln131_6_reg_1030),30));

        sext_ln131_35_fu_660_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln131_7_reg_1035),30));

        sext_ln131_36_fu_649_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(grp_fu_882_p4),29));

        sext_ln131_37_fu_669_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln131_11_reg_1040),30));

        sext_ln131_38_fu_690_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln131_12_reg_1045),34));

        sext_ln131_fu_551_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(din_data_reg_893),17));

    tmp29_fu_600_p2 <= std_logic_vector(signed(fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_48_fu_596_p1) + signed(sext_ln131_fu_551_p1));
    tmp30_fu_628_p2 <= std_logic_vector(signed(p_shl1_cast_fu_624_p1) - signed(p_shl_cast_fu_613_p1));
    tmp_1_fu_709_p4 <= acc_fu_693_p2(33 downto 31);
    trunc_ln_fu_699_p4 <= acc_fu_693_p2(33 downto 16);
end behav;
