-- ==============================================================
-- Generated by Vitis HLS v2023.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity fsk_decimator is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    rx_in_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    rx_in_TVALID : IN STD_LOGIC;
    rx_in_TREADY : OUT STD_LOGIC;
    rx_in_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
    rx_in_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
    rx_in_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    dec_out_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    dec_out_TVALID : OUT STD_LOGIC;
    dec_out_TREADY : IN STD_LOGIC;
    dec_out_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
    dec_out_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    dec_out_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0) );
end;


architecture behav of fsk_decimator is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "fsk_decimator_fsk_decimator,hls_ip_2023_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=pipeline,HLS_SYN_CLOCK=4.140000,HLS_SYN_LAT=2,HLS_SYN_TPT=1,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=110,HLS_SYN_LUT=242,HLS_VERSION=2023_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv4_F : STD_LOGIC_VECTOR (3 downto 0) := "1111";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv8_FF : STD_LOGIC_VECTOR (7 downto 0) := "11111111";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";

    signal ap_rst_n_inv : STD_LOGIC;
    signal acc_i : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal acc_q : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal dec_counter : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal rx_in_TDATA_blk_n : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal dec_out_TDATA_blk_n : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal icmp_ln40_reg_289 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal icmp_ln40_reg_289_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal pkt_rx_last_V_reg_284 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state2_io : BOOLEAN;
    signal regslice_both_dec_out_V_data_V_U_apdone_blk : STD_LOGIC;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state3_io : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln40_fu_226_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln2_reg_293 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln3_reg_298 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_phi_mux_acc_i_new_0_phi_fu_115_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter0_acc_i_new_0_reg_112 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln35_fu_180_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_mux_acc_q_new_0_phi_fu_125_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter0_acc_q_new_0_reg_122 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln36_fu_209_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_mux_storemerge_phi_fu_135_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_storemerge_reg_132 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln64_fu_232_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal rx_i_fu_150_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln35_fu_164_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln35_fu_176_p1 : STD_LOGIC_VECTOR (23 downto 0);
    signal sext_ln35_1_fu_172_p1 : STD_LOGIC_VECTOR (23 downto 0);
    signal rx_q_fu_154_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln36_fu_193_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln36_fu_205_p1 : STD_LOGIC_VECTOR (23 downto 0);
    signal sext_ln36_1_fu_201_p1 : STD_LOGIC_VECTOR (23 downto 0);
    signal add_ln36_1_fu_187_p2 : STD_LOGIC_VECTOR (23 downto 0);
    signal add_ln40_fu_216_p2 : STD_LOGIC_VECTOR (23 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reset_idle_pp0 : STD_LOGIC;
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal regslice_both_rx_in_V_data_V_U_apdone_blk : STD_LOGIC;
    signal rx_in_TDATA_int_regslice : STD_LOGIC_VECTOR (31 downto 0);
    signal rx_in_TVALID_int_regslice : STD_LOGIC;
    signal rx_in_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_rx_in_V_data_V_U_ack_in : STD_LOGIC;
    signal regslice_both_rx_in_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal rx_in_TKEEP_int_regslice : STD_LOGIC_VECTOR (3 downto 0);
    signal regslice_both_rx_in_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_rx_in_V_keep_V_U_ack_in : STD_LOGIC;
    signal regslice_both_rx_in_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal rx_in_TSTRB_int_regslice : STD_LOGIC_VECTOR (3 downto 0);
    signal regslice_both_rx_in_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_rx_in_V_strb_V_U_ack_in : STD_LOGIC;
    signal regslice_both_rx_in_V_last_V_U_apdone_blk : STD_LOGIC;
    signal rx_in_TLAST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_rx_in_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_rx_in_V_last_V_U_ack_in : STD_LOGIC;
    signal dec_out_TDATA_int_regslice : STD_LOGIC_VECTOR (31 downto 0);
    signal dec_out_TVALID_int_regslice : STD_LOGIC;
    signal dec_out_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_dec_out_V_data_V_U_vld_out : STD_LOGIC;
    signal regslice_both_dec_out_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_dec_out_V_keep_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_dec_out_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_dec_out_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_dec_out_V_strb_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_dec_out_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_dec_out_V_last_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_dec_out_V_last_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_dec_out_V_last_V_U_vld_out : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component fsk_decimator_regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    regslice_both_rx_in_V_data_V_U : component fsk_decimator_regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => rx_in_TDATA,
        vld_in => rx_in_TVALID,
        ack_in => regslice_both_rx_in_V_data_V_U_ack_in,
        data_out => rx_in_TDATA_int_regslice,
        vld_out => rx_in_TVALID_int_regslice,
        ack_out => rx_in_TREADY_int_regslice,
        apdone_blk => regslice_both_rx_in_V_data_V_U_apdone_blk);

    regslice_both_rx_in_V_keep_V_U : component fsk_decimator_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => rx_in_TKEEP,
        vld_in => rx_in_TVALID,
        ack_in => regslice_both_rx_in_V_keep_V_U_ack_in,
        data_out => rx_in_TKEEP_int_regslice,
        vld_out => regslice_both_rx_in_V_keep_V_U_vld_out,
        ack_out => rx_in_TREADY_int_regslice,
        apdone_blk => regslice_both_rx_in_V_keep_V_U_apdone_blk);

    regslice_both_rx_in_V_strb_V_U : component fsk_decimator_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => rx_in_TSTRB,
        vld_in => rx_in_TVALID,
        ack_in => regslice_both_rx_in_V_strb_V_U_ack_in,
        data_out => rx_in_TSTRB_int_regslice,
        vld_out => regslice_both_rx_in_V_strb_V_U_vld_out,
        ack_out => rx_in_TREADY_int_regslice,
        apdone_blk => regslice_both_rx_in_V_strb_V_U_apdone_blk);

    regslice_both_rx_in_V_last_V_U : component fsk_decimator_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => rx_in_TLAST,
        vld_in => rx_in_TVALID,
        ack_in => regslice_both_rx_in_V_last_V_U_ack_in,
        data_out => rx_in_TLAST_int_regslice,
        vld_out => regslice_both_rx_in_V_last_V_U_vld_out,
        ack_out => rx_in_TREADY_int_regslice,
        apdone_blk => regslice_both_rx_in_V_last_V_U_apdone_blk);

    regslice_both_dec_out_V_data_V_U : component fsk_decimator_regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => dec_out_TDATA_int_regslice,
        vld_in => dec_out_TVALID_int_regslice,
        ack_in => dec_out_TREADY_int_regslice,
        data_out => dec_out_TDATA,
        vld_out => regslice_both_dec_out_V_data_V_U_vld_out,
        ack_out => dec_out_TREADY,
        apdone_blk => regslice_both_dec_out_V_data_V_U_apdone_blk);

    regslice_both_dec_out_V_keep_V_U : component fsk_decimator_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => ap_const_lv4_F,
        vld_in => dec_out_TVALID_int_regslice,
        ack_in => regslice_both_dec_out_V_keep_V_U_ack_in_dummy,
        data_out => dec_out_TKEEP,
        vld_out => regslice_both_dec_out_V_keep_V_U_vld_out,
        ack_out => dec_out_TREADY,
        apdone_blk => regslice_both_dec_out_V_keep_V_U_apdone_blk);

    regslice_both_dec_out_V_strb_V_U : component fsk_decimator_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => ap_const_lv4_0,
        vld_in => dec_out_TVALID_int_regslice,
        ack_in => regslice_both_dec_out_V_strb_V_U_ack_in_dummy,
        data_out => dec_out_TSTRB,
        vld_out => regslice_both_dec_out_V_strb_V_U_vld_out,
        ack_out => dec_out_TREADY,
        apdone_blk => regslice_both_dec_out_V_strb_V_U_apdone_blk);

    regslice_both_dec_out_V_last_V_U : component fsk_decimator_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => pkt_rx_last_V_reg_284,
        vld_in => dec_out_TVALID_int_regslice,
        ack_in => regslice_both_dec_out_V_last_V_U_ack_in_dummy,
        data_out => dec_out_TLAST,
        vld_out => regslice_both_dec_out_V_last_V_U_vld_out,
        ack_out => dec_out_TREADY,
        apdone_blk => regslice_both_dec_out_V_last_V_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                acc_i <= ap_phi_mux_acc_i_new_0_phi_fu_115_p4;
                acc_q <= ap_phi_mux_acc_q_new_0_phi_fu_125_p4;
                dec_counter <= ap_phi_mux_storemerge_phi_fu_135_p4;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                icmp_ln40_reg_289 <= icmp_ln40_fu_226_p2;
                icmp_ln40_reg_289_pp0_iter1_reg <= icmp_ln40_reg_289;
                pkt_rx_last_V_reg_284 <= rx_in_TLAST_int_regslice;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln40_fu_226_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                trunc_ln2_reg_293 <= add_ln36_1_fu_187_p2(23 downto 8);
                trunc_ln3_reg_298 <= add_ln40_fu_216_p2(23 downto 8);
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage0_subdone, ap_reset_idle_pp0)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln35_fu_180_p2 <= std_logic_vector(unsigned(acc_i) + unsigned(sext_ln35_fu_164_p1));
    add_ln36_1_fu_187_p2 <= std_logic_vector(unsigned(trunc_ln35_fu_176_p1) + unsigned(sext_ln35_1_fu_172_p1));
    add_ln36_fu_209_p2 <= std_logic_vector(unsigned(acc_q) + unsigned(sext_ln36_fu_193_p1));
    add_ln40_fu_216_p2 <= std_logic_vector(unsigned(trunc_ln36_fu_205_p1) + unsigned(sext_ln36_1_fu_201_p1));
    add_ln64_fu_232_p2 <= std_logic_vector(unsigned(dec_counter) + unsigned(ap_const_lv8_1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_enable_reg_pp0_iter1, icmp_ln40_reg_289, ap_enable_reg_pp0_iter2, icmp_ln40_reg_289_pp0_iter1_reg, regslice_both_dec_out_V_data_V_U_apdone_blk, rx_in_TVALID_int_regslice, dec_out_TREADY_int_regslice)
    begin
                ap_block_pp0_stage0_01001 <= (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and ((regslice_both_dec_out_V_data_V_U_apdone_blk = ap_const_logic_1) or ((icmp_ln40_reg_289_pp0_iter1_reg = ap_const_lv1_1) and (dec_out_TREADY_int_regslice = ap_const_logic_0)))) or ((icmp_ln40_reg_289 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (dec_out_TREADY_int_regslice = ap_const_logic_0)) or ((ap_const_logic_1 = ap_const_logic_1) and (rx_in_TVALID_int_regslice = ap_const_logic_0)));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter1, icmp_ln40_reg_289, ap_enable_reg_pp0_iter2, icmp_ln40_reg_289_pp0_iter1_reg, ap_block_state2_io, regslice_both_dec_out_V_data_V_U_apdone_blk, ap_block_state3_io, rx_in_TVALID_int_regslice, dec_out_TREADY_int_regslice)
    begin
                ap_block_pp0_stage0_11001 <= (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and ((regslice_both_dec_out_V_data_V_U_apdone_blk = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state3_io) or ((icmp_ln40_reg_289_pp0_iter1_reg = ap_const_lv1_1) and (dec_out_TREADY_int_regslice = ap_const_logic_0)))) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and ((ap_const_boolean_1 = ap_block_state2_io) or ((icmp_ln40_reg_289 = ap_const_lv1_1) and (dec_out_TREADY_int_regslice = ap_const_logic_0)))) or ((ap_const_logic_1 = ap_const_logic_1) and (rx_in_TVALID_int_regslice = ap_const_logic_0)));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, icmp_ln40_reg_289, ap_enable_reg_pp0_iter2, icmp_ln40_reg_289_pp0_iter1_reg, ap_block_state2_io, regslice_both_dec_out_V_data_V_U_apdone_blk, ap_block_state3_io, rx_in_TVALID_int_regslice, dec_out_TREADY_int_regslice)
    begin
                ap_block_pp0_stage0_subdone <= (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and ((regslice_both_dec_out_V_data_V_U_apdone_blk = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state3_io) or ((icmp_ln40_reg_289_pp0_iter1_reg = ap_const_lv1_1) and (dec_out_TREADY_int_regslice = ap_const_logic_0)))) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and ((ap_const_boolean_1 = ap_block_state2_io) or ((icmp_ln40_reg_289 = ap_const_lv1_1) and (dec_out_TREADY_int_regslice = ap_const_logic_0)))) or ((ap_const_logic_1 = ap_const_logic_1) and (rx_in_TVALID_int_regslice = ap_const_logic_0)));
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(rx_in_TVALID_int_regslice)
    begin
                ap_block_state1_pp0_stage0_iter0 <= (rx_in_TVALID_int_regslice = ap_const_logic_0);
    end process;


    ap_block_state2_io_assign_proc : process(icmp_ln40_reg_289, dec_out_TREADY_int_regslice)
    begin
                ap_block_state2_io <= ((icmp_ln40_reg_289 = ap_const_lv1_1) and (dec_out_TREADY_int_regslice = ap_const_logic_0));
    end process;


    ap_block_state2_pp0_stage0_iter1_assign_proc : process(icmp_ln40_reg_289, dec_out_TREADY_int_regslice)
    begin
                ap_block_state2_pp0_stage0_iter1 <= ((icmp_ln40_reg_289 = ap_const_lv1_1) and (dec_out_TREADY_int_regslice = ap_const_logic_0));
    end process;


    ap_block_state3_io_assign_proc : process(icmp_ln40_reg_289_pp0_iter1_reg, dec_out_TREADY_int_regslice)
    begin
                ap_block_state3_io <= ((icmp_ln40_reg_289_pp0_iter1_reg = ap_const_lv1_1) and (dec_out_TREADY_int_regslice = ap_const_logic_0));
    end process;


    ap_block_state3_pp0_stage0_iter2_assign_proc : process(icmp_ln40_reg_289_pp0_iter1_reg, regslice_both_dec_out_V_data_V_U_apdone_blk, dec_out_TREADY_int_regslice)
    begin
                ap_block_state3_pp0_stage0_iter2 <= ((regslice_both_dec_out_V_data_V_U_apdone_blk = ap_const_logic_1) or ((icmp_ln40_reg_289_pp0_iter1_reg = ap_const_lv1_1) and (dec_out_TREADY_int_regslice = ap_const_logic_0)));
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_const_logic_1 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_acc_i_new_0_phi_fu_115_p4_assign_proc : process(icmp_ln40_fu_226_p2, ap_phi_reg_pp0_iter0_acc_i_new_0_reg_112, add_ln35_fu_180_p2)
    begin
        if ((icmp_ln40_fu_226_p2 = ap_const_lv1_0)) then 
            ap_phi_mux_acc_i_new_0_phi_fu_115_p4 <= add_ln35_fu_180_p2;
        elsif ((icmp_ln40_fu_226_p2 = ap_const_lv1_1)) then 
            ap_phi_mux_acc_i_new_0_phi_fu_115_p4 <= ap_const_lv32_0;
        else 
            ap_phi_mux_acc_i_new_0_phi_fu_115_p4 <= ap_phi_reg_pp0_iter0_acc_i_new_0_reg_112;
        end if; 
    end process;


    ap_phi_mux_acc_q_new_0_phi_fu_125_p4_assign_proc : process(icmp_ln40_fu_226_p2, ap_phi_reg_pp0_iter0_acc_q_new_0_reg_122, add_ln36_fu_209_p2)
    begin
        if ((icmp_ln40_fu_226_p2 = ap_const_lv1_0)) then 
            ap_phi_mux_acc_q_new_0_phi_fu_125_p4 <= add_ln36_fu_209_p2;
        elsif ((icmp_ln40_fu_226_p2 = ap_const_lv1_1)) then 
            ap_phi_mux_acc_q_new_0_phi_fu_125_p4 <= ap_const_lv32_0;
        else 
            ap_phi_mux_acc_q_new_0_phi_fu_125_p4 <= ap_phi_reg_pp0_iter0_acc_q_new_0_reg_122;
        end if; 
    end process;


    ap_phi_mux_storemerge_phi_fu_135_p4_assign_proc : process(icmp_ln40_fu_226_p2, ap_phi_reg_pp0_iter0_storemerge_reg_132, add_ln64_fu_232_p2)
    begin
        if ((icmp_ln40_fu_226_p2 = ap_const_lv1_0)) then 
            ap_phi_mux_storemerge_phi_fu_135_p4 <= add_ln64_fu_232_p2;
        elsif ((icmp_ln40_fu_226_p2 = ap_const_lv1_1)) then 
            ap_phi_mux_storemerge_phi_fu_135_p4 <= ap_const_lv8_0;
        else 
            ap_phi_mux_storemerge_phi_fu_135_p4 <= ap_phi_reg_pp0_iter0_storemerge_reg_132;
        end if; 
    end process;

    ap_phi_reg_pp0_iter0_acc_i_new_0_reg_112 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter0_acc_q_new_0_reg_122 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter0_storemerge_reg_132 <= "XXXXXXXX";
    ap_reset_idle_pp0 <= ap_const_logic_0;

    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;


    dec_out_TDATA_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln40_reg_289, ap_enable_reg_pp0_iter2, icmp_ln40_reg_289_pp0_iter1_reg, dec_out_TREADY_int_regslice)
    begin
        if ((((icmp_ln40_reg_289_pp0_iter1_reg = ap_const_lv1_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0)) or ((icmp_ln40_reg_289 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            dec_out_TDATA_blk_n <= dec_out_TREADY_int_regslice;
        else 
            dec_out_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    dec_out_TDATA_int_regslice <= (trunc_ln3_reg_298 & trunc_ln2_reg_293);
    dec_out_TVALID <= regslice_both_dec_out_V_data_V_U_vld_out;

    dec_out_TVALID_int_regslice_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln40_reg_289, ap_block_pp0_stage0_11001)
    begin
        if (((icmp_ln40_reg_289 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            dec_out_TVALID_int_regslice <= ap_const_logic_1;
        else 
            dec_out_TVALID_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln40_fu_226_p2 <= "1" when (dec_counter = ap_const_lv8_FF) else "0";
    rx_i_fu_150_p1 <= rx_in_TDATA_int_regslice(16 - 1 downto 0);

    rx_in_TDATA_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, rx_in_TVALID_int_regslice)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            rx_in_TDATA_blk_n <= rx_in_TVALID_int_regslice;
        else 
            rx_in_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    rx_in_TREADY <= regslice_both_rx_in_V_data_V_U_ack_in;

    rx_in_TREADY_int_regslice_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            rx_in_TREADY_int_regslice <= ap_const_logic_1;
        else 
            rx_in_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    rx_q_fu_154_p4 <= rx_in_TDATA_int_regslice(31 downto 16);
        sext_ln35_1_fu_172_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(rx_i_fu_150_p1),24));

        sext_ln35_fu_164_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(rx_i_fu_150_p1),32));

        sext_ln36_1_fu_201_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(rx_q_fu_154_p4),24));

        sext_ln36_fu_193_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(rx_q_fu_154_p4),32));

    trunc_ln35_fu_176_p1 <= acc_i(24 - 1 downto 0);
    trunc_ln36_fu_205_p1 <= acc_q(24 - 1 downto 0);
end behav;
