// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="fsk_lpf_fsk_lpf,hls_ip_2023_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=pipeline,HLS_SYN_CLOCK=6.565875,HLS_SYN_LAT=8,HLS_SYN_TPT=1,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=1079,HLS_SYN_LUT=387,HLS_VERSION=2023_1}" *)

module fsk_lpf (
        ap_clk,
        ap_rst_n,
        in_r_TDATA,
        in_r_TVALID,
        in_r_TREADY,
        in_r_TKEEP,
        in_r_TSTRB,
        in_r_TLAST,
        out_r_TDATA,
        out_r_TVALID,
        out_r_TREADY,
        out_r_TKEEP,
        out_r_TSTRB,
        out_r_TLAST
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst_n;
input  [15:0] in_r_TDATA;
input   in_r_TVALID;
output   in_r_TREADY;
input  [1:0] in_r_TKEEP;
input  [1:0] in_r_TSTRB;
input  [0:0] in_r_TLAST;
output  [15:0] out_r_TDATA;
output   out_r_TVALID;
input   out_r_TREADY;
output  [1:0] out_r_TKEEP;
output  [1:0] out_r_TSTRB;
output  [0:0] out_r_TLAST;

 reg    ap_rst_n_inv;
reg   [15:0] fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_7;
reg   [15:0] fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_6;
reg  signed [15:0] fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_5;
reg   [15:0] fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_4;
reg  signed [15:0] fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_3;
reg   [15:0] fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_2;
reg  signed [15:0] fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_1;
reg   [15:0] fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_0;
reg  signed [15:0] fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay;
reg   [15:0] fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_17;
reg  signed [15:0] fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_16;
reg   [15:0] fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_15;
reg  signed [15:0] fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_14;
reg  signed [15:0] fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_13;
reg   [15:0] fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_12;
reg   [15:0] fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_11;
reg  signed [15:0] fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_10;
reg  signed [15:0] fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_9;
reg   [15:0] fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_8;
reg  signed [15:0] fsk_lpf_stream_axis_0_stream_axis_ap_int_16_0ul_0ul_0ul_0_delay;
reg   [15:0] fsk_lpf_stream_axis_0_stream_axis_ap_int_16_0ul_0ul_0ul_0_delay_1;
reg  signed [15:0] fsk_lpf_stream_axis_0_stream_axis_ap_int_16_0ul_0ul_0ul_0_delay_2;
reg   [15:0] fsk_lpf_stream_axis_0_stream_axis_ap_int_16_0ul_0ul_0ul_0_delay_3;
reg  signed [15:0] fsk_lpf_stream_axis_0_stream_axis_ap_int_16_0ul_0ul_0ul_0_delay_4;
reg   [15:0] fsk_lpf_stream_axis_0_stream_axis_ap_int_16_0ul_0ul_0ul_0_delay_5;
reg  signed [15:0] fsk_lpf_stream_axis_0_stream_axis_ap_int_16_0ul_0ul_0ul_0_delay_6;
reg   [15:0] fsk_lpf_stream_axis_0_stream_axis_ap_int_16_0ul_0ul_0ul_0_delay_7;
reg  signed [15:0] fsk_lpf_stream_axis_0_stream_axis_ap_int_16_0ul_0ul_0ul_0_delay_8;
reg   [15:0] fsk_lpf_stream_axis_0_stream_axis_ap_int_16_0ul_0ul_0ul_0_delay_9;
reg    in_r_TDATA_blk_n;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_block_pp0_stage0;
reg    out_r_TDATA_blk_n;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg  signed [15:0] din_data_reg_893;
reg    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
wire    ap_block_state7_pp0_stage0_iter6;
reg    ap_block_state8_pp0_stage0_iter7;
wire    regslice_both_out_r_V_data_V_U_apdone_blk;
reg    ap_block_state9_pp0_stage0_iter8;
reg    ap_block_pp0_stage0_11001;
reg   [0:0] din_last_reg_898;
reg   [0:0] din_last_reg_898_pp0_iter1_reg;
reg   [0:0] din_last_reg_898_pp0_iter2_reg;
reg   [0:0] din_last_reg_898_pp0_iter3_reg;
reg   [0:0] din_last_reg_898_pp0_iter4_reg;
reg   [0:0] din_last_reg_898_pp0_iter5_reg;
reg   [0:0] din_last_reg_898_pp0_iter6_reg;
reg  signed [15:0] fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_30_reg_903;
reg  signed [15:0] fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_32_reg_909;
reg  signed [15:0] fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_34_reg_914;
reg  signed [15:0] fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_36_reg_919;
reg  signed [15:0] fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_38_reg_924;
reg  signed [15:0] fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_40_reg_929;
reg  signed [15:0] fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_43_reg_934;
reg  signed [15:0] fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_44_reg_939;
reg  signed [15:0] fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_47_reg_944;
reg  signed [15:0] fsk_lpf_stream_axis_0_stream_axis_ap_int_16_0ul_0ul_0ul_0_delay_1_load_reg_949;
reg  signed [15:0] fsk_lpf_stream_axis_0_stream_axis_ap_int_16_0ul_0ul_0ul_0_delay_3_load_reg_954;
reg  signed [15:0] fsk_lpf_stream_axis_0_stream_axis_ap_int_16_0ul_0ul_0ul_0_delay_5_load_reg_959;
reg  signed [15:0] fsk_lpf_stream_axis_0_stream_axis_ap_int_16_0ul_0ul_0ul_0_delay_7_load_reg_964;
reg  signed [15:0] fsk_lpf_stream_axis_0_stream_axis_ap_int_16_0ul_0ul_0ul_0_delay_9_load_reg_969;
wire   [16:0] tmp29_fu_600_p2;
reg   [16:0] tmp29_reg_974;
wire  signed [32:0] grp_fu_771_p3;
reg    ap_enable_reg_pp0_iter3;
wire  signed [30:0] grp_fu_779_p3;
wire  signed [27:0] grp_fu_787_p3;
wire  signed [28:0] grp_fu_795_p3;
wire  signed [28:0] grp_fu_803_p3;
wire  signed [27:0] grp_fu_811_p3;
wire  signed [32:0] grp_fu_819_p4;
reg  signed [32:0] add_ln131_1_reg_1020;
reg    ap_enable_reg_pp0_iter4;
reg  signed [32:0] add_ln131_1_reg_1020_pp0_iter5_reg;
(* use_dsp48 = "no" *) wire   [32:0] add_ln131_4_fu_644_p2;
reg   [32:0] add_ln131_4_reg_1025;
reg   [32:0] add_ln131_4_reg_1025_pp0_iter5_reg;
wire  signed [27:0] grp_fu_851_p4;
reg  signed [27:0] add_ln131_6_reg_1030;
wire  signed [28:0] grp_fu_861_p4;
reg  signed [28:0] add_ln131_7_reg_1035;
(* use_dsp48 = "no" *) wire   [28:0] add_ln131_11_fu_652_p2;
reg   [28:0] add_ln131_11_reg_1040;
wire   [29:0] add_ln131_12_fu_672_p2;
reg   [29:0] add_ln131_12_reg_1045;
wire   [33:0] acc_fu_693_p2;
reg   [33:0] acc_reg_1050;
wire   [0:0] icmp_ln139_fu_719_p2;
reg   [0:0] icmp_ln139_reg_1055;
wire   [0:0] icmp_ln142_fu_725_p2;
reg   [0:0] icmp_ln142_reg_1061;
reg    ap_enable_reg_pp0_iter1;
reg    ap_block_pp0_stage0_subdone;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_block_pp0_stage0_01001;
wire  signed [15:0] fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_48_fu_596_p0;
wire  signed [16:0] fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_48_fu_596_p1;
wire  signed [16:0] sext_ln131_fu_551_p1;
wire   [23:0] p_shl_fu_606_p3;
wire   [18:0] p_shl1_fu_617_p3;
wire  signed [24:0] p_shl1_cast_fu_624_p1;
wire  signed [24:0] p_shl_cast_fu_613_p1;
wire  signed [24:0] tmp30_fu_628_p2;
wire  signed [31:0] grp_fu_760_p4;
wire  signed [30:0] grp_fu_840_p4;
wire  signed [32:0] sext_ln131_32_fu_641_p1;
wire  signed [32:0] grp_fu_829_p4;
wire  signed [27:0] grp_fu_882_p4;
wire  signed [28:0] sext_ln131_36_fu_649_p1;
wire  signed [28:0] grp_fu_871_p4;
wire  signed [29:0] sext_ln131_35_fu_660_p1;
wire  signed [29:0] sext_ln131_34_fu_657_p1;
wire  signed [29:0] sext_ln131_37_fu_669_p1;
wire   [29:0] add_ln131_8_fu_663_p2;
wire  signed [33:0] sext_ln131_33_fu_681_p1;
wire  signed [33:0] sext_ln131_31_fu_678_p1;
wire  signed [33:0] sext_ln131_38_fu_690_p1;
wire   [33:0] add_ln131_5_fu_684_p2;
wire   [2:0] tmp_1_fu_709_p4;
wire   [17:0] trunc_ln_fu_699_p4;
wire   [0:0] or_ln139_fu_747_p2;
wire   [15:0] select_ln139_fu_740_p3;
wire   [15:0] dout_data_fu_731_p4;
wire   [14:0] grp_fu_760_p2;
wire   [14:0] grp_fu_771_p2;
wire   [13:0] grp_fu_779_p2;
wire   [10:0] grp_fu_787_p2;
wire  signed [11:0] grp_fu_795_p2;
wire  signed [11:0] grp_fu_803_p2;
wire  signed [10:0] grp_fu_811_p2;
wire   [14:0] grp_fu_819_p2;
wire   [13:0] grp_fu_829_p2;
wire   [12:0] grp_fu_840_p2;
wire  signed [6:0] grp_fu_851_p2;
wire  signed [11:0] grp_fu_861_p2;
wire  signed [11:0] grp_fu_871_p2;
wire  signed [9:0] grp_fu_882_p2;
reg    grp_fu_760_ce;
reg    grp_fu_771_ce;
reg    grp_fu_779_ce;
reg    grp_fu_787_ce;
reg    grp_fu_795_ce;
reg    grp_fu_803_ce;
reg    grp_fu_811_ce;
reg    grp_fu_819_ce;
reg    grp_fu_829_ce;
reg    grp_fu_840_ce;
reg    grp_fu_851_ce;
reg    grp_fu_861_ce;
reg    grp_fu_871_ce;
reg    grp_fu_882_ce;
reg   [0:0] ap_NS_fsm;
wire    ap_reset_idle_pp0;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
wire    regslice_both_in_r_V_data_V_U_apdone_blk;
wire   [15:0] in_r_TDATA_int_regslice;
wire    in_r_TVALID_int_regslice;
reg    in_r_TREADY_int_regslice;
wire    regslice_both_in_r_V_data_V_U_ack_in;
wire    regslice_both_in_r_V_keep_V_U_apdone_blk;
wire   [1:0] in_r_TKEEP_int_regslice;
wire    regslice_both_in_r_V_keep_V_U_vld_out;
wire    regslice_both_in_r_V_keep_V_U_ack_in;
wire    regslice_both_in_r_V_strb_V_U_apdone_blk;
wire   [1:0] in_r_TSTRB_int_regslice;
wire    regslice_both_in_r_V_strb_V_U_vld_out;
wire    regslice_both_in_r_V_strb_V_U_ack_in;
wire    regslice_both_in_r_V_last_V_U_apdone_blk;
wire   [0:0] in_r_TLAST_int_regslice;
wire    regslice_both_in_r_V_last_V_U_vld_out;
wire    regslice_both_in_r_V_last_V_U_ack_in;
wire   [15:0] out_r_TDATA_int_regslice;
reg    out_r_TVALID_int_regslice;
wire    out_r_TREADY_int_regslice;
wire    regslice_both_out_r_V_data_V_U_vld_out;
wire    regslice_both_out_r_V_keep_V_U_apdone_blk;
wire    regslice_both_out_r_V_keep_V_U_ack_in_dummy;
wire    regslice_both_out_r_V_keep_V_U_vld_out;
wire    regslice_both_out_r_V_strb_V_U_apdone_blk;
wire    regslice_both_out_r_V_strb_V_U_ack_in_dummy;
wire    regslice_both_out_r_V_strb_V_U_vld_out;
wire    regslice_both_out_r_V_last_V_U_apdone_blk;
wire    regslice_both_out_r_V_last_V_U_ack_in_dummy;
wire    regslice_both_out_r_V_last_V_U_vld_out;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_7 = 16'd0;
#0 fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_6 = 16'd0;
#0 fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_5 = 16'd0;
#0 fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_4 = 16'd0;
#0 fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_3 = 16'd0;
#0 fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_2 = 16'd0;
#0 fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_1 = 16'd0;
#0 fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_0 = 16'd0;
#0 fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay = 16'd0;
#0 fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_17 = 16'd0;
#0 fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_16 = 16'd0;
#0 fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_15 = 16'd0;
#0 fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_14 = 16'd0;
#0 fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_13 = 16'd0;
#0 fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_12 = 16'd0;
#0 fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_11 = 16'd0;
#0 fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_10 = 16'd0;
#0 fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_9 = 16'd0;
#0 fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_8 = 16'd0;
#0 fsk_lpf_stream_axis_0_stream_axis_ap_int_16_0ul_0ul_0ul_0_delay = 16'd0;
#0 fsk_lpf_stream_axis_0_stream_axis_ap_int_16_0ul_0ul_0ul_0_delay_1 = 16'd0;
#0 fsk_lpf_stream_axis_0_stream_axis_ap_int_16_0ul_0ul_0ul_0_delay_2 = 16'd0;
#0 fsk_lpf_stream_axis_0_stream_axis_ap_int_16_0ul_0ul_0ul_0_delay_3 = 16'd0;
#0 fsk_lpf_stream_axis_0_stream_axis_ap_int_16_0ul_0ul_0ul_0_delay_4 = 16'd0;
#0 fsk_lpf_stream_axis_0_stream_axis_ap_int_16_0ul_0ul_0ul_0_delay_5 = 16'd0;
#0 fsk_lpf_stream_axis_0_stream_axis_ap_int_16_0ul_0ul_0ul_0_delay_6 = 16'd0;
#0 fsk_lpf_stream_axis_0_stream_axis_ap_int_16_0ul_0ul_0ul_0_delay_7 = 16'd0;
#0 fsk_lpf_stream_axis_0_stream_axis_ap_int_16_0ul_0ul_0ul_0_delay_8 = 16'd0;
#0 fsk_lpf_stream_axis_0_stream_axis_ap_int_16_0ul_0ul_0ul_0_delay_9 = 16'd0;
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
end

fsk_lpf_ama_addmuladd_16s_16s_15ns_25s_32_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 15 ),
    .din3_WIDTH( 25 ),
    .dout_WIDTH( 32 ))
ama_addmuladd_16s_16s_15ns_25s_32_4_1_U1(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_10),
    .din1(fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_13),
    .din2(grp_fu_760_p2),
    .din3(tmp30_fu_628_p2),
    .ce(grp_fu_760_ce),
    .dout(grp_fu_760_p4)
);

fsk_lpf_am_addmul_16s_16s_15ns_33_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 15 ),
    .dout_WIDTH( 33 ))
am_addmul_16s_16s_15ns_33_4_1_U2(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_9),
    .din1(fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_14),
    .din2(grp_fu_771_p2),
    .ce(grp_fu_771_ce),
    .dout(grp_fu_771_p3)
);

fsk_lpf_am_addmul_16s_16s_14ns_31_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 14 ),
    .dout_WIDTH( 31 ))
am_addmul_16s_16s_14ns_31_4_1_U3(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(fsk_lpf_stream_axis_0_stream_axis_ap_int_16_0ul_0ul_0ul_0_delay),
    .din1(fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_16),
    .din2(grp_fu_779_p2),
    .ce(grp_fu_779_ce),
    .dout(grp_fu_779_p3)
);

fsk_lpf_am_addmul_16s_16s_11ns_28_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 11 ),
    .dout_WIDTH( 28 ))
am_addmul_16s_16s_11ns_28_4_1_U4(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(fsk_lpf_stream_axis_0_stream_axis_ap_int_16_0ul_0ul_0ul_0_delay_2),
    .din1(fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay),
    .din2(grp_fu_787_p2),
    .ce(grp_fu_787_ce),
    .dout(grp_fu_787_p3)
);

fsk_lpf_am_addmul_16s_16s_12s_29_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 12 ),
    .dout_WIDTH( 29 ))
am_addmul_16s_16s_12s_29_4_1_U5(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(fsk_lpf_stream_axis_0_stream_axis_ap_int_16_0ul_0ul_0ul_0_delay_4),
    .din1(fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_1),
    .din2(grp_fu_795_p2),
    .ce(grp_fu_795_ce),
    .dout(grp_fu_795_p3)
);

fsk_lpf_am_addmul_16s_16s_12s_29_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 12 ),
    .dout_WIDTH( 29 ))
am_addmul_16s_16s_12s_29_4_1_U6(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(fsk_lpf_stream_axis_0_stream_axis_ap_int_16_0ul_0ul_0ul_0_delay_6),
    .din1(fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_3),
    .din2(grp_fu_803_p2),
    .ce(grp_fu_803_ce),
    .dout(grp_fu_803_p3)
);

fsk_lpf_am_addmul_16s_16s_11s_28_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 11 ),
    .dout_WIDTH( 28 ))
am_addmul_16s_16s_11s_28_4_1_U7(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(fsk_lpf_stream_axis_0_stream_axis_ap_int_16_0ul_0ul_0ul_0_delay_8),
    .din1(fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_5),
    .din2(grp_fu_811_p2),
    .ce(grp_fu_811_ce),
    .dout(grp_fu_811_p3)
);

fsk_lpf_ama_addmuladd_16s_16s_15ns_32s_33_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 15 ),
    .din3_WIDTH( 32 ),
    .dout_WIDTH( 33 ))
ama_addmuladd_16s_16s_15ns_32s_33_4_1_U8(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_44_reg_939),
    .din1(fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_43_reg_934),
    .din2(grp_fu_819_p2),
    .din3(grp_fu_760_p4),
    .ce(grp_fu_819_ce),
    .dout(grp_fu_819_p4)
);

fsk_lpf_ama_addmuladd_16s_16s_14ns_33s_33_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 14 ),
    .din3_WIDTH( 33 ),
    .dout_WIDTH( 33 ))
ama_addmuladd_16s_16s_14ns_33s_33_4_1_U9(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_47_reg_944),
    .din1(fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_40_reg_929),
    .din2(grp_fu_829_p2),
    .din3(grp_fu_771_p3),
    .ce(grp_fu_829_ce),
    .dout(grp_fu_829_p4)
);

fsk_lpf_ama_addmuladd_16s_16s_13ns_31s_31_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 13 ),
    .din3_WIDTH( 31 ),
    .dout_WIDTH( 31 ))
ama_addmuladd_16s_16s_13ns_31s_31_4_1_U10(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(fsk_lpf_stream_axis_0_stream_axis_ap_int_16_0ul_0ul_0ul_0_delay_1_load_reg_949),
    .din1(fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_38_reg_924),
    .din2(grp_fu_840_p2),
    .din3(grp_fu_779_p3),
    .ce(grp_fu_840_ce),
    .dout(grp_fu_840_p4)
);

fsk_lpf_ama_addmuladd_16s_16s_7s_28s_28_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 7 ),
    .din3_WIDTH( 28 ),
    .dout_WIDTH( 28 ))
ama_addmuladd_16s_16s_7s_28s_28_4_1_U11(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(fsk_lpf_stream_axis_0_stream_axis_ap_int_16_0ul_0ul_0ul_0_delay_3_load_reg_954),
    .din1(fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_36_reg_919),
    .din2(grp_fu_851_p2),
    .din3(grp_fu_787_p3),
    .ce(grp_fu_851_ce),
    .dout(grp_fu_851_p4)
);

fsk_lpf_ama_addmuladd_16s_16s_12s_29s_29_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 12 ),
    .din3_WIDTH( 29 ),
    .dout_WIDTH( 29 ))
ama_addmuladd_16s_16s_12s_29s_29_4_1_U12(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(fsk_lpf_stream_axis_0_stream_axis_ap_int_16_0ul_0ul_0ul_0_delay_5_load_reg_959),
    .din1(fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_34_reg_914),
    .din2(grp_fu_861_p2),
    .din3(grp_fu_795_p3),
    .ce(grp_fu_861_ce),
    .dout(grp_fu_861_p4)
);

fsk_lpf_ama_addmuladd_16s_16s_12s_29s_29_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 12 ),
    .din3_WIDTH( 29 ),
    .dout_WIDTH( 29 ))
ama_addmuladd_16s_16s_12s_29s_29_4_1_U13(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(fsk_lpf_stream_axis_0_stream_axis_ap_int_16_0ul_0ul_0ul_0_delay_7_load_reg_964),
    .din1(fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_32_reg_909),
    .din2(grp_fu_871_p2),
    .din3(grp_fu_803_p3),
    .ce(grp_fu_871_ce),
    .dout(grp_fu_871_p4)
);

fsk_lpf_ama_addmuladd_16s_16s_10s_28s_28_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 10 ),
    .din3_WIDTH( 28 ),
    .dout_WIDTH( 28 ))
ama_addmuladd_16s_16s_10s_28s_28_4_1_U14(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(fsk_lpf_stream_axis_0_stream_axis_ap_int_16_0ul_0ul_0ul_0_delay_9_load_reg_969),
    .din1(fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_30_reg_903),
    .din2(grp_fu_882_p2),
    .din3(grp_fu_811_p3),
    .ce(grp_fu_882_ce),
    .dout(grp_fu_882_p4)
);

fsk_lpf_regslice_both #(
    .DataWidth( 16 ))
regslice_both_in_r_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_r_TDATA),
    .vld_in(in_r_TVALID),
    .ack_in(regslice_both_in_r_V_data_V_U_ack_in),
    .data_out(in_r_TDATA_int_regslice),
    .vld_out(in_r_TVALID_int_regslice),
    .ack_out(in_r_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_r_V_data_V_U_apdone_blk)
);

fsk_lpf_regslice_both #(
    .DataWidth( 2 ))
regslice_both_in_r_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_r_TKEEP),
    .vld_in(in_r_TVALID),
    .ack_in(regslice_both_in_r_V_keep_V_U_ack_in),
    .data_out(in_r_TKEEP_int_regslice),
    .vld_out(regslice_both_in_r_V_keep_V_U_vld_out),
    .ack_out(in_r_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_r_V_keep_V_U_apdone_blk)
);

fsk_lpf_regslice_both #(
    .DataWidth( 2 ))
regslice_both_in_r_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_r_TSTRB),
    .vld_in(in_r_TVALID),
    .ack_in(regslice_both_in_r_V_strb_V_U_ack_in),
    .data_out(in_r_TSTRB_int_regslice),
    .vld_out(regslice_both_in_r_V_strb_V_U_vld_out),
    .ack_out(in_r_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_r_V_strb_V_U_apdone_blk)
);

fsk_lpf_regslice_both #(
    .DataWidth( 1 ))
regslice_both_in_r_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_r_TLAST),
    .vld_in(in_r_TVALID),
    .ack_in(regslice_both_in_r_V_last_V_U_ack_in),
    .data_out(in_r_TLAST_int_regslice),
    .vld_out(regslice_both_in_r_V_last_V_U_vld_out),
    .ack_out(in_r_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_r_V_last_V_U_apdone_blk)
);

fsk_lpf_regslice_both #(
    .DataWidth( 16 ))
regslice_both_out_r_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(out_r_TDATA_int_regslice),
    .vld_in(out_r_TVALID_int_regslice),
    .ack_in(out_r_TREADY_int_regslice),
    .data_out(out_r_TDATA),
    .vld_out(regslice_both_out_r_V_data_V_U_vld_out),
    .ack_out(out_r_TREADY),
    .apdone_blk(regslice_both_out_r_V_data_V_U_apdone_blk)
);

fsk_lpf_regslice_both #(
    .DataWidth( 2 ))
regslice_both_out_r_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(2'd3),
    .vld_in(out_r_TVALID_int_regslice),
    .ack_in(regslice_both_out_r_V_keep_V_U_ack_in_dummy),
    .data_out(out_r_TKEEP),
    .vld_out(regslice_both_out_r_V_keep_V_U_vld_out),
    .ack_out(out_r_TREADY),
    .apdone_blk(regslice_both_out_r_V_keep_V_U_apdone_blk)
);

fsk_lpf_regslice_both #(
    .DataWidth( 2 ))
regslice_both_out_r_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(2'd3),
    .vld_in(out_r_TVALID_int_regslice),
    .ack_in(regslice_both_out_r_V_strb_V_U_ack_in_dummy),
    .data_out(out_r_TSTRB),
    .vld_out(regslice_both_out_r_V_strb_V_U_vld_out),
    .ack_out(out_r_TREADY),
    .apdone_blk(regslice_both_out_r_V_strb_V_U_apdone_blk)
);

fsk_lpf_regslice_both #(
    .DataWidth( 1 ))
regslice_both_out_r_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(din_last_reg_898_pp0_iter6_reg),
    .vld_in(out_r_TVALID_int_regslice),
    .ack_in(regslice_both_out_r_V_last_V_U_ack_in_dummy),
    .data_out(out_r_TLAST),
    .vld_out(regslice_both_out_r_V_last_V_U_vld_out),
    .ack_out(out_r_TREADY),
    .apdone_blk(regslice_both_out_r_V_last_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        acc_reg_1050 <= acc_fu_693_p2;
        add_ln131_11_reg_1040 <= add_ln131_11_fu_652_p2;
        add_ln131_12_reg_1045 <= add_ln131_12_fu_672_p2;
        add_ln131_1_reg_1020_pp0_iter5_reg <= add_ln131_1_reg_1020;
        add_ln131_4_reg_1025 <= add_ln131_4_fu_644_p2;
        add_ln131_4_reg_1025_pp0_iter5_reg <= add_ln131_4_reg_1025;
        din_last_reg_898_pp0_iter2_reg <= din_last_reg_898_pp0_iter1_reg;
        din_last_reg_898_pp0_iter3_reg <= din_last_reg_898_pp0_iter2_reg;
        din_last_reg_898_pp0_iter4_reg <= din_last_reg_898_pp0_iter3_reg;
        din_last_reg_898_pp0_iter5_reg <= din_last_reg_898_pp0_iter4_reg;
        din_last_reg_898_pp0_iter6_reg <= din_last_reg_898_pp0_iter5_reg;
        icmp_ln139_reg_1055 <= icmp_ln139_fu_719_p2;
        icmp_ln142_reg_1061 <= icmp_ln142_fu_725_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        add_ln131_1_reg_1020 <= grp_fu_819_p4;
        add_ln131_6_reg_1030 <= grp_fu_851_p4;
        add_ln131_7_reg_1035 <= grp_fu_861_p4;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        din_data_reg_893 <= in_r_TDATA_int_regslice;
        din_last_reg_898 <= in_r_TLAST_int_regslice;
        din_last_reg_898_pp0_iter1_reg <= din_last_reg_898;
        fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_30_reg_903 <= fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_6;
        fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_32_reg_909 <= fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_4;
        fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_34_reg_914 <= fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_2;
        fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_36_reg_919 <= fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_0;
        fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_38_reg_924 <= fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_17;
        fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_40_reg_929 <= fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_15;
        fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_43_reg_934 <= fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_12;
        fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_44_reg_939 <= fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_11;
        fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_47_reg_944 <= fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_8;
        fsk_lpf_stream_axis_0_stream_axis_ap_int_16_0ul_0ul_0ul_0_delay_1_load_reg_949 <= fsk_lpf_stream_axis_0_stream_axis_ap_int_16_0ul_0ul_0ul_0_delay_1;
        fsk_lpf_stream_axis_0_stream_axis_ap_int_16_0ul_0ul_0ul_0_delay_3_load_reg_954 <= fsk_lpf_stream_axis_0_stream_axis_ap_int_16_0ul_0ul_0ul_0_delay_3;
        fsk_lpf_stream_axis_0_stream_axis_ap_int_16_0ul_0ul_0ul_0_delay_5_load_reg_959 <= fsk_lpf_stream_axis_0_stream_axis_ap_int_16_0ul_0ul_0ul_0_delay_5;
        fsk_lpf_stream_axis_0_stream_axis_ap_int_16_0ul_0ul_0ul_0_delay_7_load_reg_964 <= fsk_lpf_stream_axis_0_stream_axis_ap_int_16_0ul_0ul_0ul_0_delay_7;
        fsk_lpf_stream_axis_0_stream_axis_ap_int_16_0ul_0ul_0ul_0_delay_9_load_reg_969 <= fsk_lpf_stream_axis_0_stream_axis_ap_int_16_0ul_0ul_0ul_0_delay_9;
        tmp29_reg_974 <= tmp29_fu_600_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay <= fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_17;
        fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_0 <= fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay;
        fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_1 <= fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_0;
        fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_10 <= fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_9;
        fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_11 <= fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_10;
        fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_12 <= fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_11;
        fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_13 <= fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_12;
        fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_14 <= fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_13;
        fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_15 <= fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_14;
        fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_16 <= fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_15;
        fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_17 <= fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_16;
        fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_2 <= fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_1;
        fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_3 <= fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_2;
        fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_4 <= fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_3;
        fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_5 <= fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_4;
        fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_6 <= fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_5;
        fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_8 <= fsk_lpf_stream_axis_0_stream_axis_ap_int_16_0ul_0ul_0ul_0_delay;
        fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_9 <= fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_8;
        fsk_lpf_stream_axis_0_stream_axis_ap_int_16_0ul_0ul_0ul_0_delay <= fsk_lpf_stream_axis_0_stream_axis_ap_int_16_0ul_0ul_0ul_0_delay_1;
        fsk_lpf_stream_axis_0_stream_axis_ap_int_16_0ul_0ul_0ul_0_delay_1 <= fsk_lpf_stream_axis_0_stream_axis_ap_int_16_0ul_0ul_0ul_0_delay_2;
        fsk_lpf_stream_axis_0_stream_axis_ap_int_16_0ul_0ul_0ul_0_delay_2 <= fsk_lpf_stream_axis_0_stream_axis_ap_int_16_0ul_0ul_0ul_0_delay_3;
        fsk_lpf_stream_axis_0_stream_axis_ap_int_16_0ul_0ul_0ul_0_delay_3 <= fsk_lpf_stream_axis_0_stream_axis_ap_int_16_0ul_0ul_0ul_0_delay_4;
        fsk_lpf_stream_axis_0_stream_axis_ap_int_16_0ul_0ul_0ul_0_delay_4 <= fsk_lpf_stream_axis_0_stream_axis_ap_int_16_0ul_0ul_0ul_0_delay_5;
        fsk_lpf_stream_axis_0_stream_axis_ap_int_16_0ul_0ul_0ul_0_delay_5 <= fsk_lpf_stream_axis_0_stream_axis_ap_int_16_0ul_0ul_0ul_0_delay_6;
        fsk_lpf_stream_axis_0_stream_axis_ap_int_16_0ul_0ul_0ul_0_delay_6 <= fsk_lpf_stream_axis_0_stream_axis_ap_int_16_0ul_0ul_0ul_0_delay_7;
        fsk_lpf_stream_axis_0_stream_axis_ap_int_16_0ul_0ul_0ul_0_delay_7 <= fsk_lpf_stream_axis_0_stream_axis_ap_int_16_0ul_0ul_0ul_0_delay_8;
        fsk_lpf_stream_axis_0_stream_axis_ap_int_16_0ul_0ul_0ul_0_delay_8 <= fsk_lpf_stream_axis_0_stream_axis_ap_int_16_0ul_0ul_0ul_0_delay_9;
        fsk_lpf_stream_axis_0_stream_axis_ap_int_16_0ul_0ul_0ul_0_delay_9 <= in_r_TDATA_int_regslice;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_7 <= fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_30_reg_903;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (1'b1 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

assign ap_reset_idle_pp0 = 1'b0;

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_760_ce = 1'b1;
    end else begin
        grp_fu_760_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_771_ce = 1'b1;
    end else begin
        grp_fu_771_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_779_ce = 1'b1;
    end else begin
        grp_fu_779_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_787_ce = 1'b1;
    end else begin
        grp_fu_787_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_795_ce = 1'b1;
    end else begin
        grp_fu_795_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_803_ce = 1'b1;
    end else begin
        grp_fu_803_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_811_ce = 1'b1;
    end else begin
        grp_fu_811_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_819_ce = 1'b1;
    end else begin
        grp_fu_819_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_829_ce = 1'b1;
    end else begin
        grp_fu_829_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_840_ce = 1'b1;
    end else begin
        grp_fu_840_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_851_ce = 1'b1;
    end else begin
        grp_fu_851_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_861_ce = 1'b1;
    end else begin
        grp_fu_861_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_871_ce = 1'b1;
    end else begin
        grp_fu_871_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_882_ce = 1'b1;
    end else begin
        grp_fu_882_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_r_TDATA_blk_n = in_r_TVALID_int_regslice;
    end else begin
        in_r_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_r_TREADY_int_regslice = 1'b1;
    end else begin
        in_r_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter8 == 1'b1) & (1'b0 == ap_block_pp0_stage0)) | ((ap_enable_reg_pp0_iter7 == 1'b1) & (1'b0 == ap_block_pp0_stage0)))) begin
        out_r_TDATA_blk_n = out_r_TREADY_int_regslice;
    end else begin
        out_r_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter7 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        out_r_TVALID_int_regslice = 1'b1;
    end else begin
        out_r_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign acc_fu_693_p2 = ($signed(sext_ln131_38_fu_690_p1) + $signed(add_ln131_5_fu_684_p2));

assign add_ln131_11_fu_652_p2 = ($signed(sext_ln131_36_fu_649_p1) + $signed(grp_fu_871_p4));

assign add_ln131_12_fu_672_p2 = ($signed(sext_ln131_37_fu_669_p1) + $signed(add_ln131_8_fu_663_p2));

assign add_ln131_4_fu_644_p2 = ($signed(sext_ln131_32_fu_641_p1) + $signed(grp_fu_829_p4));

assign add_ln131_5_fu_684_p2 = ($signed(sext_ln131_33_fu_681_p1) + $signed(sext_ln131_31_fu_678_p1));

assign add_ln131_8_fu_663_p2 = ($signed(sext_ln131_35_fu_660_p1) + $signed(sext_ln131_34_fu_657_p1));

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((ap_enable_reg_pp0_iter8 == 1'b1) & ((regslice_both_out_r_V_data_V_U_apdone_blk == 1'b1) | (out_r_TREADY_int_regslice == 1'b0))) | ((ap_enable_reg_pp0_iter7 == 1'b1) & (out_r_TREADY_int_regslice == 1'b0)) | ((in_r_TVALID_int_regslice == 1'b0) & (1'b1 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter8 == 1'b1) & ((regslice_both_out_r_V_data_V_U_apdone_blk == 1'b1) | (out_r_TREADY_int_regslice == 1'b0))) | ((ap_enable_reg_pp0_iter7 == 1'b1) & (out_r_TREADY_int_regslice == 1'b0)) | ((in_r_TVALID_int_regslice == 1'b0) & (1'b1 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter8 == 1'b1) & ((regslice_both_out_r_V_data_V_U_apdone_blk == 1'b1) | (out_r_TREADY_int_regslice == 1'b0))) | ((ap_enable_reg_pp0_iter7 == 1'b1) & (out_r_TREADY_int_regslice == 1'b0)) | ((in_r_TVALID_int_regslice == 1'b0) & (1'b1 == 1'b1)));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (in_r_TVALID_int_regslice == 1'b0);
end

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state8_pp0_stage0_iter7 = (out_r_TREADY_int_regslice == 1'b0);
end

always @ (*) begin
    ap_block_state9_pp0_stage0_iter8 = ((regslice_both_out_r_V_data_V_U_apdone_blk == 1'b1) | (out_r_TREADY_int_regslice == 1'b0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign dout_data_fu_731_p4 = {{acc_reg_1050[31:16]}};

assign fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_48_fu_596_p0 = fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_7;

assign fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_48_fu_596_p1 = fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_48_fu_596_p0;

assign grp_fu_760_p2 = 32'd24623;

assign grp_fu_771_p2 = 33'd20468;

assign grp_fu_779_p2 = 31'd9978;

assign grp_fu_787_p2 = 28'd1914;

assign grp_fu_795_p2 = 29'd536869790;

assign grp_fu_803_p2 = 29'd536869528;

assign grp_fu_811_p2 = 28'd268434774;

assign grp_fu_819_p2 = 33'd26732;

assign grp_fu_829_p2 = 32'd15242;

assign grp_fu_840_p2 = 31'd5318;

assign grp_fu_851_p2 = 24'd16777178;

assign grp_fu_861_p2 = 29'd536869422;

assign grp_fu_871_p2 = 29'd536869857;

assign grp_fu_882_p2 = 27'd134217373;

assign icmp_ln139_fu_719_p2 = (($signed(tmp_1_fu_709_p4) > $signed(3'd0)) ? 1'b1 : 1'b0);

assign icmp_ln142_fu_725_p2 = (($signed(trunc_ln_fu_699_p4) < $signed(18'd229376)) ? 1'b1 : 1'b0);

assign in_r_TREADY = regslice_both_in_r_V_data_V_U_ack_in;

assign or_ln139_fu_747_p2 = (icmp_ln142_reg_1061 | icmp_ln139_reg_1055);

assign out_r_TDATA_int_regslice = ((or_ln139_fu_747_p2[0:0] == 1'b1) ? select_ln139_fu_740_p3 : dout_data_fu_731_p4);

assign out_r_TVALID = regslice_both_out_r_V_data_V_U_vld_out;

assign p_shl1_cast_fu_624_p1 = $signed(p_shl1_fu_617_p3);

assign p_shl1_fu_617_p3 = {{tmp29_reg_974}, {2'd0}};

assign p_shl_cast_fu_613_p1 = $signed(p_shl_fu_606_p3);

assign p_shl_fu_606_p3 = {{tmp29_reg_974}, {7'd0}};

assign select_ln139_fu_740_p3 = ((icmp_ln139_reg_1055[0:0] == 1'b1) ? 16'd32767 : 16'd32768);

assign sext_ln131_31_fu_678_p1 = add_ln131_1_reg_1020_pp0_iter5_reg;

assign sext_ln131_32_fu_641_p1 = grp_fu_840_p4;

assign sext_ln131_33_fu_681_p1 = $signed(add_ln131_4_reg_1025_pp0_iter5_reg);

assign sext_ln131_34_fu_657_p1 = add_ln131_6_reg_1030;

assign sext_ln131_35_fu_660_p1 = add_ln131_7_reg_1035;

assign sext_ln131_36_fu_649_p1 = grp_fu_882_p4;

assign sext_ln131_37_fu_669_p1 = $signed(add_ln131_11_reg_1040);

assign sext_ln131_38_fu_690_p1 = $signed(add_ln131_12_reg_1045);

assign sext_ln131_fu_551_p1 = din_data_reg_893;

assign tmp29_fu_600_p2 = ($signed(fsk_lpf_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_hls_stream_hls_axis_ap_int_16_0ul_0ul_0ul_0_delay_48_fu_596_p1) + $signed(sext_ln131_fu_551_p1));

assign tmp30_fu_628_p2 = ($signed(p_shl1_cast_fu_624_p1) - $signed(p_shl_cast_fu_613_p1));

assign tmp_1_fu_709_p4 = {{acc_fu_693_p2[33:31]}};

assign trunc_ln_fu_699_p4 = {{acc_fu_693_p2[33:16]}};


reg find_kernel_block = 0;
// synthesis translate_off
`include "fsk_lpf_hls_deadlock_kernel_monitor_top.vh"
// synthesis translate_on

endmodule //fsk_lpf

