// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="fsk_decimator_fsk_decimator,hls_ip_2023_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=pipeline,HLS_SYN_CLOCK=4.140000,HLS_SYN_LAT=2,HLS_SYN_TPT=1,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=110,HLS_SYN_LUT=242,HLS_VERSION=2023_1}" *)

module fsk_decimator (
        ap_clk,
        ap_rst_n,
        rx_in_TDATA,
        rx_in_TVALID,
        rx_in_TREADY,
        rx_in_TKEEP,
        rx_in_TSTRB,
        rx_in_TLAST,
        dec_out_TDATA,
        dec_out_TVALID,
        dec_out_TREADY,
        dec_out_TKEEP,
        dec_out_TSTRB,
        dec_out_TLAST
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst_n;
input  [31:0] rx_in_TDATA;
input   rx_in_TVALID;
output   rx_in_TREADY;
input  [3:0] rx_in_TKEEP;
input  [3:0] rx_in_TSTRB;
input  [0:0] rx_in_TLAST;
output  [31:0] dec_out_TDATA;
output   dec_out_TVALID;
input   dec_out_TREADY;
output  [3:0] dec_out_TKEEP;
output  [3:0] dec_out_TSTRB;
output  [0:0] dec_out_TLAST;

 reg    ap_rst_n_inv;
reg   [31:0] acc_i;
reg   [31:0] acc_q;
reg   [7:0] dec_counter;
reg    rx_in_TDATA_blk_n;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_block_pp0_stage0;
reg    dec_out_TDATA_blk_n;
reg    ap_enable_reg_pp0_iter1;
reg   [0:0] icmp_ln40_reg_289;
reg    ap_enable_reg_pp0_iter2;
reg   [0:0] icmp_ln40_reg_289_pp0_iter1_reg;
reg   [0:0] pkt_rx_last_V_reg_284;
reg    ap_block_state1_pp0_stage0_iter0;
reg    ap_block_state2_pp0_stage0_iter1;
reg    ap_block_state2_io;
wire    regslice_both_dec_out_V_data_V_U_apdone_blk;
reg    ap_block_state3_pp0_stage0_iter2;
reg    ap_block_state3_io;
reg    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln40_fu_226_p2;
reg   [15:0] trunc_ln2_reg_293;
reg   [15:0] trunc_ln3_reg_298;
reg    ap_block_pp0_stage0_subdone;
reg   [31:0] ap_phi_mux_acc_i_new_0_phi_fu_115_p4;
wire   [31:0] ap_phi_reg_pp0_iter0_acc_i_new_0_reg_112;
wire   [31:0] add_ln35_fu_180_p2;
reg   [31:0] ap_phi_mux_acc_q_new_0_phi_fu_125_p4;
wire   [31:0] ap_phi_reg_pp0_iter0_acc_q_new_0_reg_122;
wire   [31:0] add_ln36_fu_209_p2;
reg   [7:0] ap_phi_mux_storemerge_phi_fu_135_p4;
wire   [7:0] ap_phi_reg_pp0_iter0_storemerge_reg_132;
wire   [7:0] add_ln64_fu_232_p2;
reg    ap_block_pp0_stage0_01001;
wire  signed [15:0] rx_i_fu_150_p1;
wire  signed [31:0] sext_ln35_fu_164_p1;
wire   [23:0] trunc_ln35_fu_176_p1;
wire  signed [23:0] sext_ln35_1_fu_172_p1;
wire  signed [15:0] rx_q_fu_154_p4;
wire  signed [31:0] sext_ln36_fu_193_p1;
wire   [23:0] trunc_ln36_fu_205_p1;
wire  signed [23:0] sext_ln36_1_fu_201_p1;
wire   [23:0] add_ln36_1_fu_187_p2;
wire   [23:0] add_ln40_fu_216_p2;
reg   [0:0] ap_NS_fsm;
wire    ap_reset_idle_pp0;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
wire    regslice_both_rx_in_V_data_V_U_apdone_blk;
wire   [31:0] rx_in_TDATA_int_regslice;
wire    rx_in_TVALID_int_regslice;
reg    rx_in_TREADY_int_regslice;
wire    regslice_both_rx_in_V_data_V_U_ack_in;
wire    regslice_both_rx_in_V_keep_V_U_apdone_blk;
wire   [3:0] rx_in_TKEEP_int_regslice;
wire    regslice_both_rx_in_V_keep_V_U_vld_out;
wire    regslice_both_rx_in_V_keep_V_U_ack_in;
wire    regslice_both_rx_in_V_strb_V_U_apdone_blk;
wire   [3:0] rx_in_TSTRB_int_regslice;
wire    regslice_both_rx_in_V_strb_V_U_vld_out;
wire    regslice_both_rx_in_V_strb_V_U_ack_in;
wire    regslice_both_rx_in_V_last_V_U_apdone_blk;
wire   [0:0] rx_in_TLAST_int_regslice;
wire    regslice_both_rx_in_V_last_V_U_vld_out;
wire    regslice_both_rx_in_V_last_V_U_ack_in;
wire   [31:0] dec_out_TDATA_int_regslice;
reg    dec_out_TVALID_int_regslice;
wire    dec_out_TREADY_int_regslice;
wire    regslice_both_dec_out_V_data_V_U_vld_out;
wire    regslice_both_dec_out_V_keep_V_U_apdone_blk;
wire    regslice_both_dec_out_V_keep_V_U_ack_in_dummy;
wire    regslice_both_dec_out_V_keep_V_U_vld_out;
wire    regslice_both_dec_out_V_strb_V_U_apdone_blk;
wire    regslice_both_dec_out_V_strb_V_U_ack_in_dummy;
wire    regslice_both_dec_out_V_strb_V_U_vld_out;
wire    regslice_both_dec_out_V_last_V_U_apdone_blk;
wire    regslice_both_dec_out_V_last_V_U_ack_in_dummy;
wire    regslice_both_dec_out_V_last_V_U_vld_out;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 acc_i = 32'd0;
#0 acc_q = 32'd0;
#0 dec_counter = 8'd0;
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
end

fsk_decimator_regslice_both #(
    .DataWidth( 32 ))
regslice_both_rx_in_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(rx_in_TDATA),
    .vld_in(rx_in_TVALID),
    .ack_in(regslice_both_rx_in_V_data_V_U_ack_in),
    .data_out(rx_in_TDATA_int_regslice),
    .vld_out(rx_in_TVALID_int_regslice),
    .ack_out(rx_in_TREADY_int_regslice),
    .apdone_blk(regslice_both_rx_in_V_data_V_U_apdone_blk)
);

fsk_decimator_regslice_both #(
    .DataWidth( 4 ))
regslice_both_rx_in_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(rx_in_TKEEP),
    .vld_in(rx_in_TVALID),
    .ack_in(regslice_both_rx_in_V_keep_V_U_ack_in),
    .data_out(rx_in_TKEEP_int_regslice),
    .vld_out(regslice_both_rx_in_V_keep_V_U_vld_out),
    .ack_out(rx_in_TREADY_int_regslice),
    .apdone_blk(regslice_both_rx_in_V_keep_V_U_apdone_blk)
);

fsk_decimator_regslice_both #(
    .DataWidth( 4 ))
regslice_both_rx_in_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(rx_in_TSTRB),
    .vld_in(rx_in_TVALID),
    .ack_in(regslice_both_rx_in_V_strb_V_U_ack_in),
    .data_out(rx_in_TSTRB_int_regslice),
    .vld_out(regslice_both_rx_in_V_strb_V_U_vld_out),
    .ack_out(rx_in_TREADY_int_regslice),
    .apdone_blk(regslice_both_rx_in_V_strb_V_U_apdone_blk)
);

fsk_decimator_regslice_both #(
    .DataWidth( 1 ))
regslice_both_rx_in_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(rx_in_TLAST),
    .vld_in(rx_in_TVALID),
    .ack_in(regslice_both_rx_in_V_last_V_U_ack_in),
    .data_out(rx_in_TLAST_int_regslice),
    .vld_out(regslice_both_rx_in_V_last_V_U_vld_out),
    .ack_out(rx_in_TREADY_int_regslice),
    .apdone_blk(regslice_both_rx_in_V_last_V_U_apdone_blk)
);

fsk_decimator_regslice_both #(
    .DataWidth( 32 ))
regslice_both_dec_out_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(dec_out_TDATA_int_regslice),
    .vld_in(dec_out_TVALID_int_regslice),
    .ack_in(dec_out_TREADY_int_regslice),
    .data_out(dec_out_TDATA),
    .vld_out(regslice_both_dec_out_V_data_V_U_vld_out),
    .ack_out(dec_out_TREADY),
    .apdone_blk(regslice_both_dec_out_V_data_V_U_apdone_blk)
);

fsk_decimator_regslice_both #(
    .DataWidth( 4 ))
regslice_both_dec_out_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(4'd15),
    .vld_in(dec_out_TVALID_int_regslice),
    .ack_in(regslice_both_dec_out_V_keep_V_U_ack_in_dummy),
    .data_out(dec_out_TKEEP),
    .vld_out(regslice_both_dec_out_V_keep_V_U_vld_out),
    .ack_out(dec_out_TREADY),
    .apdone_blk(regslice_both_dec_out_V_keep_V_U_apdone_blk)
);

fsk_decimator_regslice_both #(
    .DataWidth( 4 ))
regslice_both_dec_out_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(4'd0),
    .vld_in(dec_out_TVALID_int_regslice),
    .ack_in(regslice_both_dec_out_V_strb_V_U_ack_in_dummy),
    .data_out(dec_out_TSTRB),
    .vld_out(regslice_both_dec_out_V_strb_V_U_vld_out),
    .ack_out(dec_out_TREADY),
    .apdone_blk(regslice_both_dec_out_V_strb_V_U_apdone_blk)
);

fsk_decimator_regslice_both #(
    .DataWidth( 1 ))
regslice_both_dec_out_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(pkt_rx_last_V_reg_284),
    .vld_in(dec_out_TVALID_int_regslice),
    .ack_in(regslice_both_dec_out_V_last_V_U_ack_in_dummy),
    .data_out(dec_out_TLAST),
    .vld_out(regslice_both_dec_out_V_last_V_U_vld_out),
    .ack_out(dec_out_TREADY),
    .apdone_blk(regslice_both_dec_out_V_last_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_i <= ap_phi_mux_acc_i_new_0_phi_fu_115_p4;
        acc_q <= ap_phi_mux_acc_q_new_0_phi_fu_125_p4;
        dec_counter <= ap_phi_mux_storemerge_phi_fu_135_p4;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln40_reg_289 <= icmp_ln40_fu_226_p2;
        icmp_ln40_reg_289_pp0_iter1_reg <= icmp_ln40_reg_289;
        pkt_rx_last_V_reg_284 <= rx_in_TLAST_int_regslice;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln40_fu_226_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        trunc_ln2_reg_293 <= {{add_ln36_1_fu_187_p2[23:8]}};
        trunc_ln3_reg_298 <= {{add_ln40_fu_216_p2[23:8]}};
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (1'b1 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((icmp_ln40_fu_226_p2 == 1'd0)) begin
        ap_phi_mux_acc_i_new_0_phi_fu_115_p4 = add_ln35_fu_180_p2;
    end else if ((icmp_ln40_fu_226_p2 == 1'd1)) begin
        ap_phi_mux_acc_i_new_0_phi_fu_115_p4 = 32'd0;
    end else begin
        ap_phi_mux_acc_i_new_0_phi_fu_115_p4 = ap_phi_reg_pp0_iter0_acc_i_new_0_reg_112;
    end
end

always @ (*) begin
    if ((icmp_ln40_fu_226_p2 == 1'd0)) begin
        ap_phi_mux_acc_q_new_0_phi_fu_125_p4 = add_ln36_fu_209_p2;
    end else if ((icmp_ln40_fu_226_p2 == 1'd1)) begin
        ap_phi_mux_acc_q_new_0_phi_fu_125_p4 = 32'd0;
    end else begin
        ap_phi_mux_acc_q_new_0_phi_fu_125_p4 = ap_phi_reg_pp0_iter0_acc_q_new_0_reg_122;
    end
end

always @ (*) begin
    if ((icmp_ln40_fu_226_p2 == 1'd0)) begin
        ap_phi_mux_storemerge_phi_fu_135_p4 = add_ln64_fu_232_p2;
    end else if ((icmp_ln40_fu_226_p2 == 1'd1)) begin
        ap_phi_mux_storemerge_phi_fu_135_p4 = 8'd0;
    end else begin
        ap_phi_mux_storemerge_phi_fu_135_p4 = ap_phi_reg_pp0_iter0_storemerge_reg_132;
    end
end

assign ap_reset_idle_pp0 = 1'b0;

always @ (*) begin
    if ((((icmp_ln40_reg_289_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0)) | ((icmp_ln40_reg_289 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        dec_out_TDATA_blk_n = dec_out_TREADY_int_regslice;
    end else begin
        dec_out_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln40_reg_289 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dec_out_TVALID_int_regslice = 1'b1;
    end else begin
        dec_out_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        rx_in_TDATA_blk_n = rx_in_TVALID_int_regslice;
    end else begin
        rx_in_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        rx_in_TREADY_int_regslice = 1'b1;
    end else begin
        rx_in_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln35_fu_180_p2 = ($signed(acc_i) + $signed(sext_ln35_fu_164_p1));

assign add_ln36_1_fu_187_p2 = ($signed(trunc_ln35_fu_176_p1) + $signed(sext_ln35_1_fu_172_p1));

assign add_ln36_fu_209_p2 = ($signed(acc_q) + $signed(sext_ln36_fu_193_p1));

assign add_ln40_fu_216_p2 = ($signed(trunc_ln36_fu_205_p1) + $signed(sext_ln36_1_fu_201_p1));

assign add_ln64_fu_232_p2 = (dec_counter + 8'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((ap_enable_reg_pp0_iter2 == 1'b1) & ((regslice_both_dec_out_V_data_V_U_apdone_blk == 1'b1) | ((icmp_ln40_reg_289_pp0_iter1_reg == 1'd1) & (dec_out_TREADY_int_regslice == 1'b0)))) | ((icmp_ln40_reg_289 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (dec_out_TREADY_int_regslice == 1'b0)) | ((1'b1 == 1'b1) & (rx_in_TVALID_int_regslice == 1'b0)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter2 == 1'b1) & ((regslice_both_dec_out_V_data_V_U_apdone_blk == 1'b1) | (1'b1 == ap_block_state3_io) | ((icmp_ln40_reg_289_pp0_iter1_reg == 1'd1) & (dec_out_TREADY_int_regslice == 1'b0)))) | ((ap_enable_reg_pp0_iter1 == 1'b1) & ((1'b1 == ap_block_state2_io) | ((icmp_ln40_reg_289 == 1'd1) & (dec_out_TREADY_int_regslice == 1'b0)))) | ((1'b1 == 1'b1) & (rx_in_TVALID_int_regslice == 1'b0)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter2 == 1'b1) & ((regslice_both_dec_out_V_data_V_U_apdone_blk == 1'b1) | (1'b1 == ap_block_state3_io) | ((icmp_ln40_reg_289_pp0_iter1_reg == 1'd1) & (dec_out_TREADY_int_regslice == 1'b0)))) | ((ap_enable_reg_pp0_iter1 == 1'b1) & ((1'b1 == ap_block_state2_io) | ((icmp_ln40_reg_289 == 1'd1) & (dec_out_TREADY_int_regslice == 1'b0)))) | ((1'b1 == 1'b1) & (rx_in_TVALID_int_regslice == 1'b0)));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (rx_in_TVALID_int_regslice == 1'b0);
end

always @ (*) begin
    ap_block_state2_io = ((icmp_ln40_reg_289 == 1'd1) & (dec_out_TREADY_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = ((icmp_ln40_reg_289 == 1'd1) & (dec_out_TREADY_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_state3_io = ((icmp_ln40_reg_289_pp0_iter1_reg == 1'd1) & (dec_out_TREADY_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_state3_pp0_stage0_iter2 = ((regslice_both_dec_out_V_data_V_U_apdone_blk == 1'b1) | ((icmp_ln40_reg_289_pp0_iter1_reg == 1'd1) & (dec_out_TREADY_int_regslice == 1'b0)));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_phi_reg_pp0_iter0_acc_i_new_0_reg_112 = 'bx;

assign ap_phi_reg_pp0_iter0_acc_q_new_0_reg_122 = 'bx;

assign ap_phi_reg_pp0_iter0_storemerge_reg_132 = 'bx;

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign dec_out_TDATA_int_regslice = {{trunc_ln3_reg_298}, {trunc_ln2_reg_293}};

assign dec_out_TVALID = regslice_both_dec_out_V_data_V_U_vld_out;

assign icmp_ln40_fu_226_p2 = ((dec_counter == 8'd255) ? 1'b1 : 1'b0);

assign rx_i_fu_150_p1 = rx_in_TDATA_int_regslice[15:0];

assign rx_in_TREADY = regslice_both_rx_in_V_data_V_U_ack_in;

assign rx_q_fu_154_p4 = {{rx_in_TDATA_int_regslice[31:16]}};

assign sext_ln35_1_fu_172_p1 = rx_i_fu_150_p1;

assign sext_ln35_fu_164_p1 = rx_i_fu_150_p1;

assign sext_ln36_1_fu_201_p1 = rx_q_fu_154_p4;

assign sext_ln36_fu_193_p1 = rx_q_fu_154_p4;

assign trunc_ln35_fu_176_p1 = acc_i[23:0];

assign trunc_ln36_fu_205_p1 = acc_q[23:0];


reg find_kernel_block = 0;
// synthesis translate_off
`include "fsk_decimator_hls_deadlock_kernel_monitor_top.vh"
// synthesis translate_on

endmodule //fsk_decimator

