-- ==============================================================
-- Generated by Vitis HLS v2023.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity gaussian_shaping_v2 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    in_stream_TDATA : IN STD_LOGIC_VECTOR (7 downto 0);
    in_stream_TVALID : IN STD_LOGIC;
    in_stream_TREADY : OUT STD_LOGIC;
    in_stream_TKEEP : IN STD_LOGIC_VECTOR (0 downto 0);
    in_stream_TSTRB : IN STD_LOGIC_VECTOR (0 downto 0);
    in_stream_TUSER : IN STD_LOGIC_VECTOR (12 downto 0);
    in_stream_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    fcw_out_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    fcw_out_TVALID : OUT STD_LOGIC;
    fcw_out_TREADY : IN STD_LOGIC;
    fcw_out_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
    fcw_out_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    fcw_out_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0) );
end;


architecture behav of gaussian_shaping_v2 is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "gaussian_shaping_v2_gaussian_shaping_v2,hls_ip_2023_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=pipeline,HLS_SYN_CLOCK=5.657563,HLS_SYN_LAT=5,HLS_SYN_TPT=1,HLS_SYN_MEM=80,HLS_SYN_DSP=0,HLS_SYN_FF=100,HLS_SYN_LUT=118,HLS_VERSION=2023_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv4_F : STD_LOGIC_VECTOR (3 downto 0) := "1111";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv13_0 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000000";
    constant ap_const_lv27_42AAAAA : STD_LOGIC_VECTOR (26 downto 0) := "100001010101010101010101010";
    constant ap_const_lv16_1900 : STD_LOGIC_VECTOR (15 downto 0) := "0001100100000000";

    signal ap_rst_n_inv : STD_LOGIC;
    signal history : STD_LOGIC_VECTOR (2 downto 0) := "111";
    signal GAUSS_LUT_address0 : STD_LOGIC_VECTOR (15 downto 0);
    signal GAUSS_LUT_ce0 : STD_LOGIC;
    signal GAUSS_LUT_q0 : STD_LOGIC_VECTOR (19 downto 0);
    signal in_stream_TDATA_blk_n : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal fcw_out_TDATA_blk_n : STD_LOGIC;
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal input_pkt_user_V_reg_207 : STD_LOGIC_VECTOR (12 downto 0);
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4 : BOOLEAN;
    signal regslice_both_fcw_out_V_data_V_U_apdone_blk : STD_LOGIC;
    signal ap_block_state6_pp0_stage0_iter5 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal input_pkt_user_V_reg_207_pp0_iter1_reg : STD_LOGIC_VECTOR (12 downto 0);
    signal input_pkt_last_V_reg_212 : STD_LOGIC_VECTOR (0 downto 0);
    signal input_pkt_last_V_reg_212_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal input_pkt_last_V_reg_212_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal input_pkt_last_V_reg_212_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_phi_mux_history_loc_0_phi_fu_120_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal or_ln_fu_157_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_phi_reg_pp0_iter0_history_loc_0_reg_117 : STD_LOGIC_VECTOR (2 downto 0);
    signal icmp_ln39_fu_142_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln45_2_fu_179_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal trunc_ln40_fu_153_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln34_fu_138_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_198_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln48_fu_183_p1 : STD_LOGIC_VECTOR (26 downto 0);
    signal current_fcw_fu_187_p2 : STD_LOGIC_VECTOR (26 downto 0);
    signal grp_fu_198_p0 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_fu_198_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal grp_fu_198_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal grp_fu_198_ce : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reset_idle_pp0 : STD_LOGIC;
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal regslice_both_in_stream_V_data_V_U_apdone_blk : STD_LOGIC;
    signal in_stream_TDATA_int_regslice : STD_LOGIC_VECTOR (7 downto 0);
    signal in_stream_TVALID_int_regslice : STD_LOGIC;
    signal in_stream_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_in_stream_V_data_V_U_ack_in : STD_LOGIC;
    signal regslice_both_in_stream_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal in_stream_TKEEP_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_in_stream_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_in_stream_V_keep_V_U_ack_in : STD_LOGIC;
    signal regslice_both_in_stream_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal in_stream_TSTRB_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_in_stream_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_in_stream_V_strb_V_U_ack_in : STD_LOGIC;
    signal regslice_both_in_stream_V_user_V_U_apdone_blk : STD_LOGIC;
    signal in_stream_TUSER_int_regslice : STD_LOGIC_VECTOR (12 downto 0);
    signal regslice_both_in_stream_V_user_V_U_vld_out : STD_LOGIC;
    signal regslice_both_in_stream_V_user_V_U_ack_in : STD_LOGIC;
    signal regslice_both_in_stream_V_last_V_U_apdone_blk : STD_LOGIC;
    signal in_stream_TLAST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_in_stream_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_in_stream_V_last_V_U_ack_in : STD_LOGIC;
    signal fcw_out_TDATA_int_regslice : STD_LOGIC_VECTOR (31 downto 0);
    signal fcw_out_TVALID_int_regslice : STD_LOGIC;
    signal fcw_out_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_fcw_out_V_data_V_U_vld_out : STD_LOGIC;
    signal regslice_both_fcw_out_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_fcw_out_V_keep_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_fcw_out_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_fcw_out_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_fcw_out_V_strb_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_fcw_out_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_fcw_out_V_last_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_fcw_out_V_last_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_fcw_out_V_last_V_U_vld_out : STD_LOGIC;
    signal grp_fu_198_p00 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_198_p20 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component gaussian_shaping_v2_mac_muladd_3ns_13ns_13ns_16_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (2 downto 0);
        din1 : IN STD_LOGIC_VECTOR (12 downto 0);
        din2 : IN STD_LOGIC_VECTOR (12 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component gaussian_shaping_v2_GAUSS_LUT_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (15 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (19 downto 0) );
    end component;


    component gaussian_shaping_v2_regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    GAUSS_LUT_U : component gaussian_shaping_v2_GAUSS_LUT_ROM_AUTO_1R
    generic map (
        DataWidth => 20,
        AddressRange => 51200,
        AddressWidth => 16)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => GAUSS_LUT_address0,
        ce0 => GAUSS_LUT_ce0,
        q0 => GAUSS_LUT_q0);

    mac_muladd_3ns_13ns_13ns_16_4_1_U1 : component gaussian_shaping_v2_mac_muladd_3ns_13ns_13ns_16_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 3,
        din1_WIDTH => 13,
        din2_WIDTH => 13,
        dout_WIDTH => 16)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => grp_fu_198_p0,
        din1 => grp_fu_198_p1,
        din2 => grp_fu_198_p2,
        ce => grp_fu_198_ce,
        dout => grp_fu_198_p3);

    regslice_both_in_stream_V_data_V_U : component gaussian_shaping_v2_regslice_both
    generic map (
        DataWidth => 8)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_stream_TDATA,
        vld_in => in_stream_TVALID,
        ack_in => regslice_both_in_stream_V_data_V_U_ack_in,
        data_out => in_stream_TDATA_int_regslice,
        vld_out => in_stream_TVALID_int_regslice,
        ack_out => in_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_in_stream_V_data_V_U_apdone_blk);

    regslice_both_in_stream_V_keep_V_U : component gaussian_shaping_v2_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_stream_TKEEP,
        vld_in => in_stream_TVALID,
        ack_in => regslice_both_in_stream_V_keep_V_U_ack_in,
        data_out => in_stream_TKEEP_int_regslice,
        vld_out => regslice_both_in_stream_V_keep_V_U_vld_out,
        ack_out => in_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_in_stream_V_keep_V_U_apdone_blk);

    regslice_both_in_stream_V_strb_V_U : component gaussian_shaping_v2_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_stream_TSTRB,
        vld_in => in_stream_TVALID,
        ack_in => regslice_both_in_stream_V_strb_V_U_ack_in,
        data_out => in_stream_TSTRB_int_regslice,
        vld_out => regslice_both_in_stream_V_strb_V_U_vld_out,
        ack_out => in_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_in_stream_V_strb_V_U_apdone_blk);

    regslice_both_in_stream_V_user_V_U : component gaussian_shaping_v2_regslice_both
    generic map (
        DataWidth => 13)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_stream_TUSER,
        vld_in => in_stream_TVALID,
        ack_in => regslice_both_in_stream_V_user_V_U_ack_in,
        data_out => in_stream_TUSER_int_regslice,
        vld_out => regslice_both_in_stream_V_user_V_U_vld_out,
        ack_out => in_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_in_stream_V_user_V_U_apdone_blk);

    regslice_both_in_stream_V_last_V_U : component gaussian_shaping_v2_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_stream_TLAST,
        vld_in => in_stream_TVALID,
        ack_in => regslice_both_in_stream_V_last_V_U_ack_in,
        data_out => in_stream_TLAST_int_regslice,
        vld_out => regslice_both_in_stream_V_last_V_U_vld_out,
        ack_out => in_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_in_stream_V_last_V_U_apdone_blk);

    regslice_both_fcw_out_V_data_V_U : component gaussian_shaping_v2_regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => fcw_out_TDATA_int_regslice,
        vld_in => fcw_out_TVALID_int_regslice,
        ack_in => fcw_out_TREADY_int_regslice,
        data_out => fcw_out_TDATA,
        vld_out => regslice_both_fcw_out_V_data_V_U_vld_out,
        ack_out => fcw_out_TREADY,
        apdone_blk => regslice_both_fcw_out_V_data_V_U_apdone_blk);

    regslice_both_fcw_out_V_keep_V_U : component gaussian_shaping_v2_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => ap_const_lv4_F,
        vld_in => fcw_out_TVALID_int_regslice,
        ack_in => regslice_both_fcw_out_V_keep_V_U_ack_in_dummy,
        data_out => fcw_out_TKEEP,
        vld_out => regslice_both_fcw_out_V_keep_V_U_vld_out,
        ack_out => fcw_out_TREADY,
        apdone_blk => regslice_both_fcw_out_V_keep_V_U_apdone_blk);

    regslice_both_fcw_out_V_strb_V_U : component gaussian_shaping_v2_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => ap_const_lv4_0,
        vld_in => fcw_out_TVALID_int_regslice,
        ack_in => regslice_both_fcw_out_V_strb_V_U_ack_in_dummy,
        data_out => fcw_out_TSTRB,
        vld_out => regslice_both_fcw_out_V_strb_V_U_vld_out,
        ack_out => fcw_out_TREADY,
        apdone_blk => regslice_both_fcw_out_V_strb_V_U_apdone_blk);

    regslice_both_fcw_out_V_last_V_U : component gaussian_shaping_v2_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => input_pkt_last_V_reg_212_pp0_iter3_reg,
        vld_in => fcw_out_TVALID_int_regslice,
        ack_in => regslice_both_fcw_out_V_last_V_U_ack_in_dummy,
        data_out => fcw_out_TLAST,
        vld_out => regslice_both_fcw_out_V_last_V_U_vld_out,
        ack_out => fcw_out_TREADY,
        apdone_blk => regslice_both_fcw_out_V_last_V_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln39_fu_142_p2 = ap_const_lv1_1))) then
                history <= or_ln_fu_157_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                input_pkt_last_V_reg_212 <= in_stream_TLAST_int_regslice;
                input_pkt_last_V_reg_212_pp0_iter1_reg <= input_pkt_last_V_reg_212;
                input_pkt_user_V_reg_207 <= in_stream_TUSER_int_regslice;
                input_pkt_user_V_reg_207_pp0_iter1_reg <= input_pkt_user_V_reg_207;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                input_pkt_last_V_reg_212_pp0_iter2_reg <= input_pkt_last_V_reg_212_pp0_iter1_reg;
                input_pkt_last_V_reg_212_pp0_iter3_reg <= input_pkt_last_V_reg_212_pp0_iter2_reg;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage0_subdone, ap_reset_idle_pp0)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    GAUSS_LUT_address0 <= zext_ln45_2_fu_179_p1(16 - 1 downto 0);

    GAUSS_LUT_ce0_assign_proc : process(ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter3)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            GAUSS_LUT_ce0 <= ap_const_logic_1;
        else 
            GAUSS_LUT_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, regslice_both_fcw_out_V_data_V_U_apdone_blk, in_stream_TVALID_int_regslice, fcw_out_TREADY_int_regslice)
    begin
                ap_block_pp0_stage0_01001 <= (((ap_enable_reg_pp0_iter5 = ap_const_logic_1) and ((regslice_both_fcw_out_V_data_V_U_apdone_blk = ap_const_logic_1) or (fcw_out_TREADY_int_regslice = ap_const_logic_0))) or ((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (fcw_out_TREADY_int_regslice = ap_const_logic_0)) or ((ap_const_logic_1 = ap_const_logic_1) and (in_stream_TVALID_int_regslice = ap_const_logic_0)));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, regslice_both_fcw_out_V_data_V_U_apdone_blk, in_stream_TVALID_int_regslice, fcw_out_TREADY_int_regslice)
    begin
                ap_block_pp0_stage0_11001 <= (((ap_enable_reg_pp0_iter5 = ap_const_logic_1) and ((regslice_both_fcw_out_V_data_V_U_apdone_blk = ap_const_logic_1) or (fcw_out_TREADY_int_regslice = ap_const_logic_0))) or ((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (fcw_out_TREADY_int_regslice = ap_const_logic_0)) or ((ap_const_logic_1 = ap_const_logic_1) and (in_stream_TVALID_int_regslice = ap_const_logic_0)));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, regslice_both_fcw_out_V_data_V_U_apdone_blk, in_stream_TVALID_int_regslice, fcw_out_TREADY_int_regslice)
    begin
                ap_block_pp0_stage0_subdone <= (((ap_enable_reg_pp0_iter5 = ap_const_logic_1) and ((regslice_both_fcw_out_V_data_V_U_apdone_blk = ap_const_logic_1) or (fcw_out_TREADY_int_regslice = ap_const_logic_0))) or ((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (fcw_out_TREADY_int_regslice = ap_const_logic_0)) or ((ap_const_logic_1 = ap_const_logic_1) and (in_stream_TVALID_int_regslice = ap_const_logic_0)));
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(in_stream_TVALID_int_regslice)
    begin
                ap_block_state1_pp0_stage0_iter0 <= (in_stream_TVALID_int_regslice = ap_const_logic_0);
    end process;

        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state5_pp0_stage0_iter4_assign_proc : process(fcw_out_TREADY_int_regslice)
    begin
                ap_block_state5_pp0_stage0_iter4 <= (fcw_out_TREADY_int_regslice = ap_const_logic_0);
    end process;


    ap_block_state6_pp0_stage0_iter5_assign_proc : process(regslice_both_fcw_out_V_data_V_U_apdone_blk, fcw_out_TREADY_int_regslice)
    begin
                ap_block_state6_pp0_stage0_iter5 <= ((regslice_both_fcw_out_V_data_V_U_apdone_blk = ap_const_logic_1) or (fcw_out_TREADY_int_regslice = ap_const_logic_0));
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_const_logic_1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_history_loc_0_phi_fu_120_p4_assign_proc : process(history, or_ln_fu_157_p3, ap_phi_reg_pp0_iter0_history_loc_0_reg_117, icmp_ln39_fu_142_p2)
    begin
        if ((icmp_ln39_fu_142_p2 = ap_const_lv1_0)) then 
            ap_phi_mux_history_loc_0_phi_fu_120_p4 <= history;
        elsif ((icmp_ln39_fu_142_p2 = ap_const_lv1_1)) then 
            ap_phi_mux_history_loc_0_phi_fu_120_p4 <= or_ln_fu_157_p3;
        else 
            ap_phi_mux_history_loc_0_phi_fu_120_p4 <= ap_phi_reg_pp0_iter0_history_loc_0_reg_117;
        end if; 
    end process;

    ap_phi_reg_pp0_iter0_history_loc_0_reg_117 <= "XXX";
    ap_reset_idle_pp0 <= ap_const_logic_0;

    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    current_fcw_fu_187_p2 <= std_logic_vector(signed(sext_ln48_fu_183_p1) + signed(ap_const_lv27_42AAAAA));

    fcw_out_TDATA_blk_n_assign_proc : process(ap_block_pp0_stage0, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, fcw_out_TREADY_int_regslice)
    begin
        if ((((ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0)) or ((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0)))) then 
            fcw_out_TDATA_blk_n <= fcw_out_TREADY_int_regslice;
        else 
            fcw_out_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    fcw_out_TDATA_int_regslice <= std_logic_vector(IEEE.numeric_std.resize(unsigned(current_fcw_fu_187_p2),32));
    fcw_out_TVALID <= regslice_both_fcw_out_V_data_V_U_vld_out;

    fcw_out_TVALID_int_regslice_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            fcw_out_TVALID_int_regslice <= ap_const_logic_1;
        else 
            fcw_out_TVALID_int_regslice <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_198_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_198_ce <= ap_const_logic_1;
        else 
            grp_fu_198_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_198_p0 <= grp_fu_198_p00(3 - 1 downto 0);
    grp_fu_198_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_phi_mux_history_loc_0_phi_fu_120_p4),16));
    grp_fu_198_p1 <= ap_const_lv16_1900(13 - 1 downto 0);
    grp_fu_198_p2 <= grp_fu_198_p20(13 - 1 downto 0);
    grp_fu_198_p20 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(input_pkt_user_V_reg_207_pp0_iter1_reg),16));
    icmp_ln39_fu_142_p2 <= "1" when (in_stream_TUSER_int_regslice = ap_const_lv13_0) else "0";

    in_stream_TDATA_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, in_stream_TVALID_int_regslice)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            in_stream_TDATA_blk_n <= in_stream_TVALID_int_regslice;
        else 
            in_stream_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    in_stream_TREADY <= regslice_both_in_stream_V_data_V_U_ack_in;

    in_stream_TREADY_int_regslice_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            in_stream_TREADY_int_regslice <= ap_const_logic_1;
        else 
            in_stream_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    or_ln_fu_157_p3 <= (trunc_ln40_fu_153_p1 & trunc_ln34_fu_138_p1);
        sext_ln48_fu_183_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(GAUSS_LUT_q0),27));

    trunc_ln34_fu_138_p1 <= in_stream_TDATA_int_regslice(1 - 1 downto 0);
    trunc_ln40_fu_153_p1 <= history(2 - 1 downto 0);
    zext_ln45_2_fu_179_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(grp_fu_198_p3),64));
end behav;
