// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="fsk_scrambler_fsk_scrambler,hls_ip_2023_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=pipeline,HLS_SYN_CLOCK=1.679500,HLS_SYN_LAT=2,HLS_SYN_TPT=1,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=37,HLS_SYN_LUT=42,HLS_VERSION=2023_1}" *)

module fsk_scrambler (
        ap_clk,
        ap_rst_n,
        in_stream_TDATA,
        in_stream_TVALID,
        in_stream_TREADY,
        in_stream_TKEEP,
        in_stream_TSTRB,
        in_stream_TUSER,
        in_stream_TLAST,
        in_stream_TID,
        in_stream_TDEST,
        out_stream_TDATA,
        out_stream_TVALID,
        out_stream_TREADY,
        out_stream_TKEEP,
        out_stream_TSTRB,
        out_stream_TUSER,
        out_stream_TLAST,
        out_stream_TID,
        out_stream_TDEST
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst_n;
input  [7:0] in_stream_TDATA;
input   in_stream_TVALID;
output   in_stream_TREADY;
input  [0:0] in_stream_TKEEP;
input  [0:0] in_stream_TSTRB;
input  [12:0] in_stream_TUSER;
input  [0:0] in_stream_TLAST;
input  [0:0] in_stream_TID;
input  [0:0] in_stream_TDEST;
output  [7:0] out_stream_TDATA;
output   out_stream_TVALID;
input   out_stream_TREADY;
output  [0:0] out_stream_TKEEP;
output  [0:0] out_stream_TSTRB;
output  [12:0] out_stream_TUSER;
output  [0:0] out_stream_TLAST;
output  [0:0] out_stream_TID;
output  [0:0] out_stream_TDEST;

 reg    ap_rst_n_inv;
reg   [6:0] lfsr;
reg   [0:0] current_scramble_bit;
reg    in_stream_TDATA_blk_n;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_block_pp0_stage0;
reg    out_stream_TDATA_blk_n;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg   [7:0] in_pkt_data_V_reg_240;
reg    ap_block_state1_pp0_stage0_iter0;
reg    ap_block_state2_pp0_stage0_iter1;
wire    regslice_both_out_stream_V_data_V_U_apdone_blk;
reg    ap_block_state3_pp0_stage0_iter2;
reg    ap_block_pp0_stage0_11001;
reg   [0:0] in_pkt_keep_V_reg_246;
reg   [0:0] in_pkt_strb_V_reg_251;
reg   [12:0] in_pkt_user_V_reg_256;
reg   [0:0] in_pkt_last_V_reg_261;
reg   [0:0] in_pkt_id_V_reg_266;
reg   [0:0] in_pkt_dest_V_reg_271;
reg    ap_block_pp0_stage0_subdone;
wire   [6:0] or_ln_fu_195_p3;
wire   [0:0] icmp_ln39_fu_153_p2;
wire   [0:0] feedback_fu_179_p2;
reg    ap_block_pp0_stage0_01001;
wire   [0:0] tmp_2_fu_171_p3;
wire   [0:0] tmp_fu_163_p3;
wire   [5:0] trunc_ln49_fu_191_p1;
wire   [0:0] trunc_ln56_fu_213_p1;
wire   [6:0] tmp_1_fu_222_p4;
wire   [0:0] scrambled_bit_fu_216_p2;
reg   [0:0] ap_NS_fsm;
wire    ap_reset_idle_pp0;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
wire    regslice_both_in_stream_V_data_V_U_apdone_blk;
wire   [7:0] in_stream_TDATA_int_regslice;
wire    in_stream_TVALID_int_regslice;
reg    in_stream_TREADY_int_regslice;
wire    regslice_both_in_stream_V_data_V_U_ack_in;
wire    regslice_both_in_stream_V_keep_V_U_apdone_blk;
wire   [0:0] in_stream_TKEEP_int_regslice;
wire    regslice_both_in_stream_V_keep_V_U_vld_out;
wire    regslice_both_in_stream_V_keep_V_U_ack_in;
wire    regslice_both_in_stream_V_strb_V_U_apdone_blk;
wire   [0:0] in_stream_TSTRB_int_regslice;
wire    regslice_both_in_stream_V_strb_V_U_vld_out;
wire    regslice_both_in_stream_V_strb_V_U_ack_in;
wire    regslice_both_in_stream_V_user_V_U_apdone_blk;
wire   [12:0] in_stream_TUSER_int_regslice;
wire    regslice_both_in_stream_V_user_V_U_vld_out;
wire    regslice_both_in_stream_V_user_V_U_ack_in;
wire    regslice_both_in_stream_V_last_V_U_apdone_blk;
wire   [0:0] in_stream_TLAST_int_regslice;
wire    regslice_both_in_stream_V_last_V_U_vld_out;
wire    regslice_both_in_stream_V_last_V_U_ack_in;
wire    regslice_both_in_stream_V_id_V_U_apdone_blk;
wire   [0:0] in_stream_TID_int_regslice;
wire    regslice_both_in_stream_V_id_V_U_vld_out;
wire    regslice_both_in_stream_V_id_V_U_ack_in;
wire    regslice_both_in_stream_V_dest_V_U_apdone_blk;
wire   [0:0] in_stream_TDEST_int_regslice;
wire    regslice_both_in_stream_V_dest_V_U_vld_out;
wire    regslice_both_in_stream_V_dest_V_U_ack_in;
wire   [7:0] out_stream_TDATA_int_regslice;
reg    out_stream_TVALID_int_regslice;
wire    out_stream_TREADY_int_regslice;
wire    regslice_both_out_stream_V_data_V_U_vld_out;
wire    regslice_both_out_stream_V_keep_V_U_apdone_blk;
wire    regslice_both_out_stream_V_keep_V_U_ack_in_dummy;
wire    regslice_both_out_stream_V_keep_V_U_vld_out;
wire    regslice_both_out_stream_V_strb_V_U_apdone_blk;
wire    regslice_both_out_stream_V_strb_V_U_ack_in_dummy;
wire    regslice_both_out_stream_V_strb_V_U_vld_out;
wire    regslice_both_out_stream_V_user_V_U_apdone_blk;
wire    regslice_both_out_stream_V_user_V_U_ack_in_dummy;
wire    regslice_both_out_stream_V_user_V_U_vld_out;
wire    regslice_both_out_stream_V_last_V_U_apdone_blk;
wire    regslice_both_out_stream_V_last_V_U_ack_in_dummy;
wire    regslice_both_out_stream_V_last_V_U_vld_out;
wire    regslice_both_out_stream_V_id_V_U_apdone_blk;
wire    regslice_both_out_stream_V_id_V_U_ack_in_dummy;
wire    regslice_both_out_stream_V_id_V_U_vld_out;
wire    regslice_both_out_stream_V_dest_V_U_apdone_blk;
wire    regslice_both_out_stream_V_dest_V_U_ack_in_dummy;
wire    regslice_both_out_stream_V_dest_V_U_vld_out;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 lfsr = 7'd127;
#0 current_scramble_bit = 1'd0;
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
end

fsk_scrambler_regslice_both #(
    .DataWidth( 8 ))
regslice_both_in_stream_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_stream_TDATA),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_data_V_U_ack_in),
    .data_out(in_stream_TDATA_int_regslice),
    .vld_out(in_stream_TVALID_int_regslice),
    .ack_out(in_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_stream_V_data_V_U_apdone_blk)
);

fsk_scrambler_regslice_both #(
    .DataWidth( 1 ))
regslice_both_in_stream_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_stream_TKEEP),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_keep_V_U_ack_in),
    .data_out(in_stream_TKEEP_int_regslice),
    .vld_out(regslice_both_in_stream_V_keep_V_U_vld_out),
    .ack_out(in_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_stream_V_keep_V_U_apdone_blk)
);

fsk_scrambler_regslice_both #(
    .DataWidth( 1 ))
regslice_both_in_stream_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_stream_TSTRB),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_strb_V_U_ack_in),
    .data_out(in_stream_TSTRB_int_regslice),
    .vld_out(regslice_both_in_stream_V_strb_V_U_vld_out),
    .ack_out(in_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_stream_V_strb_V_U_apdone_blk)
);

fsk_scrambler_regslice_both #(
    .DataWidth( 13 ))
regslice_both_in_stream_V_user_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_stream_TUSER),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_user_V_U_ack_in),
    .data_out(in_stream_TUSER_int_regslice),
    .vld_out(regslice_both_in_stream_V_user_V_U_vld_out),
    .ack_out(in_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_stream_V_user_V_U_apdone_blk)
);

fsk_scrambler_regslice_both #(
    .DataWidth( 1 ))
regslice_both_in_stream_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_stream_TLAST),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_last_V_U_ack_in),
    .data_out(in_stream_TLAST_int_regslice),
    .vld_out(regslice_both_in_stream_V_last_V_U_vld_out),
    .ack_out(in_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_stream_V_last_V_U_apdone_blk)
);

fsk_scrambler_regslice_both #(
    .DataWidth( 1 ))
regslice_both_in_stream_V_id_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_stream_TID),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_id_V_U_ack_in),
    .data_out(in_stream_TID_int_regslice),
    .vld_out(regslice_both_in_stream_V_id_V_U_vld_out),
    .ack_out(in_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_stream_V_id_V_U_apdone_blk)
);

fsk_scrambler_regslice_both #(
    .DataWidth( 1 ))
regslice_both_in_stream_V_dest_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_stream_TDEST),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_dest_V_U_ack_in),
    .data_out(in_stream_TDEST_int_regslice),
    .vld_out(regslice_both_in_stream_V_dest_V_U_vld_out),
    .ack_out(in_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_stream_V_dest_V_U_apdone_blk)
);

fsk_scrambler_regslice_both #(
    .DataWidth( 8 ))
regslice_both_out_stream_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(out_stream_TDATA_int_regslice),
    .vld_in(out_stream_TVALID_int_regslice),
    .ack_in(out_stream_TREADY_int_regslice),
    .data_out(out_stream_TDATA),
    .vld_out(regslice_both_out_stream_V_data_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_data_V_U_apdone_blk)
);

fsk_scrambler_regslice_both #(
    .DataWidth( 1 ))
regslice_both_out_stream_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_pkt_keep_V_reg_246),
    .vld_in(out_stream_TVALID_int_regslice),
    .ack_in(regslice_both_out_stream_V_keep_V_U_ack_in_dummy),
    .data_out(out_stream_TKEEP),
    .vld_out(regslice_both_out_stream_V_keep_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_keep_V_U_apdone_blk)
);

fsk_scrambler_regslice_both #(
    .DataWidth( 1 ))
regslice_both_out_stream_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_pkt_strb_V_reg_251),
    .vld_in(out_stream_TVALID_int_regslice),
    .ack_in(regslice_both_out_stream_V_strb_V_U_ack_in_dummy),
    .data_out(out_stream_TSTRB),
    .vld_out(regslice_both_out_stream_V_strb_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_strb_V_U_apdone_blk)
);

fsk_scrambler_regslice_both #(
    .DataWidth( 13 ))
regslice_both_out_stream_V_user_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_pkt_user_V_reg_256),
    .vld_in(out_stream_TVALID_int_regslice),
    .ack_in(regslice_both_out_stream_V_user_V_U_ack_in_dummy),
    .data_out(out_stream_TUSER),
    .vld_out(regslice_both_out_stream_V_user_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_user_V_U_apdone_blk)
);

fsk_scrambler_regslice_both #(
    .DataWidth( 1 ))
regslice_both_out_stream_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_pkt_last_V_reg_261),
    .vld_in(out_stream_TVALID_int_regslice),
    .ack_in(regslice_both_out_stream_V_last_V_U_ack_in_dummy),
    .data_out(out_stream_TLAST),
    .vld_out(regslice_both_out_stream_V_last_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_last_V_U_apdone_blk)
);

fsk_scrambler_regslice_both #(
    .DataWidth( 1 ))
regslice_both_out_stream_V_id_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_pkt_id_V_reg_266),
    .vld_in(out_stream_TVALID_int_regslice),
    .ack_in(regslice_both_out_stream_V_id_V_U_ack_in_dummy),
    .data_out(out_stream_TID),
    .vld_out(regslice_both_out_stream_V_id_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_id_V_U_apdone_blk)
);

fsk_scrambler_regslice_both #(
    .DataWidth( 1 ))
regslice_both_out_stream_V_dest_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_pkt_dest_V_reg_271),
    .vld_in(out_stream_TVALID_int_regslice),
    .ack_in(regslice_both_out_stream_V_dest_V_U_ack_in_dummy),
    .data_out(out_stream_TDEST),
    .vld_out(regslice_both_out_stream_V_dest_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_dest_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln39_fu_153_p2 == 1'd1))) begin
        current_scramble_bit <= feedback_fu_179_p2;
        lfsr <= or_ln_fu_195_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_pkt_data_V_reg_240 <= in_stream_TDATA_int_regslice;
        in_pkt_dest_V_reg_271 <= in_stream_TDEST_int_regslice;
        in_pkt_id_V_reg_266 <= in_stream_TID_int_regslice;
        in_pkt_keep_V_reg_246 <= in_stream_TKEEP_int_regslice;
        in_pkt_last_V_reg_261 <= in_stream_TLAST_int_regslice;
        in_pkt_strb_V_reg_251 <= in_stream_TSTRB_int_regslice;
        in_pkt_user_V_reg_256 <= in_stream_TUSER_int_regslice;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (1'b1 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

assign ap_reset_idle_pp0 = 1'b0;

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_stream_TDATA_blk_n = in_stream_TVALID_int_regslice;
    end else begin
        in_stream_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_stream_TREADY_int_regslice = 1'b1;
    end else begin
        in_stream_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        out_stream_TDATA_blk_n = out_stream_TREADY_int_regslice;
    end else begin
        out_stream_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        out_stream_TVALID_int_regslice = 1'b1;
    end else begin
        out_stream_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((ap_enable_reg_pp0_iter2 == 1'b1) & ((regslice_both_out_stream_V_data_V_U_apdone_blk == 1'b1) | (out_stream_TREADY_int_regslice == 1'b0))) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (out_stream_TREADY_int_regslice == 1'b0)) | ((1'b1 == 1'b1) & (in_stream_TVALID_int_regslice == 1'b0)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter2 == 1'b1) & ((regslice_both_out_stream_V_data_V_U_apdone_blk == 1'b1) | (out_stream_TREADY_int_regslice == 1'b0))) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (out_stream_TREADY_int_regslice == 1'b0)) | ((1'b1 == 1'b1) & (in_stream_TVALID_int_regslice == 1'b0)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter2 == 1'b1) & ((regslice_both_out_stream_V_data_V_U_apdone_blk == 1'b1) | (out_stream_TREADY_int_regslice == 1'b0))) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (out_stream_TREADY_int_regslice == 1'b0)) | ((1'b1 == 1'b1) & (in_stream_TVALID_int_regslice == 1'b0)));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (in_stream_TVALID_int_regslice == 1'b0);
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = (out_stream_TREADY_int_regslice == 1'b0);
end

always @ (*) begin
    ap_block_state3_pp0_stage0_iter2 = ((regslice_both_out_stream_V_data_V_U_apdone_blk == 1'b1) | (out_stream_TREADY_int_regslice == 1'b0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign feedback_fu_179_p2 = (tmp_fu_163_p3 ^ tmp_2_fu_171_p3);

assign icmp_ln39_fu_153_p2 = ((in_stream_TUSER_int_regslice == 13'd0) ? 1'b1 : 1'b0);

assign in_stream_TREADY = regslice_both_in_stream_V_data_V_U_ack_in;

assign or_ln_fu_195_p3 = {{trunc_ln49_fu_191_p1}, {feedback_fu_179_p2}};

assign out_stream_TDATA_int_regslice = {{tmp_1_fu_222_p4}, {scrambled_bit_fu_216_p2}};

assign out_stream_TVALID = regslice_both_out_stream_V_data_V_U_vld_out;

assign scrambled_bit_fu_216_p2 = (trunc_ln56_fu_213_p1 ^ current_scramble_bit);

assign tmp_1_fu_222_p4 = {{in_pkt_data_V_reg_240[7:1]}};

assign tmp_2_fu_171_p3 = lfsr[32'd6];

assign tmp_fu_163_p3 = lfsr[32'd3];

assign trunc_ln49_fu_191_p1 = lfsr[5:0];

assign trunc_ln56_fu_213_p1 = in_pkt_data_V_reg_240[0:0];


reg find_kernel_block = 0;
// synthesis translate_off
`include "fsk_scrambler_hls_deadlock_kernel_monitor_top.vh"
// synthesis translate_on

endmodule //fsk_scrambler

