// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="fsk_phase_corrector_fsk_phase_corrector,hls_ip_2023_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=pipeline,HLS_SYN_CLOCK=6.912000,HLS_SYN_LAT=4,HLS_SYN_TPT=1,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=785,HLS_SYN_LUT=543,HLS_VERSION=2023_1}" *)

module fsk_phase_corrector (
        ap_clk,
        ap_rst_n,
        in_stream_TDATA,
        in_stream_TVALID,
        in_stream_TREADY,
        in_stream_TKEEP,
        in_stream_TSTRB,
        in_stream_TLAST,
        out_stream_TDATA,
        out_stream_TVALID,
        out_stream_TREADY,
        out_stream_TKEEP,
        out_stream_TSTRB,
        out_stream_TLAST
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst_n;
input  [31:0] in_stream_TDATA;
input   in_stream_TVALID;
output   in_stream_TREADY;
input  [3:0] in_stream_TKEEP;
input  [3:0] in_stream_TSTRB;
input  [0:0] in_stream_TLAST;
output  [31:0] out_stream_TDATA;
output   out_stream_TVALID;
input   out_stream_TREADY;
output  [3:0] out_stream_TKEEP;
output  [3:0] out_stream_TSTRB;
output  [0:0] out_stream_TLAST;

 reg    ap_rst_n_inv;
reg   [0:0] calibrated;
reg   [31:0] sum;
reg   [31:0] counter;
reg   [15:0] dc_offset;
reg    in_stream_TDATA_blk_n;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_block_pp0_stage0;
reg    out_stream_TDATA_blk_n;
reg    ap_enable_reg_pp0_iter3;
reg   [0:0] calibrated_load_reg_279;
reg   [0:0] calibrated_load_reg_279_pp0_iter2_reg;
reg    ap_enable_reg_pp0_iter4;
reg   [0:0] calibrated_load_reg_279_pp0_iter3_reg;
reg   [3:0] pkt_in_keep_V_reg_259;
reg    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
reg    ap_block_state4_pp0_stage0_iter3;
reg    ap_block_state4_io;
wire    regslice_both_out_stream_V_data_V_U_apdone_blk;
reg    ap_block_state5_pp0_stage0_iter4;
reg    ap_block_state5_io;
reg    ap_block_pp0_stage0_11001;
reg   [3:0] pkt_in_keep_V_reg_259_pp0_iter1_reg;
reg   [3:0] pkt_in_keep_V_reg_259_pp0_iter2_reg;
reg   [3:0] pkt_in_strb_V_reg_264;
reg   [3:0] pkt_in_strb_V_reg_264_pp0_iter1_reg;
reg   [3:0] pkt_in_strb_V_reg_264_pp0_iter2_reg;
reg   [0:0] pkt_in_last_V_reg_269;
reg   [0:0] pkt_in_last_V_reg_269_pp0_iter1_reg;
reg   [0:0] pkt_in_last_V_reg_269_pp0_iter2_reg;
wire  signed [15:0] val_in_fu_129_p1;
reg  signed [15:0] val_in_reg_274;
reg  signed [15:0] val_in_reg_274_pp0_iter1_reg;
reg  signed [15:0] val_in_reg_274_pp0_iter2_reg;
wire   [0:0] calibrated_load_load_fu_133_p1;
reg   [0:0] calibrated_load_reg_279_pp0_iter1_reg;
wire  signed [31:0] add_ln32_fu_145_p2;
reg  signed [31:0] add_ln32_reg_283;
wire   [0:0] icmp_ln35_fu_173_p2;
reg   [0:0] icmp_ln35_reg_289;
reg   [0:0] icmp_ln35_reg_289_pp0_iter1_reg;
reg   [0:0] icmp_ln35_reg_289_pp0_iter2_reg;
reg   [0:0] tmp_reg_298;
reg   [0:0] tmp_reg_298_pp0_iter2_reg;
wire   [64:0] grp_fu_108_p2;
reg   [64:0] mul_ln39_reg_304;
reg   [15:0] tmp_2_reg_309;
reg    ap_enable_reg_pp0_iter1;
reg    ap_block_pp0_stage0_subdone;
reg    ap_enable_reg_pp0_iter2;
wire   [31:0] add_ln33_fu_161_p2;
wire   [15:0] select_ln39_1_fu_233_p3;
reg    ap_block_pp0_stage0_01001;
wire   [33:0] grp_fu_108_p1;
wire  signed [31:0] sext_ln32_fu_137_p1;
wire   [64:0] sub_ln39_fu_206_p2;
wire   [15:0] tmp_1_fu_211_p4;
wire   [15:0] select_ln39_fu_221_p3;
wire   [15:0] sub_ln39_1_fu_227_p2;
wire   [15:0] val_corrected_fu_249_p2;
reg    grp_fu_108_ce;
reg   [0:0] ap_NS_fsm;
wire    ap_reset_idle_pp0;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
wire    regslice_both_in_stream_V_data_V_U_apdone_blk;
wire   [31:0] in_stream_TDATA_int_regslice;
wire    in_stream_TVALID_int_regslice;
reg    in_stream_TREADY_int_regslice;
wire    regslice_both_in_stream_V_data_V_U_ack_in;
wire    regslice_both_in_stream_V_keep_V_U_apdone_blk;
wire   [3:0] in_stream_TKEEP_int_regslice;
wire    regslice_both_in_stream_V_keep_V_U_vld_out;
wire    regslice_both_in_stream_V_keep_V_U_ack_in;
wire    regslice_both_in_stream_V_strb_V_U_apdone_blk;
wire   [3:0] in_stream_TSTRB_int_regslice;
wire    regslice_both_in_stream_V_strb_V_U_vld_out;
wire    regslice_both_in_stream_V_strb_V_U_ack_in;
wire    regslice_both_in_stream_V_last_V_U_apdone_blk;
wire   [0:0] in_stream_TLAST_int_regslice;
wire    regslice_both_in_stream_V_last_V_U_vld_out;
wire    regslice_both_in_stream_V_last_V_U_ack_in;
wire   [31:0] out_stream_TDATA_int_regslice;
reg    out_stream_TVALID_int_regslice;
wire    out_stream_TREADY_int_regslice;
wire    regslice_both_out_stream_V_data_V_U_vld_out;
wire    regslice_both_out_stream_V_keep_V_U_apdone_blk;
wire    regslice_both_out_stream_V_keep_V_U_ack_in_dummy;
wire    regslice_both_out_stream_V_keep_V_U_vld_out;
wire    regslice_both_out_stream_V_strb_V_U_apdone_blk;
wire    regslice_both_out_stream_V_strb_V_U_ack_in_dummy;
wire    regslice_both_out_stream_V_strb_V_U_vld_out;
wire    regslice_both_out_stream_V_last_V_U_apdone_blk;
wire    regslice_both_out_stream_V_last_V_U_ack_in_dummy;
wire    regslice_both_out_stream_V_last_V_U_vld_out;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 calibrated = 1'd0;
#0 sum = 32'd0;
#0 counter = 32'd0;
#0 dc_offset = 16'd0;
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
end

fsk_phase_corrector_mul_32s_34ns_65_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 34 ),
    .dout_WIDTH( 65 ))
mul_32s_34ns_65_2_1_U1(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(add_ln32_reg_283),
    .din1(grp_fu_108_p1),
    .ce(grp_fu_108_ce),
    .dout(grp_fu_108_p2)
);

fsk_phase_corrector_regslice_both #(
    .DataWidth( 32 ))
regslice_both_in_stream_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_stream_TDATA),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_data_V_U_ack_in),
    .data_out(in_stream_TDATA_int_regslice),
    .vld_out(in_stream_TVALID_int_regslice),
    .ack_out(in_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_stream_V_data_V_U_apdone_blk)
);

fsk_phase_corrector_regslice_both #(
    .DataWidth( 4 ))
regslice_both_in_stream_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_stream_TKEEP),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_keep_V_U_ack_in),
    .data_out(in_stream_TKEEP_int_regslice),
    .vld_out(regslice_both_in_stream_V_keep_V_U_vld_out),
    .ack_out(in_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_stream_V_keep_V_U_apdone_blk)
);

fsk_phase_corrector_regslice_both #(
    .DataWidth( 4 ))
regslice_both_in_stream_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_stream_TSTRB),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_strb_V_U_ack_in),
    .data_out(in_stream_TSTRB_int_regslice),
    .vld_out(regslice_both_in_stream_V_strb_V_U_vld_out),
    .ack_out(in_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_stream_V_strb_V_U_apdone_blk)
);

fsk_phase_corrector_regslice_both #(
    .DataWidth( 1 ))
regslice_both_in_stream_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_stream_TLAST),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_last_V_U_ack_in),
    .data_out(in_stream_TLAST_int_regslice),
    .vld_out(regslice_both_in_stream_V_last_V_U_vld_out),
    .ack_out(in_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_stream_V_last_V_U_apdone_blk)
);

fsk_phase_corrector_regslice_both #(
    .DataWidth( 32 ))
regslice_both_out_stream_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(out_stream_TDATA_int_regslice),
    .vld_in(out_stream_TVALID_int_regslice),
    .ack_in(out_stream_TREADY_int_regslice),
    .data_out(out_stream_TDATA),
    .vld_out(regslice_both_out_stream_V_data_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_data_V_U_apdone_blk)
);

fsk_phase_corrector_regslice_both #(
    .DataWidth( 4 ))
regslice_both_out_stream_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(pkt_in_keep_V_reg_259_pp0_iter2_reg),
    .vld_in(out_stream_TVALID_int_regslice),
    .ack_in(regslice_both_out_stream_V_keep_V_U_ack_in_dummy),
    .data_out(out_stream_TKEEP),
    .vld_out(regslice_both_out_stream_V_keep_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_keep_V_U_apdone_blk)
);

fsk_phase_corrector_regslice_both #(
    .DataWidth( 4 ))
regslice_both_out_stream_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(pkt_in_strb_V_reg_264_pp0_iter2_reg),
    .vld_in(out_stream_TVALID_int_regslice),
    .ack_in(regslice_both_out_stream_V_strb_V_U_ack_in_dummy),
    .data_out(out_stream_TSTRB),
    .vld_out(regslice_both_out_stream_V_strb_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_strb_V_U_apdone_blk)
);

fsk_phase_corrector_regslice_both #(
    .DataWidth( 1 ))
regslice_both_out_stream_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(pkt_in_last_V_reg_269_pp0_iter2_reg),
    .vld_in(out_stream_TVALID_int_regslice),
    .ack_in(regslice_both_out_stream_V_last_V_U_ack_in_dummy),
    .data_out(out_stream_TLAST),
    .vld_out(regslice_both_out_stream_V_last_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_last_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (calibrated_load_load_fu_133_p1 == 1'd0))) begin
        add_ln32_reg_283 <= add_ln32_fu_145_p2;
        icmp_ln35_reg_289 <= icmp_ln35_fu_173_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln35_fu_173_p2 == 1'd1) & (calibrated_load_load_fu_133_p1 == 1'd0))) begin
        calibrated <= 1'd1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        calibrated_load_reg_279 <= calibrated;
        calibrated_load_reg_279_pp0_iter1_reg <= calibrated_load_reg_279;
        icmp_ln35_reg_289_pp0_iter1_reg <= icmp_ln35_reg_289;
        pkt_in_keep_V_reg_259 <= in_stream_TKEEP_int_regslice;
        pkt_in_keep_V_reg_259_pp0_iter1_reg <= pkt_in_keep_V_reg_259;
        pkt_in_last_V_reg_269 <= in_stream_TLAST_int_regslice;
        pkt_in_last_V_reg_269_pp0_iter1_reg <= pkt_in_last_V_reg_269;
        pkt_in_strb_V_reg_264 <= in_stream_TSTRB_int_regslice;
        pkt_in_strb_V_reg_264_pp0_iter1_reg <= pkt_in_strb_V_reg_264;
        val_in_reg_274 <= val_in_fu_129_p1;
        val_in_reg_274_pp0_iter1_reg <= val_in_reg_274;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        calibrated_load_reg_279_pp0_iter2_reg <= calibrated_load_reg_279_pp0_iter1_reg;
        calibrated_load_reg_279_pp0_iter3_reg <= calibrated_load_reg_279_pp0_iter2_reg;
        icmp_ln35_reg_289_pp0_iter2_reg <= icmp_ln35_reg_289_pp0_iter1_reg;
        pkt_in_keep_V_reg_259_pp0_iter2_reg <= pkt_in_keep_V_reg_259_pp0_iter1_reg;
        pkt_in_last_V_reg_269_pp0_iter2_reg <= pkt_in_last_V_reg_269_pp0_iter1_reg;
        pkt_in_strb_V_reg_264_pp0_iter2_reg <= pkt_in_strb_V_reg_264_pp0_iter1_reg;
        tmp_reg_298_pp0_iter2_reg <= tmp_reg_298;
        val_in_reg_274_pp0_iter2_reg <= val_in_reg_274_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (calibrated_load_load_fu_133_p1 == 1'd0))) begin
        counter <= add_ln33_fu_161_p2;
        sum <= add_ln32_fu_145_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((calibrated_load_reg_279_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln35_reg_289_pp0_iter2_reg == 1'd1))) begin
        dc_offset <= select_ln39_1_fu_233_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln35_reg_289_pp0_iter1_reg == 1'd1) & (calibrated_load_reg_279_pp0_iter1_reg == 1'd0))) begin
        mul_ln39_reg_304 <= grp_fu_108_p2;
        tmp_2_reg_309 <= {{grp_fu_108_p2[57:42]}};
    end
end

always @ (posedge ap_clk) begin
    if (((calibrated_load_reg_279 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln35_reg_289 == 1'd1))) begin
        tmp_reg_298 <= add_ln32_reg_283[32'd31];
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (1'b1 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

assign ap_reset_idle_pp0 = 1'b0;

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_108_ce = 1'b1;
    end else begin
        grp_fu_108_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_stream_TDATA_blk_n = in_stream_TVALID_int_regslice;
    end else begin
        in_stream_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_stream_TREADY_int_regslice = 1'b1;
    end else begin
        in_stream_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((((calibrated_load_reg_279_pp0_iter3_reg == 1'd1) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0)) | ((calibrated_load_reg_279_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0)))) begin
        out_stream_TDATA_blk_n = out_stream_TREADY_int_regslice;
    end else begin
        out_stream_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((calibrated_load_reg_279_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        out_stream_TVALID_int_regslice = 1'b1;
    end else begin
        out_stream_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln32_fu_145_p2 = ($signed(sum) + $signed(sext_ln32_fu_137_p1));

assign add_ln33_fu_161_p2 = (counter + 32'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((ap_enable_reg_pp0_iter4 == 1'b1) & ((regslice_both_out_stream_V_data_V_U_apdone_blk == 1'b1) | ((calibrated_load_reg_279_pp0_iter3_reg == 1'd1) & (out_stream_TREADY_int_regslice == 1'b0)))) | ((calibrated_load_reg_279_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (out_stream_TREADY_int_regslice == 1'b0)) | ((1'b1 == 1'b1) & (in_stream_TVALID_int_regslice == 1'b0)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter4 == 1'b1) & ((regslice_both_out_stream_V_data_V_U_apdone_blk == 1'b1) | (1'b1 == ap_block_state5_io) | ((calibrated_load_reg_279_pp0_iter3_reg == 1'd1) & (out_stream_TREADY_int_regslice == 1'b0)))) | ((ap_enable_reg_pp0_iter3 == 1'b1) & ((1'b1 == ap_block_state4_io) | ((calibrated_load_reg_279_pp0_iter2_reg == 1'd1) & (out_stream_TREADY_int_regslice == 1'b0)))) | ((1'b1 == 1'b1) & (in_stream_TVALID_int_regslice == 1'b0)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter4 == 1'b1) & ((regslice_both_out_stream_V_data_V_U_apdone_blk == 1'b1) | (1'b1 == ap_block_state5_io) | ((calibrated_load_reg_279_pp0_iter3_reg == 1'd1) & (out_stream_TREADY_int_regslice == 1'b0)))) | ((ap_enable_reg_pp0_iter3 == 1'b1) & ((1'b1 == ap_block_state4_io) | ((calibrated_load_reg_279_pp0_iter2_reg == 1'd1) & (out_stream_TREADY_int_regslice == 1'b0)))) | ((1'b1 == 1'b1) & (in_stream_TVALID_int_regslice == 1'b0)));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (in_stream_TVALID_int_regslice == 1'b0);
end

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state4_io = ((calibrated_load_reg_279_pp0_iter2_reg == 1'd1) & (out_stream_TREADY_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_state4_pp0_stage0_iter3 = ((calibrated_load_reg_279_pp0_iter2_reg == 1'd1) & (out_stream_TREADY_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_state5_io = ((calibrated_load_reg_279_pp0_iter3_reg == 1'd1) & (out_stream_TREADY_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_state5_pp0_stage0_iter4 = ((regslice_both_out_stream_V_data_V_U_apdone_blk == 1'b1) | ((calibrated_load_reg_279_pp0_iter3_reg == 1'd1) & (out_stream_TREADY_int_regslice == 1'b0)));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign calibrated_load_load_fu_133_p1 = calibrated;

assign grp_fu_108_p1 = 65'd5497558139;

assign icmp_ln35_fu_173_p2 = ((add_ln33_fu_161_p2 == 32'd800) ? 1'b1 : 1'b0);

assign in_stream_TREADY = regslice_both_in_stream_V_data_V_U_ack_in;

assign out_stream_TDATA_int_regslice = $signed(val_corrected_fu_249_p2);

assign out_stream_TVALID = regslice_both_out_stream_V_data_V_U_vld_out;

assign select_ln39_1_fu_233_p3 = ((tmp_reg_298_pp0_iter2_reg[0:0] == 1'b1) ? sub_ln39_1_fu_227_p2 : tmp_2_reg_309);

assign select_ln39_fu_221_p3 = ((tmp_reg_298_pp0_iter2_reg[0:0] == 1'b1) ? tmp_1_fu_211_p4 : tmp_2_reg_309);

assign sext_ln32_fu_137_p1 = val_in_fu_129_p1;

assign sub_ln39_1_fu_227_p2 = (16'd0 - select_ln39_fu_221_p3);

assign sub_ln39_fu_206_p2 = (65'd0 - mul_ln39_reg_304);

assign tmp_1_fu_211_p4 = {{sub_ln39_fu_206_p2[57:42]}};

assign val_corrected_fu_249_p2 = ($signed(val_in_reg_274_pp0_iter2_reg) - $signed(dc_offset));

assign val_in_fu_129_p1 = in_stream_TDATA_int_regslice[15:0];


reg find_kernel_block = 0;
// synthesis translate_off
`include "fsk_phase_corrector_hls_deadlock_kernel_monitor_top.vh"
// synthesis translate_on

endmodule //fsk_phase_corrector

