// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="fsk_ddc_fsk_ddc,hls_ip_2023_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=pipeline,HLS_SYN_CLOCK=5.580000,HLS_SYN_LAT=4,HLS_SYN_TPT=1,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=262,HLS_SYN_LUT=111,HLS_VERSION=2023_1}" *)

module fsk_ddc (
        ap_clk,
        ap_rst_n,
        rx_in_TDATA,
        rx_in_TVALID,
        rx_in_TREADY,
        rx_in_TKEEP,
        rx_in_TSTRB,
        rx_in_TLAST,
        dds_lo_TDATA,
        dds_lo_TVALID,
        dds_lo_TREADY,
        dds_lo_TKEEP,
        dds_lo_TSTRB,
        dds_lo_TLAST,
        baseband_out_TDATA,
        baseband_out_TVALID,
        baseband_out_TREADY,
        baseband_out_TKEEP,
        baseband_out_TSTRB,
        baseband_out_TLAST
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst_n;
input  [31:0] rx_in_TDATA;
input   rx_in_TVALID;
output   rx_in_TREADY;
input  [3:0] rx_in_TKEEP;
input  [3:0] rx_in_TSTRB;
input  [0:0] rx_in_TLAST;
input  [31:0] dds_lo_TDATA;
input   dds_lo_TVALID;
output   dds_lo_TREADY;
input  [3:0] dds_lo_TKEEP;
input  [3:0] dds_lo_TSTRB;
input  [0:0] dds_lo_TLAST;
output  [31:0] baseband_out_TDATA;
output   baseband_out_TVALID;
input   baseband_out_TREADY;
output  [3:0] baseband_out_TKEEP;
output  [3:0] baseband_out_TSTRB;
output  [0:0] baseband_out_TLAST;

 reg    ap_rst_n_inv;
reg    rx_in_TDATA_blk_n;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_block_pp0_stage0;
reg    dds_lo_TDATA_blk_n;
reg    baseband_out_TDATA_blk_n;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg   [3:0] pkt_rx_keep_V_reg_234;
reg    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
reg    ap_block_state4_pp0_stage0_iter3;
wire    regslice_both_baseband_out_V_data_V_U_apdone_blk;
reg    ap_block_state5_pp0_stage0_iter4;
reg    ap_block_pp0_stage0_11001;
reg   [3:0] pkt_rx_keep_V_reg_234_pp0_iter1_reg;
reg   [3:0] pkt_rx_keep_V_reg_234_pp0_iter2_reg;
reg   [0:0] pkt_rx_last_V_reg_239;
reg   [0:0] pkt_rx_last_V_reg_239_pp0_iter1_reg;
reg   [0:0] pkt_rx_last_V_reg_239_pp0_iter2_reg;
wire  signed [30:0] sext_ln39_fu_163_p1;
wire  signed [30:0] sext_ln39_1_fu_167_p1;
wire  signed [30:0] sext_ln40_fu_171_p1;
wire   [30:0] mul_ln40_fu_179_p2;
reg   [30:0] mul_ln40_reg_260;
reg  signed [30:0] mul_ln40_reg_260_pp0_iter1_reg;
wire   [30:0] mul_ln41_fu_185_p2;
reg   [30:0] mul_ln41_reg_265;
reg  signed [30:0] mul_ln41_reg_265_pp0_iter1_reg;
reg    ap_enable_reg_pp0_iter1;
reg    ap_block_pp0_stage0_subdone;
reg    ap_enable_reg_pp0_iter2;
reg    ap_block_pp0_stage0_01001;
wire   [15:0] lo_i_fu_149_p1;
wire   [15:0] rx_i_fu_135_p1;
wire   [15:0] lo_q_fu_153_p4;
wire   [15:0] rx_q_fu_139_p4;
wire  signed [15:0] mul_ln40_fu_179_p0;
wire  signed [15:0] mul_ln40_fu_179_p1;
wire  signed [30:0] sext_ln40_1_fu_175_p1;
wire  signed [15:0] mul_ln41_fu_185_p0;
wire  signed [15:0] mul_ln41_fu_185_p1;
wire  signed [30:0] grp_fu_218_p3;
wire  signed [30:0] grp_fu_226_p3;
wire   [15:0] trunc_ln1_fu_200_p4;
wire   [15:0] trunc_ln_fu_191_p4;
wire  signed [15:0] grp_fu_218_p0;
wire  signed [15:0] grp_fu_218_p1;
wire  signed [15:0] grp_fu_226_p0;
wire  signed [15:0] grp_fu_226_p1;
reg    grp_fu_218_ce;
reg    grp_fu_226_ce;
reg   [0:0] ap_NS_fsm;
wire    ap_reset_idle_pp0;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
wire    regslice_both_rx_in_V_data_V_U_apdone_blk;
wire   [31:0] rx_in_TDATA_int_regslice;
wire    rx_in_TVALID_int_regslice;
reg    rx_in_TREADY_int_regslice;
wire    regslice_both_rx_in_V_data_V_U_ack_in;
wire    regslice_both_rx_in_V_keep_V_U_apdone_blk;
wire   [3:0] rx_in_TKEEP_int_regslice;
wire    regslice_both_rx_in_V_keep_V_U_vld_out;
wire    regslice_both_rx_in_V_keep_V_U_ack_in;
wire    regslice_both_rx_in_V_strb_V_U_apdone_blk;
wire   [3:0] rx_in_TSTRB_int_regslice;
wire    regslice_both_rx_in_V_strb_V_U_vld_out;
wire    regslice_both_rx_in_V_strb_V_U_ack_in;
wire    regslice_both_rx_in_V_last_V_U_apdone_blk;
wire   [0:0] rx_in_TLAST_int_regslice;
wire    regslice_both_rx_in_V_last_V_U_vld_out;
wire    regslice_both_rx_in_V_last_V_U_ack_in;
wire    regslice_both_dds_lo_V_data_V_U_apdone_blk;
wire   [31:0] dds_lo_TDATA_int_regslice;
wire    dds_lo_TVALID_int_regslice;
reg    dds_lo_TREADY_int_regslice;
wire    regslice_both_dds_lo_V_data_V_U_ack_in;
wire    regslice_both_dds_lo_V_keep_V_U_apdone_blk;
wire   [3:0] dds_lo_TKEEP_int_regslice;
wire    regslice_both_dds_lo_V_keep_V_U_vld_out;
wire    regslice_both_dds_lo_V_keep_V_U_ack_in;
wire    regslice_both_dds_lo_V_strb_V_U_apdone_blk;
wire   [3:0] dds_lo_TSTRB_int_regslice;
wire    regslice_both_dds_lo_V_strb_V_U_vld_out;
wire    regslice_both_dds_lo_V_strb_V_U_ack_in;
wire    regslice_both_dds_lo_V_last_V_U_apdone_blk;
wire   [0:0] dds_lo_TLAST_int_regslice;
wire    regslice_both_dds_lo_V_last_V_U_vld_out;
wire    regslice_both_dds_lo_V_last_V_U_ack_in;
wire   [31:0] baseband_out_TDATA_int_regslice;
reg    baseband_out_TVALID_int_regslice;
wire    baseband_out_TREADY_int_regslice;
wire    regslice_both_baseband_out_V_data_V_U_vld_out;
wire    regslice_both_baseband_out_V_keep_V_U_apdone_blk;
wire    regslice_both_baseband_out_V_keep_V_U_ack_in_dummy;
wire    regslice_both_baseband_out_V_keep_V_U_vld_out;
wire    regslice_both_baseband_out_V_strb_V_U_apdone_blk;
wire    regslice_both_baseband_out_V_strb_V_U_ack_in_dummy;
wire    regslice_both_baseband_out_V_strb_V_U_vld_out;
wire    regslice_both_baseband_out_V_last_V_U_apdone_blk;
wire    regslice_both_baseband_out_V_last_V_U_ack_in_dummy;
wire    regslice_both_baseband_out_V_last_V_U_vld_out;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
end

fsk_ddc_mul_16s_16s_31_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 31 ))
mul_16s_16s_31_1_1_U1(
    .din0(mul_ln40_fu_179_p0),
    .din1(mul_ln40_fu_179_p1),
    .dout(mul_ln40_fu_179_p2)
);

fsk_ddc_mul_16s_16s_31_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 31 ))
mul_16s_16s_31_1_1_U2(
    .din0(mul_ln41_fu_185_p0),
    .din1(mul_ln41_fu_185_p1),
    .dout(mul_ln41_fu_185_p2)
);

fsk_ddc_mac_muladd_16s_16s_31s_31_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 31 ),
    .dout_WIDTH( 31 ))
mac_muladd_16s_16s_31s_31_4_1_U3(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_218_p0),
    .din1(grp_fu_218_p1),
    .din2(mul_ln40_reg_260_pp0_iter1_reg),
    .ce(grp_fu_218_ce),
    .dout(grp_fu_218_p3)
);

fsk_ddc_mac_mulsub_16s_16s_31s_31_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 31 ),
    .dout_WIDTH( 31 ))
mac_mulsub_16s_16s_31s_31_4_1_U4(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_226_p0),
    .din1(grp_fu_226_p1),
    .din2(mul_ln41_reg_265_pp0_iter1_reg),
    .ce(grp_fu_226_ce),
    .dout(grp_fu_226_p3)
);

fsk_ddc_regslice_both #(
    .DataWidth( 32 ))
regslice_both_rx_in_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(rx_in_TDATA),
    .vld_in(rx_in_TVALID),
    .ack_in(regslice_both_rx_in_V_data_V_U_ack_in),
    .data_out(rx_in_TDATA_int_regslice),
    .vld_out(rx_in_TVALID_int_regslice),
    .ack_out(rx_in_TREADY_int_regslice),
    .apdone_blk(regslice_both_rx_in_V_data_V_U_apdone_blk)
);

fsk_ddc_regslice_both #(
    .DataWidth( 4 ))
regslice_both_rx_in_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(rx_in_TKEEP),
    .vld_in(rx_in_TVALID),
    .ack_in(regslice_both_rx_in_V_keep_V_U_ack_in),
    .data_out(rx_in_TKEEP_int_regslice),
    .vld_out(regslice_both_rx_in_V_keep_V_U_vld_out),
    .ack_out(rx_in_TREADY_int_regslice),
    .apdone_blk(regslice_both_rx_in_V_keep_V_U_apdone_blk)
);

fsk_ddc_regslice_both #(
    .DataWidth( 4 ))
regslice_both_rx_in_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(rx_in_TSTRB),
    .vld_in(rx_in_TVALID),
    .ack_in(regslice_both_rx_in_V_strb_V_U_ack_in),
    .data_out(rx_in_TSTRB_int_regslice),
    .vld_out(regslice_both_rx_in_V_strb_V_U_vld_out),
    .ack_out(rx_in_TREADY_int_regslice),
    .apdone_blk(regslice_both_rx_in_V_strb_V_U_apdone_blk)
);

fsk_ddc_regslice_both #(
    .DataWidth( 1 ))
regslice_both_rx_in_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(rx_in_TLAST),
    .vld_in(rx_in_TVALID),
    .ack_in(regslice_both_rx_in_V_last_V_U_ack_in),
    .data_out(rx_in_TLAST_int_regslice),
    .vld_out(regslice_both_rx_in_V_last_V_U_vld_out),
    .ack_out(rx_in_TREADY_int_regslice),
    .apdone_blk(regslice_both_rx_in_V_last_V_U_apdone_blk)
);

fsk_ddc_regslice_both #(
    .DataWidth( 32 ))
regslice_both_dds_lo_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(dds_lo_TDATA),
    .vld_in(dds_lo_TVALID),
    .ack_in(regslice_both_dds_lo_V_data_V_U_ack_in),
    .data_out(dds_lo_TDATA_int_regslice),
    .vld_out(dds_lo_TVALID_int_regslice),
    .ack_out(dds_lo_TREADY_int_regslice),
    .apdone_blk(regslice_both_dds_lo_V_data_V_U_apdone_blk)
);

fsk_ddc_regslice_both #(
    .DataWidth( 4 ))
regslice_both_dds_lo_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(dds_lo_TKEEP),
    .vld_in(dds_lo_TVALID),
    .ack_in(regslice_both_dds_lo_V_keep_V_U_ack_in),
    .data_out(dds_lo_TKEEP_int_regslice),
    .vld_out(regslice_both_dds_lo_V_keep_V_U_vld_out),
    .ack_out(dds_lo_TREADY_int_regslice),
    .apdone_blk(regslice_both_dds_lo_V_keep_V_U_apdone_blk)
);

fsk_ddc_regslice_both #(
    .DataWidth( 4 ))
regslice_both_dds_lo_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(dds_lo_TSTRB),
    .vld_in(dds_lo_TVALID),
    .ack_in(regslice_both_dds_lo_V_strb_V_U_ack_in),
    .data_out(dds_lo_TSTRB_int_regslice),
    .vld_out(regslice_both_dds_lo_V_strb_V_U_vld_out),
    .ack_out(dds_lo_TREADY_int_regslice),
    .apdone_blk(regslice_both_dds_lo_V_strb_V_U_apdone_blk)
);

fsk_ddc_regslice_both #(
    .DataWidth( 1 ))
regslice_both_dds_lo_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(dds_lo_TLAST),
    .vld_in(dds_lo_TVALID),
    .ack_in(regslice_both_dds_lo_V_last_V_U_ack_in),
    .data_out(dds_lo_TLAST_int_regslice),
    .vld_out(regslice_both_dds_lo_V_last_V_U_vld_out),
    .ack_out(dds_lo_TREADY_int_regslice),
    .apdone_blk(regslice_both_dds_lo_V_last_V_U_apdone_blk)
);

fsk_ddc_regslice_both #(
    .DataWidth( 32 ))
regslice_both_baseband_out_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(baseband_out_TDATA_int_regslice),
    .vld_in(baseband_out_TVALID_int_regslice),
    .ack_in(baseband_out_TREADY_int_regslice),
    .data_out(baseband_out_TDATA),
    .vld_out(regslice_both_baseband_out_V_data_V_U_vld_out),
    .ack_out(baseband_out_TREADY),
    .apdone_blk(regslice_both_baseband_out_V_data_V_U_apdone_blk)
);

fsk_ddc_regslice_both #(
    .DataWidth( 4 ))
regslice_both_baseband_out_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(pkt_rx_keep_V_reg_234_pp0_iter2_reg),
    .vld_in(baseband_out_TVALID_int_regslice),
    .ack_in(regslice_both_baseband_out_V_keep_V_U_ack_in_dummy),
    .data_out(baseband_out_TKEEP),
    .vld_out(regslice_both_baseband_out_V_keep_V_U_vld_out),
    .ack_out(baseband_out_TREADY),
    .apdone_blk(regslice_both_baseband_out_V_keep_V_U_apdone_blk)
);

fsk_ddc_regslice_both #(
    .DataWidth( 4 ))
regslice_both_baseband_out_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(4'd0),
    .vld_in(baseband_out_TVALID_int_regslice),
    .ack_in(regslice_both_baseband_out_V_strb_V_U_ack_in_dummy),
    .data_out(baseband_out_TSTRB),
    .vld_out(regslice_both_baseband_out_V_strb_V_U_vld_out),
    .ack_out(baseband_out_TREADY),
    .apdone_blk(regslice_both_baseband_out_V_strb_V_U_apdone_blk)
);

fsk_ddc_regslice_both #(
    .DataWidth( 1 ))
regslice_both_baseband_out_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(pkt_rx_last_V_reg_239_pp0_iter2_reg),
    .vld_in(baseband_out_TVALID_int_regslice),
    .ack_in(regslice_both_baseband_out_V_last_V_U_ack_in_dummy),
    .data_out(baseband_out_TLAST),
    .vld_out(regslice_both_baseband_out_V_last_V_U_vld_out),
    .ack_out(baseband_out_TREADY),
    .apdone_blk(regslice_both_baseband_out_V_last_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        mul_ln40_reg_260 <= mul_ln40_fu_179_p2;
        mul_ln40_reg_260_pp0_iter1_reg <= mul_ln40_reg_260;
        mul_ln41_reg_265 <= mul_ln41_fu_185_p2;
        mul_ln41_reg_265_pp0_iter1_reg <= mul_ln41_reg_265;
        pkt_rx_keep_V_reg_234 <= rx_in_TKEEP_int_regslice;
        pkt_rx_keep_V_reg_234_pp0_iter1_reg <= pkt_rx_keep_V_reg_234;
        pkt_rx_last_V_reg_239 <= rx_in_TLAST_int_regslice;
        pkt_rx_last_V_reg_239_pp0_iter1_reg <= pkt_rx_last_V_reg_239;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        pkt_rx_keep_V_reg_234_pp0_iter2_reg <= pkt_rx_keep_V_reg_234_pp0_iter1_reg;
        pkt_rx_last_V_reg_239_pp0_iter2_reg <= pkt_rx_last_V_reg_239_pp0_iter1_reg;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (1'b1 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

assign ap_reset_idle_pp0 = 1'b0;

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0)) | ((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0)))) begin
        baseband_out_TDATA_blk_n = baseband_out_TREADY_int_regslice;
    end else begin
        baseband_out_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        baseband_out_TVALID_int_regslice = 1'b1;
    end else begin
        baseband_out_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dds_lo_TDATA_blk_n = dds_lo_TVALID_int_regslice;
    end else begin
        dds_lo_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dds_lo_TREADY_int_regslice = 1'b1;
    end else begin
        dds_lo_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_218_ce = 1'b1;
    end else begin
        grp_fu_218_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_226_ce = 1'b1;
    end else begin
        grp_fu_226_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        rx_in_TDATA_blk_n = rx_in_TVALID_int_regslice;
    end else begin
        rx_in_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        rx_in_TREADY_int_regslice = 1'b1;
    end else begin
        rx_in_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((ap_enable_reg_pp0_iter4 == 1'b1) & ((regslice_both_baseband_out_V_data_V_U_apdone_blk == 1'b1) | (baseband_out_TREADY_int_regslice == 1'b0))) | ((ap_enable_reg_pp0_iter3 == 1'b1) & (baseband_out_TREADY_int_regslice == 1'b0)) | ((1'b1 == 1'b1) & ((dds_lo_TVALID_int_regslice == 1'b0) | (rx_in_TVALID_int_regslice == 1'b0))));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter4 == 1'b1) & ((regslice_both_baseband_out_V_data_V_U_apdone_blk == 1'b1) | (baseband_out_TREADY_int_regslice == 1'b0))) | ((ap_enable_reg_pp0_iter3 == 1'b1) & (baseband_out_TREADY_int_regslice == 1'b0)) | ((1'b1 == 1'b1) & ((dds_lo_TVALID_int_regslice == 1'b0) | (rx_in_TVALID_int_regslice == 1'b0))));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter4 == 1'b1) & ((regslice_both_baseband_out_V_data_V_U_apdone_blk == 1'b1) | (baseband_out_TREADY_int_regslice == 1'b0))) | ((ap_enable_reg_pp0_iter3 == 1'b1) & (baseband_out_TREADY_int_regslice == 1'b0)) | ((1'b1 == 1'b1) & ((dds_lo_TVALID_int_regslice == 1'b0) | (rx_in_TVALID_int_regslice == 1'b0))));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((dds_lo_TVALID_int_regslice == 1'b0) | (rx_in_TVALID_int_regslice == 1'b0));
end

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state4_pp0_stage0_iter3 = (baseband_out_TREADY_int_regslice == 1'b0);
end

always @ (*) begin
    ap_block_state5_pp0_stage0_iter4 = ((regslice_both_baseband_out_V_data_V_U_apdone_blk == 1'b1) | (baseband_out_TREADY_int_regslice == 1'b0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign baseband_out_TDATA_int_regslice = {{trunc_ln1_fu_200_p4}, {trunc_ln_fu_191_p4}};

assign baseband_out_TVALID = regslice_both_baseband_out_V_data_V_U_vld_out;

assign dds_lo_TREADY = regslice_both_dds_lo_V_data_V_U_ack_in;

assign grp_fu_218_p0 = sext_ln39_fu_163_p1;

assign grp_fu_218_p1 = sext_ln39_1_fu_167_p1;

assign grp_fu_226_p0 = sext_ln40_fu_171_p1;

assign grp_fu_226_p1 = sext_ln39_1_fu_167_p1;

assign lo_i_fu_149_p1 = dds_lo_TDATA_int_regslice[15:0];

assign lo_q_fu_153_p4 = {{dds_lo_TDATA_int_regslice[31:16]}};

assign mul_ln40_fu_179_p0 = sext_ln40_fu_171_p1;

assign mul_ln40_fu_179_p1 = sext_ln40_1_fu_175_p1;

assign mul_ln41_fu_185_p0 = sext_ln39_fu_163_p1;

assign mul_ln41_fu_185_p1 = sext_ln40_1_fu_175_p1;

assign rx_i_fu_135_p1 = rx_in_TDATA_int_regslice[15:0];

assign rx_in_TREADY = regslice_both_rx_in_V_data_V_U_ack_in;

assign rx_q_fu_139_p4 = {{rx_in_TDATA_int_regslice[31:16]}};

assign sext_ln39_1_fu_167_p1 = $signed(rx_i_fu_135_p1);

assign sext_ln39_fu_163_p1 = $signed(lo_i_fu_149_p1);

assign sext_ln40_1_fu_175_p1 = $signed(rx_q_fu_139_p4);

assign sext_ln40_fu_171_p1 = $signed(lo_q_fu_153_p4);

assign trunc_ln1_fu_200_p4 = {{grp_fu_226_p3[30:15]}};

assign trunc_ln_fu_191_p4 = {{grp_fu_218_p3[30:15]}};


reg find_kernel_block = 0;
// synthesis translate_off
`include "fsk_ddc_hls_deadlock_kernel_monitor_top.vh"
// synthesis translate_on

endmodule //fsk_ddc

