-- ==============================================================
-- Generated by Vitis HLS v2023.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity fsk_discriminator is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    in_stream_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    in_stream_TVALID : IN STD_LOGIC;
    in_stream_TREADY : OUT STD_LOGIC;
    in_stream_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
    in_stream_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
    in_stream_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    out_stream_TDATA : OUT STD_LOGIC_VECTOR (15 downto 0);
    out_stream_TVALID : OUT STD_LOGIC;
    out_stream_TREADY : IN STD_LOGIC;
    out_stream_TKEEP : OUT STD_LOGIC_VECTOR (1 downto 0);
    out_stream_TSTRB : OUT STD_LOGIC_VECTOR (1 downto 0);
    out_stream_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0) );
end;


architecture behav of fsk_discriminator is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "fsk_discriminator_fsk_discriminator,hls_ip_2023_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=pipeline,HLS_SYN_CLOCK=6.805437,HLS_SYN_LAT=4,HLS_SYN_TPT=1,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=327,HLS_SYN_LUT=532,HLS_VERSION=2023_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_FF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011111111";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_1A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011010";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv21_1F8000 : STD_LOGIC_VECTOR (20 downto 0) := "111111000000000000000";
    constant ap_const_lv16_7FFF : STD_LOGIC_VECTOR (15 downto 0) := "0111111111111111";
    constant ap_const_lv16_8000 : STD_LOGIC_VECTOR (15 downto 0) := "1000000000000000";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_15 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010101";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv26_3FF8000 : STD_LOGIC_VECTOR (25 downto 0) := "11111111111000000000000000";

    signal ap_rst_n_inv : STD_LOGIC;
    signal sum_i : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal sum_q : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal counter : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal i_old : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal q_old : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal in_stream_TDATA_blk_n : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal out_stream_TDATA_blk_n : STD_LOGIC;
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal icmp_ln52_reg_494 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln52_reg_494_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal icmp_ln52_reg_494_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal pkt_last_V_reg_489 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_state4_io : BOOLEAN;
    signal regslice_both_out_stream_V_data_V_U_apdone_blk : STD_LOGIC;
    signal ap_block_state5_pp0_stage0_iter4 : BOOLEAN;
    signal ap_block_state5_io : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal pkt_last_V_reg_489_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal pkt_last_V_reg_489_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln52_fu_225_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln52_reg_494_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal i_curr_fu_297_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal i_curr_reg_498 : STD_LOGIC_VECTOR (15 downto 0);
    signal q_curr_fu_351_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal q_curr_reg_503 : STD_LOGIC_VECTOR (15 downto 0);
    signal term1_fu_406_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal term1_reg_518 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_phi_mux_sum_i_new_0_phi_fu_135_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter0_sum_i_new_0_reg_132 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln47_fu_192_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_mux_sum_q_new_0_phi_fu_145_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter0_sum_q_new_0_reg_142 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln48_fu_207_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_mux_counter_new_0_phi_fu_155_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter0_counter_new_0_reg_152 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln49_fu_218_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal raw_i_fu_170_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln47_fu_184_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal raw_q_fu_174_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln48_fu_199_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_fu_251_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal trunc_ln_fu_231_p4 : STD_LOGIC_VECTOR (20 downto 0);
    signal icmp_ln21_fu_261_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln23_fu_267_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln21_fu_291_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln21_fu_283_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln2_fu_273_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_1_fu_305_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal trunc_ln1_fu_241_p4 : STD_LOGIC_VECTOR (20 downto 0);
    signal icmp_ln21_1_fu_315_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln23_1_fu_321_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln21_1_fu_345_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln21_2_fu_337_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln26_1_fu_327_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_479_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_2_fu_426_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal trunc_ln3_fu_417_p4 : STD_LOGIC_VECTOR (25 downto 0);
    signal icmp_ln21_2_fu_435_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln23_2_fu_441_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln21_2_fu_464_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln21_4_fu_456_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln26_2_fu_447_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_479_ce : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reset_idle_pp0 : STD_LOGIC;
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal regslice_both_in_stream_V_data_V_U_apdone_blk : STD_LOGIC;
    signal in_stream_TDATA_int_regslice : STD_LOGIC_VECTOR (31 downto 0);
    signal in_stream_TVALID_int_regslice : STD_LOGIC;
    signal in_stream_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_in_stream_V_data_V_U_ack_in : STD_LOGIC;
    signal regslice_both_in_stream_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal in_stream_TKEEP_int_regslice : STD_LOGIC_VECTOR (3 downto 0);
    signal regslice_both_in_stream_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_in_stream_V_keep_V_U_ack_in : STD_LOGIC;
    signal regslice_both_in_stream_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal in_stream_TSTRB_int_regslice : STD_LOGIC_VECTOR (3 downto 0);
    signal regslice_both_in_stream_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_in_stream_V_strb_V_U_ack_in : STD_LOGIC;
    signal regslice_both_in_stream_V_last_V_U_apdone_blk : STD_LOGIC;
    signal in_stream_TLAST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_in_stream_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_in_stream_V_last_V_U_ack_in : STD_LOGIC;
    signal out_stream_TDATA_int_regslice : STD_LOGIC_VECTOR (15 downto 0);
    signal out_stream_TVALID_int_regslice : STD_LOGIC;
    signal out_stream_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_out_stream_V_data_V_U_vld_out : STD_LOGIC;
    signal regslice_both_out_stream_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_out_stream_V_keep_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_out_stream_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_out_stream_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_out_stream_V_strb_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_out_stream_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_out_stream_V_last_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_out_stream_V_last_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_out_stream_V_last_V_U_vld_out : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component fsk_discriminator_mul_16s_16s_32_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component fsk_discriminator_mac_mulsub_16s_16s_32s_32_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        din2 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component fsk_discriminator_regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    mul_16s_16s_32_1_1_U1 : component fsk_discriminator_mul_16s_16s_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        dout_WIDTH => 32)
    port map (
        din0 => i_old,
        din1 => q_curr_reg_503,
        dout => term1_fu_406_p2);

    mac_mulsub_16s_16s_32s_32_4_1_U2 : component fsk_discriminator_mac_mulsub_16s_16s_32s_32_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        din2_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => q_old,
        din1 => i_curr_fu_297_p3,
        din2 => term1_reg_518,
        ce => grp_fu_479_ce,
        dout => grp_fu_479_p3);

    regslice_both_in_stream_V_data_V_U : component fsk_discriminator_regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_stream_TDATA,
        vld_in => in_stream_TVALID,
        ack_in => regslice_both_in_stream_V_data_V_U_ack_in,
        data_out => in_stream_TDATA_int_regslice,
        vld_out => in_stream_TVALID_int_regslice,
        ack_out => in_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_in_stream_V_data_V_U_apdone_blk);

    regslice_both_in_stream_V_keep_V_U : component fsk_discriminator_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_stream_TKEEP,
        vld_in => in_stream_TVALID,
        ack_in => regslice_both_in_stream_V_keep_V_U_ack_in,
        data_out => in_stream_TKEEP_int_regslice,
        vld_out => regslice_both_in_stream_V_keep_V_U_vld_out,
        ack_out => in_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_in_stream_V_keep_V_U_apdone_blk);

    regslice_both_in_stream_V_strb_V_U : component fsk_discriminator_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_stream_TSTRB,
        vld_in => in_stream_TVALID,
        ack_in => regslice_both_in_stream_V_strb_V_U_ack_in,
        data_out => in_stream_TSTRB_int_regslice,
        vld_out => regslice_both_in_stream_V_strb_V_U_vld_out,
        ack_out => in_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_in_stream_V_strb_V_U_apdone_blk);

    regslice_both_in_stream_V_last_V_U : component fsk_discriminator_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_stream_TLAST,
        vld_in => in_stream_TVALID,
        ack_in => regslice_both_in_stream_V_last_V_U_ack_in,
        data_out => in_stream_TLAST_int_regslice,
        vld_out => regslice_both_in_stream_V_last_V_U_vld_out,
        ack_out => in_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_in_stream_V_last_V_U_apdone_blk);

    regslice_both_out_stream_V_data_V_U : component fsk_discriminator_regslice_both
    generic map (
        DataWidth => 16)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => out_stream_TDATA_int_regslice,
        vld_in => out_stream_TVALID_int_regslice,
        ack_in => out_stream_TREADY_int_regslice,
        data_out => out_stream_TDATA,
        vld_out => regslice_both_out_stream_V_data_V_U_vld_out,
        ack_out => out_stream_TREADY,
        apdone_blk => regslice_both_out_stream_V_data_V_U_apdone_blk);

    regslice_both_out_stream_V_keep_V_U : component fsk_discriminator_regslice_both
    generic map (
        DataWidth => 2)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => ap_const_lv2_3,
        vld_in => out_stream_TVALID_int_regslice,
        ack_in => regslice_both_out_stream_V_keep_V_U_ack_in_dummy,
        data_out => out_stream_TKEEP,
        vld_out => regslice_both_out_stream_V_keep_V_U_vld_out,
        ack_out => out_stream_TREADY,
        apdone_blk => regslice_both_out_stream_V_keep_V_U_apdone_blk);

    regslice_both_out_stream_V_strb_V_U : component fsk_discriminator_regslice_both
    generic map (
        DataWidth => 2)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => ap_const_lv2_0,
        vld_in => out_stream_TVALID_int_regslice,
        ack_in => regslice_both_out_stream_V_strb_V_U_ack_in_dummy,
        data_out => out_stream_TSTRB,
        vld_out => regslice_both_out_stream_V_strb_V_U_vld_out,
        ack_out => out_stream_TREADY,
        apdone_blk => regslice_both_out_stream_V_strb_V_U_apdone_blk);

    regslice_both_out_stream_V_last_V_U : component fsk_discriminator_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => pkt_last_V_reg_489_pp0_iter2_reg,
        vld_in => out_stream_TVALID_int_regslice,
        ack_in => regslice_both_out_stream_V_last_V_U_ack_in_dummy,
        data_out => out_stream_TLAST,
        vld_out => regslice_both_out_stream_V_last_V_U_vld_out,
        ack_out => out_stream_TREADY,
        apdone_blk => regslice_both_out_stream_V_last_V_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                counter <= ap_phi_mux_counter_new_0_phi_fu_155_p4;
                sum_i <= ap_phi_mux_sum_i_new_0_phi_fu_135_p4;
                sum_q <= ap_phi_mux_sum_q_new_0_phi_fu_145_p4;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln52_fu_225_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                i_curr_reg_498 <= i_curr_fu_297_p3;
                q_curr_reg_503 <= q_curr_fu_351_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln52_reg_494 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then
                i_old <= i_curr_reg_498;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                icmp_ln52_reg_494 <= icmp_ln52_fu_225_p2;
                icmp_ln52_reg_494_pp0_iter1_reg <= icmp_ln52_reg_494;
                pkt_last_V_reg_489 <= in_stream_TLAST_int_regslice;
                pkt_last_V_reg_489_pp0_iter1_reg <= pkt_last_V_reg_489;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                icmp_ln52_reg_494_pp0_iter2_reg <= icmp_ln52_reg_494_pp0_iter1_reg;
                icmp_ln52_reg_494_pp0_iter3_reg <= icmp_ln52_reg_494_pp0_iter2_reg;
                pkt_last_V_reg_489_pp0_iter2_reg <= pkt_last_V_reg_489_pp0_iter1_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln52_fu_225_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                q_old <= q_curr_fu_351_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln52_reg_494 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                term1_reg_518 <= term1_fu_406_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage0_subdone, ap_reset_idle_pp0)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln47_fu_192_p2 <= std_logic_vector(unsigned(sum_i) + unsigned(sext_ln47_fu_184_p1));
    add_ln48_fu_207_p2 <= std_logic_vector(unsigned(sum_q) + unsigned(sext_ln48_fu_199_p1));
    add_ln49_fu_218_p2 <= std_logic_vector(unsigned(counter) + unsigned(ap_const_lv32_1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_enable_reg_pp0_iter3, icmp_ln52_reg_494_pp0_iter2_reg, ap_enable_reg_pp0_iter4, icmp_ln52_reg_494_pp0_iter3_reg, regslice_both_out_stream_V_data_V_U_apdone_blk, in_stream_TVALID_int_regslice, out_stream_TREADY_int_regslice)
    begin
                ap_block_pp0_stage0_01001 <= (((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and ((regslice_both_out_stream_V_data_V_U_apdone_blk = ap_const_logic_1) or ((icmp_ln52_reg_494_pp0_iter3_reg = ap_const_lv1_1) and (out_stream_TREADY_int_regslice = ap_const_logic_0)))) or ((icmp_ln52_reg_494_pp0_iter2_reg = ap_const_lv1_1) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (out_stream_TREADY_int_regslice = ap_const_logic_0)) or ((in_stream_TVALID_int_regslice = ap_const_logic_0) and (ap_const_logic_1 = ap_const_logic_1)));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter3, icmp_ln52_reg_494_pp0_iter2_reg, ap_enable_reg_pp0_iter4, icmp_ln52_reg_494_pp0_iter3_reg, ap_block_state4_io, regslice_both_out_stream_V_data_V_U_apdone_blk, ap_block_state5_io, in_stream_TVALID_int_regslice, out_stream_TREADY_int_regslice)
    begin
                ap_block_pp0_stage0_11001 <= (((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and ((regslice_both_out_stream_V_data_V_U_apdone_blk = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state5_io) or ((icmp_ln52_reg_494_pp0_iter3_reg = ap_const_lv1_1) and (out_stream_TREADY_int_regslice = ap_const_logic_0)))) or ((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and ((ap_const_boolean_1 = ap_block_state4_io) or ((icmp_ln52_reg_494_pp0_iter2_reg = ap_const_lv1_1) and (out_stream_TREADY_int_regslice = ap_const_logic_0)))) or ((in_stream_TVALID_int_regslice = ap_const_logic_0) and (ap_const_logic_1 = ap_const_logic_1)));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter3, icmp_ln52_reg_494_pp0_iter2_reg, ap_enable_reg_pp0_iter4, icmp_ln52_reg_494_pp0_iter3_reg, ap_block_state4_io, regslice_both_out_stream_V_data_V_U_apdone_blk, ap_block_state5_io, in_stream_TVALID_int_regslice, out_stream_TREADY_int_regslice)
    begin
                ap_block_pp0_stage0_subdone <= (((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and ((regslice_both_out_stream_V_data_V_U_apdone_blk = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state5_io) or ((icmp_ln52_reg_494_pp0_iter3_reg = ap_const_lv1_1) and (out_stream_TREADY_int_regslice = ap_const_logic_0)))) or ((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and ((ap_const_boolean_1 = ap_block_state4_io) or ((icmp_ln52_reg_494_pp0_iter2_reg = ap_const_lv1_1) and (out_stream_TREADY_int_regslice = ap_const_logic_0)))) or ((in_stream_TVALID_int_regslice = ap_const_logic_0) and (ap_const_logic_1 = ap_const_logic_1)));
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(in_stream_TVALID_int_regslice)
    begin
                ap_block_state1_pp0_stage0_iter0 <= (in_stream_TVALID_int_regslice = ap_const_logic_0);
    end process;

        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state4_io_assign_proc : process(icmp_ln52_reg_494_pp0_iter2_reg, out_stream_TREADY_int_regslice)
    begin
                ap_block_state4_io <= ((icmp_ln52_reg_494_pp0_iter2_reg = ap_const_lv1_1) and (out_stream_TREADY_int_regslice = ap_const_logic_0));
    end process;


    ap_block_state4_pp0_stage0_iter3_assign_proc : process(icmp_ln52_reg_494_pp0_iter2_reg, out_stream_TREADY_int_regslice)
    begin
                ap_block_state4_pp0_stage0_iter3 <= ((icmp_ln52_reg_494_pp0_iter2_reg = ap_const_lv1_1) and (out_stream_TREADY_int_regslice = ap_const_logic_0));
    end process;


    ap_block_state5_io_assign_proc : process(icmp_ln52_reg_494_pp0_iter3_reg, out_stream_TREADY_int_regslice)
    begin
                ap_block_state5_io <= ((icmp_ln52_reg_494_pp0_iter3_reg = ap_const_lv1_1) and (out_stream_TREADY_int_regslice = ap_const_logic_0));
    end process;


    ap_block_state5_pp0_stage0_iter4_assign_proc : process(icmp_ln52_reg_494_pp0_iter3_reg, regslice_both_out_stream_V_data_V_U_apdone_blk, out_stream_TREADY_int_regslice)
    begin
                ap_block_state5_pp0_stage0_iter4 <= ((regslice_both_out_stream_V_data_V_U_apdone_blk = ap_const_logic_1) or ((icmp_ln52_reg_494_pp0_iter3_reg = ap_const_lv1_1) and (out_stream_TREADY_int_regslice = ap_const_logic_0)));
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_const_logic_1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_counter_new_0_phi_fu_155_p4_assign_proc : process(icmp_ln52_fu_225_p2, ap_phi_reg_pp0_iter0_counter_new_0_reg_152, add_ln49_fu_218_p2)
    begin
        if ((icmp_ln52_fu_225_p2 = ap_const_lv1_0)) then 
            ap_phi_mux_counter_new_0_phi_fu_155_p4 <= add_ln49_fu_218_p2;
        elsif ((icmp_ln52_fu_225_p2 = ap_const_lv1_1)) then 
            ap_phi_mux_counter_new_0_phi_fu_155_p4 <= ap_const_lv32_0;
        else 
            ap_phi_mux_counter_new_0_phi_fu_155_p4 <= ap_phi_reg_pp0_iter0_counter_new_0_reg_152;
        end if; 
    end process;


    ap_phi_mux_sum_i_new_0_phi_fu_135_p4_assign_proc : process(icmp_ln52_fu_225_p2, ap_phi_reg_pp0_iter0_sum_i_new_0_reg_132, add_ln47_fu_192_p2)
    begin
        if ((icmp_ln52_fu_225_p2 = ap_const_lv1_0)) then 
            ap_phi_mux_sum_i_new_0_phi_fu_135_p4 <= add_ln47_fu_192_p2;
        elsif ((icmp_ln52_fu_225_p2 = ap_const_lv1_1)) then 
            ap_phi_mux_sum_i_new_0_phi_fu_135_p4 <= ap_const_lv32_0;
        else 
            ap_phi_mux_sum_i_new_0_phi_fu_135_p4 <= ap_phi_reg_pp0_iter0_sum_i_new_0_reg_132;
        end if; 
    end process;


    ap_phi_mux_sum_q_new_0_phi_fu_145_p4_assign_proc : process(icmp_ln52_fu_225_p2, ap_phi_reg_pp0_iter0_sum_q_new_0_reg_142, add_ln48_fu_207_p2)
    begin
        if ((icmp_ln52_fu_225_p2 = ap_const_lv1_0)) then 
            ap_phi_mux_sum_q_new_0_phi_fu_145_p4 <= add_ln48_fu_207_p2;
        elsif ((icmp_ln52_fu_225_p2 = ap_const_lv1_1)) then 
            ap_phi_mux_sum_q_new_0_phi_fu_145_p4 <= ap_const_lv32_0;
        else 
            ap_phi_mux_sum_q_new_0_phi_fu_145_p4 <= ap_phi_reg_pp0_iter0_sum_q_new_0_reg_142;
        end if; 
    end process;

    ap_phi_reg_pp0_iter0_counter_new_0_reg_152 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter0_sum_i_new_0_reg_132 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter0_sum_q_new_0_reg_142 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    ap_reset_idle_pp0 <= ap_const_logic_0;

    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;


    grp_fu_479_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_479_ce <= ap_const_logic_1;
        else 
            grp_fu_479_ce <= ap_const_logic_0;
        end if; 
    end process;

    i_curr_fu_297_p3 <= 
        select_ln21_fu_283_p3 when (or_ln21_fu_291_p2(0) = '1') else 
        trunc_ln2_fu_273_p4;
    icmp_ln21_1_fu_315_p2 <= "1" when (signed(tmp_1_fu_305_p4) > signed(ap_const_lv6_0)) else "0";
    icmp_ln21_2_fu_435_p2 <= "1" when (signed(tmp_2_fu_426_p4) > signed(ap_const_lv11_0)) else "0";
    icmp_ln21_fu_261_p2 <= "1" when (signed(tmp_fu_251_p4) > signed(ap_const_lv6_0)) else "0";
    icmp_ln23_1_fu_321_p2 <= "1" when (signed(trunc_ln1_fu_241_p4) < signed(ap_const_lv21_1F8000)) else "0";
    icmp_ln23_2_fu_441_p2 <= "1" when (signed(trunc_ln3_fu_417_p4) < signed(ap_const_lv26_3FF8000)) else "0";
    icmp_ln23_fu_267_p2 <= "1" when (signed(trunc_ln_fu_231_p4) < signed(ap_const_lv21_1F8000)) else "0";
    icmp_ln52_fu_225_p2 <= "1" when (add_ln49_fu_218_p2 = ap_const_lv32_FF) else "0";

    in_stream_TDATA_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, in_stream_TVALID_int_regslice)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            in_stream_TDATA_blk_n <= in_stream_TVALID_int_regslice;
        else 
            in_stream_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    in_stream_TREADY <= regslice_both_in_stream_V_data_V_U_ack_in;

    in_stream_TREADY_int_regslice_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            in_stream_TREADY_int_regslice <= ap_const_logic_1;
        else 
            in_stream_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    or_ln21_1_fu_345_p2 <= (icmp_ln23_1_fu_321_p2 or icmp_ln21_1_fu_315_p2);
    or_ln21_2_fu_464_p2 <= (icmp_ln23_2_fu_441_p2 or icmp_ln21_2_fu_435_p2);
    or_ln21_fu_291_p2 <= (icmp_ln23_fu_267_p2 or icmp_ln21_fu_261_p2);

    out_stream_TDATA_blk_n_assign_proc : process(ap_block_pp0_stage0, ap_enable_reg_pp0_iter3, icmp_ln52_reg_494_pp0_iter2_reg, ap_enable_reg_pp0_iter4, icmp_ln52_reg_494_pp0_iter3_reg, out_stream_TREADY_int_regslice)
    begin
        if ((((icmp_ln52_reg_494_pp0_iter3_reg = ap_const_lv1_1) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0)) or ((icmp_ln52_reg_494_pp0_iter2_reg = ap_const_lv1_1) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0)))) then 
            out_stream_TDATA_blk_n <= out_stream_TREADY_int_regslice;
        else 
            out_stream_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    out_stream_TDATA_int_regslice <= 
        select_ln21_4_fu_456_p3 when (or_ln21_2_fu_464_p2(0) = '1') else 
        trunc_ln26_2_fu_447_p4;
    out_stream_TVALID <= regslice_both_out_stream_V_data_V_U_vld_out;

    out_stream_TVALID_int_regslice_assign_proc : process(ap_enable_reg_pp0_iter3, icmp_ln52_reg_494_pp0_iter2_reg, ap_block_pp0_stage0_11001)
    begin
        if (((icmp_ln52_reg_494_pp0_iter2_reg = ap_const_lv1_1) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            out_stream_TVALID_int_regslice <= ap_const_logic_1;
        else 
            out_stream_TVALID_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    q_curr_fu_351_p3 <= 
        select_ln21_2_fu_337_p3 when (or_ln21_1_fu_345_p2(0) = '1') else 
        trunc_ln26_1_fu_327_p4;
    raw_i_fu_170_p1 <= in_stream_TDATA_int_regslice(16 - 1 downto 0);
    raw_q_fu_174_p4 <= in_stream_TDATA_int_regslice(31 downto 16);
    select_ln21_2_fu_337_p3 <= 
        ap_const_lv16_7FFF when (icmp_ln21_1_fu_315_p2(0) = '1') else 
        ap_const_lv16_8000;
    select_ln21_4_fu_456_p3 <= 
        ap_const_lv16_7FFF when (icmp_ln21_2_fu_435_p2(0) = '1') else 
        ap_const_lv16_8000;
    select_ln21_fu_283_p3 <= 
        ap_const_lv16_7FFF when (icmp_ln21_fu_261_p2(0) = '1') else 
        ap_const_lv16_8000;
        sext_ln47_fu_184_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(raw_i_fu_170_p1),32));

        sext_ln48_fu_199_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(raw_q_fu_174_p4),32));

    tmp_1_fu_305_p4 <= add_ln48_fu_207_p2(31 downto 26);
    tmp_2_fu_426_p4 <= grp_fu_479_p3(31 downto 21);
    tmp_fu_251_p4 <= add_ln47_fu_192_p2(31 downto 26);
    trunc_ln1_fu_241_p4 <= add_ln48_fu_207_p2(31 downto 11);
    trunc_ln26_1_fu_327_p4 <= add_ln48_fu_207_p2(26 downto 11);
    trunc_ln26_2_fu_447_p4 <= grp_fu_479_p3(21 downto 6);
    trunc_ln2_fu_273_p4 <= add_ln47_fu_192_p2(26 downto 11);
    trunc_ln3_fu_417_p4 <= grp_fu_479_p3(31 downto 6);
    trunc_ln_fu_231_p4 <= add_ln47_fu_192_p2(31 downto 11);
end behav;
